### ISSUE TITLE
Code completion using tab

### ISSUE THREAD

**Issue by nuno-agostinho** [coteditor/CotEditor#1003]
As previously mentioned in #392, it would be great to be able to press tab for auto-completion (as in accordance with other editors, including Sublime Text).

- CotEditor: 3.8.5 (384)
- System: macOS Version 10.14.6 (Build 18G87)
- Language: English

**Comment by 1024jp** [comment]
Thank you for the feedback and sorry for the late reply.

Well, because Xcode has this feature as opt-in, I need to consider it. I'm just wondering I should implement it just straightforward or as opt-in.

<img width="912" alt="Screen Shot 2020-02-21 at 16 47 15" src="https://user-images.githubusercontent.com/1165044/75014535-db24c080-54c9-11ea-8dce-5f36bbff348d.png">

**Comment by 1024jp** [comment]
Sorry, maybe I misread your request I firstly replied. I suppose the current implementation already fulfills this.
So I once close this issue. If I still misunderstand something, please feel free to comment.
