### ISSUE TITLE
Spelling should be reserved for strings/comments

### ISSUE THREAD

**Issue by nuno-agostinho** [coteditor/CotEditor#1004]
There should be an option to check spelling only on comments and strings (the spelling feature is useless for code as most of the code is underlined as misspellings).

- CotEditor: 3.8.5 (384)
- System: macOS Version 10.14.6 (Build 18G87)
- Language: English

**Comment by 1024jp** [comment]
I understand your use case, however, because CotEditor is a general plain-text editor, not all users/syntax want to check only spelling in strings/comment. For instance, in HTML, the main contents, where user may want to check the spelling, is not syntax highlighted area. In other styles, maybe another strategy. Therefore, I suppose it is not a reasonable feature even it is opt-in.

A fully-customizable speck check area feature per syntax style can be another option, but it would be too much to add to CotEditor and users may have a different preference even in the same syntax.

Thus, sorry, but I need to reject your request.

If misspelling underlines are annoying for you on some specific occasions, the Speck Check toolbar button may help to quickly toggle the feature. I know this is not a fundamental solution, but maybe something better.

<img width="752" alt="Screen Shot 2020-02-21 at 16 22 47" src="https://user-images.githubusercontent.com/1165044/75012908-76b43200-54c6-11ea-978d-e2634f7c3804.png">
