### ISSUE TITLE
Request: Save as

### ISSUE THREAD

**Issue by kool-kat** [coteditor/CotEditor#1009]
_FIrstly thanks for a great little editor._

Could you add a [save as] function?

In a typical workflow, we often incrementally make changes to existing files but need to keep the original unchanged (for testing, version control etc).

Currently, we have to copy and paste into a new document to save as a new file. Then have to remember the exact file-path and file-name of the source file to keep our filing system neat.

It would be great to have SAVE AS and have that offer up the current file path as the save location and the current filename (with string 'copy' or '2' appended before file extension).

If this feature has been asked and rejected before... I am sorry, but it is worth considering again ;-)

**Comment by 1024jp** [comment]
CotEditor changes its behavior and menu items that are related to saving depending on whether Auto Save and Versions are enabled or not (You can toggle it in Preferences > General pane).

That is:

|             | Auto Save disabled  |  Auto Save enabled   |
|------------ |------------|------------|
| File menu    | <img width="224" alt="Screen Shot 2019-11-22 at 10 20 28" src="https://user-images.githubusercontent.com/1165044/69390212-cccfd880-0d11-11ea-8e4d-6285373d141d.png"> | <img width="224" alt="Screen Shot 2019-11-22 at 10 06 14" src="https://user-images.githubusercontent.com/1165044/69390018-2b488700-0d11-11ea-8e08-e26f9cb9ae28.png"> |
| File overwrite | when user performs "Save" | automatically when document modified |
| Versions | disabled | enabled |

The differences in the menu item line-up are actually managed and provided by the macOS system according to the Autosaving availability.
Technically, I can provide the "Save As" command also in the Auto Save mode; however, it would be not recommended, because it breaks the standard macOS behavior.

So, when you want to use the original document as a template for another new document while the Auto Save is enabled, perform "Duplicate" first and then modify it in the new document window that is duplicated. I know this experience is not the same as modifying the original one first and then deciding saving it as a new file.
Another choice is disabling the Auto Save feature, but it may be not a good choice only for Save As command, 'cause then you lose the entire Auto Save & Versions feature.

**Comment by marrus-sh** [comment]
@kool-kat If you hold “option” while accessing the File menu, “Save As…” will appear in place of “Duplicate”. The shortcut Option+Shift+Command+S works as well.
