### ISSUE TITLE
[request] smaller tab symbol in inspector/outline view

### ISSUE THREAD

**Issue by yuriy-makhin** [coteditor/CotEditor#1021]
4 spaces per tab bit too much space spent for the outline view, as it's limited in width; reduce to 2 spaces per tab? (this is visible when outline picks up lines that start with tabs, which is something I often do in my todo lists).

**Comment by 1024jp** [comment]
Thank you for the feedback and sorry for my late reply.

Although I understand your need, I cannot adopt your request because it leads inconsistency, for instance when the spaces and tabs are mixed (a tab character behaves a very tricky in text drawing, I agree).
Sorry for that, but I just close this ticket.
