### ISSUE TITLE
CotEditor window size

### ISSUE THREAD

**Issue by ghost** [coteditor/CotEditor#1025]
Fill the following template, and post it on [GitHub Issues](https://github.com/coteditor/CotEditor/issues) or send to <coteditor.github@gmail.com>. Please note that the contents of the sent email can be shared on the Issue page. Please write the contents either in English or in Japanese.

-----------------------------------------------

## Environment

- CotEditor: 3.8.8 (391)
- System: macOS Version 10.15.2 (Build 19C57)
- Language: English

## Short Description

I would like to set a default screen size for when CotEditor opens.

There are window settings in the apps Preferences but they don't seem related or are ignored when the editor is first started or when a new file is created. It would be nice if CotEditor could read the screen settings and allow them to be set as the default.

## Steps to Reproduce the Issue

N/A

## Expected Result

CotEditor opens every time using the same screen size.

**Comment by 1024jp** [comment]
Do you mean the window size?
If yes, CotEditor recently (since 3.8.8) added an option in the Preferences > Window to set the default window (content) size. 

<img width="672" alt="Screen Shot 2020-02-10 at 13 50 50" src="https://user-images.githubusercontent.com/1165044/74121802-64a3db00-4c0c-11ea-8569-d3d0f36ed5c5.png">

If you mean something deferent with "screen size", please describe it more in detail.

**Comment by tiiiecherle** [comment]
Thanks for the info, this is at least what I meant ;)

It would be nice to have an option to get the old behavior 
"always open window with last used size"
back.

Thanks for this really nice editor. Using it a lot ;)

Kind regards
