### ISSUE TITLE
about file drag

### ISSUE THREAD

**Issue by zwb124** [coteditor/CotEditor#1034]
Can I add an extra setting to file drag, I usually don't need to drag to show the file path, I need to drag and drop directly open the file, thanks。

**Comment by 1024jp** [comment]
In CotEditor's preference, you can find the File Drop tab that allows you to customize the file drop behavior.
When you set "extensions: __all__ / syntax styles: __all__ / insertion format: __\<\<\<FILECONTENT\>\>\>__", then the content of the dropped file will be inserted to the dropped position.

<img width="672" alt="Screen Shot 2020-02-20 at 9 39 24 PM" src="https://user-images.githubusercontent.com/1165044/74934407-7fa2f600-5429-11ea-8f47-2c7cd0f8aea0.png">

However, if you want to open a new document window by dropping a file to any existing document window, it is impossible, because it is unnatural behavior in macOS apps. For that use case, drop your file not to a document window but to the application icon in the Dock.

**Comment by zwb124** [comment]
But software like sublime can do that? Is coteditor due to the limitations of the app store?

**Comment by 1024jp** [comment]
Sublime Text does not respect native macOS app behavior so much.
This is not a technical limitation but a kind of difference in value.
So, I don't implement it even it can.

**Comment by zwb124** [comment]
Don't you understand what you're saying, isn't the core purpose of an app being to serve people more conveniently? If this is not possible, what is the meaning of the so-called values? Please also seriously consider that I will support this process regardless of the outcome.

**Comment by 1024jp** [comment]
Sorry, but this is my hobby project, and, therefore, I just do what I want and believe.

I understand some people like this feature (I’ve received the same requests before).
But it is not my preference.
The core goal of this project is actually to develop a __true native macOS__ plain text editor. Very specific.

Please use another app that already has this feature or fork this repo.

**Comment by zwb124** [comment]
好吧，其实我只需要一个便捷小巧的文本编辑器，偶尔看看代码，但是我不太想用sublime。无意中发现您的app，完全满足我的需求，除了拖拽打开，无论怎样，还是感谢您的解答。

**Comment by zwb124** [comment]
Well, I just need a convenient, compact text editor and occasionally look at the code, but I don't really want to use sublime. Inadvertently found your app, fully meet my needs, in addition to dragging open, no matter what, or thank you for the answer.
