### ISSUE TITLE
Show current window size when changing and/or remember last window position/size?

### ISSUE THREAD

**Issue by qokelate** [coteditor/CotEditor#1036]
same as title.

**Comment by 1024jp** [comment]
> Show current window size when changing

I understand this demand; however, this kind of feature should be implemented not by a 3rd party application but by Apple itself. I do not want to introduce it to the CotEditor level.

> remember last window position/size?

The last window position is currently already remembered.
The window size is not, because the initial window size was changed to set in the preferences in CotEditor 3.8.8.
Before that, the last window size was used for the next document.
Now, I have actually a plan to fulfill both demands, setting a specific size and using the last window size, but not yet decided when I implement it.
Modifying the initial window size in the latest Cocoa is just a nightmare.

I need to reject the first request and the second request was already raised in #1025. So, I close this issue due to duplication.
