### ISSUE TITLE
Can't scroll left/right when just a very long line.

### ISSUE THREAD

**Issue by qokelate** [coteditor/CotEditor#1037]
Reproduce:

1.copy a very long line(just one line).
2.open coteditor, paste line
3.disable softwrap(format/unwrap)
4.try move cursor to end(H-Scrollbar not show)......

BTW:
Possable, line count include last blank line?

"" = line 0
"a" = line1
"\n" = line 1
"\n\n" = line 2
It looks like bug.......

**Comment by 1024jp** [comment]
Thank you for the feedback.
I succeed in reproducing the phenomenon and think this must be a bug.
I'll try fixing it.


> Possable, line count include last blank line?

I guess this was originally intentionally designed so.
However, because I recently also felt strange about omitting the last blank line, I changed to include the last blank line in the next CotEditor 3.9.0.

**Comment by 1024jp** [comment]
The current workaround for this issue is resizing the window. Then, the horizontal scroller will appear.
Well, this is just a workaround. I'm still not sure why the scroller doesn't appear properly, but I'll fix it.

**Comment by 1024jp** [comment]
Fixed.
