### ISSUE TITLE
Kotlin syntax

### ISSUE THREAD

**Issue by global667** [coteditor/CotEditor#1038]
val \`I can't believe this is not an error!\` = 0

Will parsed wrong. See https://kotlinlang.org/docs/tutorials/kotlin-for-py/declaring-variables.html#scopes-and-naming

**Comment by 1024jp** [comment]
Thank you for the feedback.
Because the current CotEditor' syntax highlighting cannot just ignore specific patterns, I'll treat it just the same as other variable-like keywords, such as `this` and `super`.

<img width="752" alt="Screen Shot 2020-03-02 at 13 53 46" src="https://user-images.githubusercontent.com/1165044/75646521-3eaeab00-5c8d-11ea-9c3c-765133c3abe2.png">
