### ISSUE TITLE
JSON text not parsed correctly - theme color hard to read

### ISSUE THREAD

**Issue by skottles** [coteditor/CotEditor#1040]
## Environment

- CotEditor: 3.8.11 (398)
- System: macOS Version 10.14.6 (Build 18G3020)
- Language: English

## Short Description

JSON text not parsed correctly - theme color hard to read

## Steps to Reproduce the Issue

1. find a json payload online - example: https://jsonapi.org/examples/
2. copy the payload
3. create new document in CotEditor
4. paste the payload
5. save the file with a .JSON file extension

## Expected Result

I am using the "Classic" theme. When the file is saved, there are 2 colors being used. Blue for Characters, and everything else using the RED "string" color. I would expect any character after the ":" to be a different color as all other JSON text editors do (example TextWrangler or Backets).

Screenshot Examples:
**CotEditor**
<img width="712" alt="json-example-coteditor" src="https://user-images.githubusercontent.com/4684178/75800087-e085d480-5d2d-11ea-8498-8a01d1b9217f.png">

**TextWrangler**
<img width="659" alt="json-example-textwrangler" src="https://user-images.githubusercontent.com/4684178/75800089-e085d480-5d2d-11ea-82ac-39aa9ad165a1.png">

**Brackets**
<img width="823" alt="json-example-brackets" src="https://user-images.githubusercontent.com/4684178/75800083-df54a780-5d2d-11ea-9a4a-ccf119eb224c.png">

**Comment by 1024jp** [comment]
Okay, this is not something wrong. They both are string.
But I understand it is easier to read if the keys and values are colorized differently.
Due to the current CotEditor's implementation of the syntax parsing, using separate colors for the same quoted scopes is actually a little bit challenging.
It's a kind of historical reason.
I'm not sure if I can parse properly, but I'll try.
