### ISSUE TITLE
[support] Chinese ANSI encoding and [request] Clipboard history

### ISSUE THREAD

**Issue by zwb124** [coteditor/CotEditor#1041]
hope add Clipboard history and ansi encoding。

**Comment by zwb124** [comment]
Mainly to open windows text documents will be garbled，thanks

**Comment by 1024jp** [comment]
Please create issues request by request and set a proper title for each.

Well, your requests are the following two, right?

1. Add user interface to select/check/edit the clipboard history.
2. Add the ansi encoding.


Answering your request:

#### 1. Clipboard
This is not a feature that a plain-text editor should implement.
Use clipboard utility apps straightforwardly, such as [Clipy](https://clipy-app.com), if you want.

#### 2. ANSI encoding

If you mean by the term ANSI as it used in the Microsoft culture, "Western (Windows Latin 1)" would be what you want.


And in term of another one:

> Mainly to open windows text documents will be garbled

I guess this is additional information for ANSI encoding, but I didn't get what you meant.
If I understand wrongly, could you describe it more in detail?

**Comment by zwb124** [comment]
I'm sorry, my English is average,just like the file,it is a create file in win10,it is Chinese,Open well with mac's own text editor.
[test.txt](https://github.com/coteditor/CotEditor/files/4335801/test.txt)

**Comment by 1024jp** [comment]
> I'm sorry, my English is average

No problem. I am also non-native.
I just needed to make the issue here clear.

Ok, ANSI.
Microsoft uses the term ANSI horribly in their own way.
This encoding, ANSI, does not point a single encoding but changes the actual character set depending on the environment (locale).
For simplified Chinese, "Simplified Chinese (Windows, DOS)", which you can find also in the CotEditor's encoding list, is the correspondent encoding to the Chinese ANSI in Windows.

**Comment by zwb124** [comment]
ohh, I understand,thanks very much

**Comment by 1024jp** [comment]
You are welcome 🙂
