### ISSUE TITLE
option for Location, Current Line and Column to start at zero

### ISSUE THREAD

**Issue by vassudanagunta** [coteditor/CotEditor#1052]
I'm doing parser development. Line and character offset indexing in nearly every data structure in nearly every programming language starts at zero.  I think it would be simple enough to add a tiny text field next to each checkbox for these on the Status bar settings?

Would be so helpful :)

**Comment by 1024jp** [comment]
There are various ways to count characters and every way has their own needs. Supporting all of them is, yes...,  a kind of nightmare 😨.

I understand your demand. Your request is one of them.
Actually, I have a plan to make the character (and line?) counting customizable. However, because I am currently working on other features that have a higher priority, I have no fixed schedule yet for this.
So please be patient. In the future, one day, it will be implemented.

**Comment by vassudanagunta** [comment]
Not a demand! A hope. I understand. I appreciate what you do. Thank you.

**Comment by 1024jp** [comment]
Hi, it’s been a while.

CotEditor has improved the character counting in the next minor update, CotEditor 4.4.0, which will be released this fall. It also will change the spec to count the location and column to start with zero (although the current line number is still 1-based because the line number itself starts with 1).
There will be no option to back to the current 0-based count. This is the default spec change as I also think it is more intuitive for non-programmers as well.
 
<img width="554" alt="Screen Shot 2022-09-04 at 15 26 22" src="https://user-images.githubusercontent.com/1165044/188300514-1e788304-e116-4f91-9481-d52575c8a784.png">

**Comment by vassudanagunta** [comment]
Perfect!
