### ISSUE TITLE
MATLAB syntax style and matrix transpose

### ISSUE THREAD

**Issue by SamSchott** [coteditor/CotEditor#1073]
MATLAB syntax uses opening and closing single quotes `'` for character arrays but a single quote `'` by itself for transposed matrices. Since CotEditor does not distinguish between those uses, large portions of a document after a transpose (until the next transpose) will be erroneously recognised as a character array and highlighted in blue.

It is tricky to distinguish the two uses cases, but Matlab itself of course does so - otherwise it could not interpret its own language. The Matlab IDE manages as well, despite being a real pain to use otherwise.

Would you consider supporting this?

**Comment by 1024jp** [comment]
I close this issue just because it's already reported at #697.
Due to the limitation of the current CotEditor's implementation to extract syntax highlighting, fixing this is hard (maybe impossible).

I know I need to re-design the entire syntax parsing algorithm, but actually, not yet planned due to my limited time resource. Sorry for that.
I'll consider again if there is a way to work around it.

**Comment by SamSchott** [comment]
Ahh, I did briefly search for related issues but overlooked this one. Thanks for the info.

Also, thank you for maintaining CotEditor. It is really great to have a light-weight text editor with syntax highlighting as an alternative to all the heavy IDEs!
