### ISSUE TITLE
[feature request] keep editor open

### ISSUE THREAD

**Issue by cvlmtg** [coteditor/CotEditor#1078]
Hi, would it be possible to make CotEditor remain open when all windows are closed? Thanks!

**Comment by 1024jp** [comment]
There is no way on CotEditor to toggle this behavior with the GUI, because this is the standard (and preferred) behavior for document-based applications in macOS.  
Because of this reason, CotEditor also does not implement it intentionally.

However, if you really want, you can disable it in CotEditor by running the following line in the Terminal.

`defaults write com.coteditor.CotEditor NSDisableAutomaticTermination -bool YES`

**Comment by cvlmtg** [comment]
Thanks, I really like to have it always open so I can drag and drop files on its icon when I need. having to run it again every time is a bit annoying.

**Comment by 1024jp** [comment]
The command overrides the CotEditor's default behavior. So, you don't need to run it every time.
