### ISSUE TITLE
Feature Request: More Applescript Capability

### ISSUE THREAD

**Issue by gregarios** [coteditor/CotEditor#1092]
Can you please update the Applescript capability in CotEditor to allow for recording scripts directly?

Also, more Applescript-able commands would be really useful:

- Smarten/Straighten Quotes
- Alphabetize/Sort Selection
- Smarten Dashes
- Set Background Color
- Set Selected Text Color

A few good examples for using each Applescript command would be awesome in the help section "CotEditor Scripting Guide --> About Scripting" (which is currently 404 in the app BTW)

A direct rich-text or HTML editing option would be nice too with capability for bold, italic, h[1-9], etc.

**Comment by 1024jp** [comment]
Hi, I've just added the following AppleScript commands to CotEditor 4.0.0, which will be released in this year when Big Sur is published:

- Smarten/Straighten Quotes
- Smarten Dashes

Regarding other commands you requested:

- Alphabetize/Sort Selection
    - We already have `sort lines` and `reverse lines` commands. Have you tried them?

- Set Selected Text Color
    - Currently, I don't prefer implementing it because it conflicts with syntax highlighting and hard to maintain without spoiling performance.
- Set Background Color
    - Pretty the same as the text color. I'm not keen to add AppleScript commands that style text. However, since I understand the needs (such as for pointing out errors, emphasizing specific terms, etc...), maybe I'll implement it in the future, at some time point. But not sure yet. I need to consider the implementation design and performance.


> A few good examples for using each Applescript command would be awesome in the help section "CotEditor Scripting Guide --> About Scripting" (which is currently 404 in the app BTW)

We have some sample scripts on https://github.com/coteditor/SampleScripts
Previously, these samples were bundled in CotEditor.app; however, due to the AppStore restriction, now we provide them separately.

> About Scripting (which is currently 404 in the app BTW)

This is a long-standing issue system-wide on macOS. I have no idea yet how to fix it. It works under most environments, but sometimes not.

**Comment by gregarios** [comment]
> Hi, I've just added the following AppleScript commands to CotEditor 4.0.0, which will be released in this year when Big Sur is published:
> 
>     * Smarten/Straighten Quotes
>     * Smarten Dashes

Thank you! This will help me complete my prepress script that normalizes author-submitted text for use in our publications.

**Comment by gregarios** [comment]
Uh oh... I just saw the System Requirements...   CotEditor 4 won't work on High Sierra?

**Comment by 1024jp** [comment]
> CotEditor 4 won't work on High Sierra?

Unfortunately, no.
CotEditor 4 aims mainly to support macOS Big Sur, and because the change in Big Sur is drastic, it is unrealistic for a private developer to support the new standards in Big Sur but simultaneously maintaining for previous systems. So, I needed to decide to change the system requirement. Sorry about that.

**Comment by gregarios** [comment]
Would it be possible to at least add the AppleScript smarten/straighten capability to the 3.x version so it is still available on earlier MacOS versions?

**Comment by 1024jp** [comment]
Hmm well, I'll consider. Because the release of Big Sur seems later than I thought.
Maybe I still have time to release another one for the 3.x series.

**Comment by gregarios** [comment]
> Hmm well, I'll consider. Because the release of Big Sur seems later than I thought.
> Maybe I still have time to release another one for the 3.x series.

It would be so _great_, as I work for a company that refuses to upgrade their Macs unless they die completely, and they are working with 2011 iMacs that can only be upgraded to High-Sierra or Mojave.
But, I work from home for them 1/2 of the time and have a 2017 loaded iMac with Catalina on it...  and I need to use your text editor (along with several other people) with my workflow text-prep script both at the office and at home. :-)

**Comment by 1024jp** [comment]
So, I've just released CotEditor 3.9.7 both on MAS and GitHub [with this feature and several other small changes](http://coteditor.com/releasenotes/3.9.7.en).

Note that, even after releasing CotEditor 4.0.0 on the MAS, you can always download previous versions from the [archive page](https://coteditor.com/archives) of the CotEditor's website.

**Comment by gregarios** [comment]
Thank you! :-)
