### ISSUE TITLE
Display error after replace some char

### ISSUE THREAD

**Issue by xlighting2017** [coteditor/CotEditor#1100]
CotEditor 3.9.5(433) Github Release + macOS 10.15.6

the space/tab character is disappeared after replace..

---
hard to describe in English, better see gif below:

![coteditor](https://user-images.githubusercontent.com/25970065/91290710-8a6a8900-e7c6-11ea-870e-27178ccc69ae.gif)

---
the original text is
`2p7kFhW3TTM	官网+ebay	3EN1BX	1kVodp`

after type the `,`   the space/char between `BX` and `1k`  is still there, but not displayed/shown in CotEditor

**Comment by 1024jp** [comment]
Thank you for the report.
However, I could not reproduce your issue under my environment.

Observing your GIF, I found the widths of the spaces between `M`-`官` and `X`-`1` are different.
Thus, I guess the space between `X`-`1` is not a SPACE character (U+0020) but a HORIZONTAL TABULATION (U+0009, namely a tab) or something.
If it is a tab character, this behavior can be correct because a tab character changes its width depending on the location. In addition, some proportional fonts also adjust the space width.

So, could you let me know the following information?
1. Your font setting in Preferences > Appearance > Font
2. The exact character between `BX` and `1k`. (You can check it by selecting the space and performing __Text__ > __Inspect Character__ in the menu.)

**Comment by xlighting2017** [comment]
hmmm, I see,  the line was copied from Google Sheet, which uses `TAB`

the font is  JetBrains Mono Regular 16

the Char is indeed HORIZONTAL TABULATION (U+0009) when I use **Text > Inspect Character**

I was not aware that the `TAB` can be "invisible"/change its width to 0 in this situation,
thanks for the explanation! 👍 


I can use "Preferences > Appearance > Show invisible" to make sure it displays :)
