### ISSUE TITLE
Feature Request: Smarten or Stupefy Quotes and Apostrophes

### ISSUE THREAD

**Issue by gregarios** [coteditor/CotEditor#1107]
I'm not sure this is the correct place for a request — forgive me if it isn't.

This is just a request for a feature that I find I really need...
A button to convert all quotes to correctly formatted curly (smart) quotes and apostrophes, and a button to straighten (stupefy) all quotes and apostrophes.
Please consider this for all people using CotEditor scripting to correct text as a pre-press tool.

**Comment by 1024jp** [comment]
CotEditor already has such a function in the contextual menu.

<img width="490" alt="Screen Shot 2020-09-23 at 14 18 29" src="https://user-images.githubusercontent.com/1165044/93969799-b5390480-fda7-11ea-8053-67af11f7c3b0.png">

Is that enough for you? Or do you need buttons (maybe in the toolbar?) as well?

Regarding scripting, I may mention the issue #1092.
Because this is a reasonable request, I already planned to implement it (sorry I didn't reply).
Currently, finishing-up the up-coming Big Sur support is the highest priority, and then, I'll implement new features, such as your request.

**Comment by gregarios** [comment]
> CotEditor already has such a function in the contextual menu.
> 
> <img alt="Screen Shot 2020-09-23 at 14 18 29" width="490" src="https://user-images.githubusercontent.com/1165044/93969799-b5390480-fda7-11ea-8053-67af11f7c3b0.png">
> 
> Is that enough for you? Or do you need buttons (maybe in the toolbar?) as well?

A button that would straighten and alternately smarten quotes on a document level would be awesome, also the ability to script that action too.

> Regarding scripting, I may mention the issue #1092.
> Because this is a reasonable request, I already planned to implement it (sorry I didn't reply).
Oh thank you!
> Currently, finishing-up the up-coming Big Sur support is the highest priority, and then, I'll implement new features, such as your request.
