### ISSUE TITLE
Mostly empty menubar after updating to 4.0

### ISSUE THREAD

**Issue by vordenken** [coteditor/CotEditor#1118]
Hello,

after updating to version 4.0 through the appstore, the top of this app is mostly empty. As far as I remember, there where a lot more things before.
Heres a screenshot:
<img width="600" alt="Bildschirmfoto 2020-11-11 um 14 24 03" src="https://user-images.githubusercontent.com/62395860/98816968-b8588480-2429-11eb-8831-bbd965bbc174.png">

Is this expected behavior? 

best regards,
vd

**Comment by gregarios** [comment]
Same with mine. My customized toolbar is empty.

**Comment by tenox7** [comment]
+1

**Comment by matzepf** [comment]
And I cannot add "Convert line endings" to the toolbar. This was the most important one for me. Why was it removed?

**Comment by 1024jp** [comment]
The toolbar item line-up was changed on CotEditor 4.0 to fit the new Big Sur style toolbar layout that has significantly narrower space than the previous system versions.
The largest change was that the encoding menu and line endings menu were moved from the toolbar to the status bar that is located at the bottom of the window. Thus they were removed from the toolbar.
So the remained items in the default toolbar are the syntax menu and the inspector button.

In addition, because the toolbar implementation was changed a lot on Big Sur, all toolbar item settings had to be reset. Please re-customize the toolbar if you added others before.

**Comment by 1024jp** [comment]
I close this issue.
If you have any issues potentially related to this one, please create a new issue.
