### ISSUE TITLE
Removing spaces at EoL when saving is unreliable

### ISSUE THREAD

**Issue by velotiger** [coteditor/CotEditor#1124]
## Environment

- CotEditor: 4.0.1 (455)
- System: macOS Version 11.0.1 (Build 20B50)
- Language: German

## Short Description

Removing spaces at EoL when saving is unreliable.

## Steps to Reproduce the Issue

Activate «remove spaces at EoL» and «include lines that contain only
spaces» in CoTEditor's settings (sorry, I do not know how you named
these items in the english localization – in german they are named
«Leerzeichen am Zeilenende automatisch entfernen» and «Nur aus
Leerzeichen bestehende Zeilen einschließen»).

* Load a file in the editor that contains spaces at EoL.
* Save the file.
* Sometimes the spaces at EoL are removed, sometimes they remain,
sometimes they are removed after a few seconds.

The more complex/longer the file, the less reliable is the removal
of the spaces at EoL. E.g. on Python code it almost never works, on
simple text files it works most of the time.

## Expected Result

Spaces at EoL are removed if the settings are active.

**Comment by 1024jp** [comment]
Thank you for the feedback and sorry for taking the time to pick up this issue.
First, I need to say this is in spec.
The timing to trim trailing spaces was changed on CotEditor 4.0.0, and the new behavior is the following:
1. Saving doesn't trigger the trimming.
2. The auto trimming is triggered only when the user doesn't modify the text for more than 5 seconds.
3. The trailing spaces remain if the cursor locates there.

The change was carried out to improve the application stability while saving. However, taking your comment into consideration, I changed this delay from 5 seconds to 3 seconds to ensure the spaces are trimmed before the autosaving because the autosaving delay is also set to 5 seconds. The change will be applied to the next CotEditor, namely 4.0.6, which will be released in late June.

Moreover, if you find any case that doesn't match the rules above, please let me know.
