### ISSUE TITLE
Opacity Setting No Longer Functioning in Full Screen in Big Sur

### ISSUE THREAD

**Issue by madalaus** [coteditor/CotEditor#1125]
## Environment

- CotEditor: 4.0.1 (455)
- System: macOS Version 11.0.1 (Build 20B29)
- Language: English

## Short Description

Opacity no longer working in Big Sur

## Steps to Reproduce the Issue

Set Opacity to any percentage
Verify you can view desktop picture with specified opacity setting
Maximize editor window (full screen)
Opacity no longer working

## Expected Result
Maximized editor window reveals desktop photo in full screen as before

**Comment by 1024jp** [comment]
This is by design. Because in the fullscreen mode in macOS, there is no desktop layer underneath the window but only the fullscreen-ed window. Therefore CotEditor just disables the editor transparency and make it fully opaque. I suppose this behavior is the same as before.

Therefore, there is technically no way to display your desktop picture by the fullscreen mode because the macOS's fullscreen is designed so.
