### ISSUE TITLE
Save on loss of focus

### ISSUE THREAD

**Issue by kour1er** [coteditor/CotEditor#1126]
[Feature request]
Would it be possible to add a setting so that whenever I switch from CotEditor to a different application, CotEditor automatically saves?

Usecase: Editing a script in CotEditor, switching to Terminal to run the edit I just made without needing to type Command+S every time.

I appreciate this is a minor edge case but I found the feature really handy in TextMate. Thanks for the consideration.

**Comment by velotiger** [comment]
I suppose «Settings → General → Automatic Versioning» (guessed translation from german) will serve the purpose. If it's activated, CotEditor almost instantly saves a file after altering just a single letter. Side effect/backdraw: You cannot edit without changing the file.

**Comment by kour1er** [comment]
That's a good compromise for sure - cheers!

**Comment by 1024jp** [comment]
Sorry for my late reply.
As velotiger pointed out, CotEditor has a autosaving system that relies on the macOS's Autosave and Version feature. Because it is a native behavior in macOS, I want to stick to it and not to add other minor options.

So, I just close this issue without adding the option you requested (but I think you may like the Autosave feature).
