### ISSUE TITLE
"show in finder" button in Inspector panel

### ISSUE THREAD

**Issue by sweetppro** [coteditor/CotEditor#1145]
A button to show the current working document in the Finder would be super nice

**Comment by 1024jp** [comment]
CotEditor doesn't have such a button in the inspector because in macOS, you can reveal the document in Finder by clicking the tiny document icon in the titlebar with the Command key. This is the standard behavior in document-based applications in Mac. So I have rejected this kind of requests.

<img width="370" alt="Screen Shot 2021-01-21 at 19 06 42" src="https://user-images.githubusercontent.com/1165044/105335838-e02f4a00-5c1b-11eb-98ae-78f899995659.png">
 
However, in macOS 11 Big Sur, it becomes regrettably harder to reach the document icon in titlebar. So it can be now good to add the button in the inspector, next to the full path. I'll consider.

**Comment by michelf** [comment]
Note that you don't need to command-click on the icon, you can also command-click the title.

**Comment by 1024jp** [comment]
This feature will be added to the next version (finally!).

<img width="270" alt="Screenshot 2024-05-10 at 22 53 49" src="https://github.com/coteditor/CotEditor/assets/1165044/68a549cd-deb0-4e2d-bc5f-df42653ac3d3">
