### ISSUE TITLE
Reflow / join selected contiguous lines - possible?

### ISSUE THREAD

**Issue by dajare** [coteditor/CotEditor#1151]
Is it possible to join + "flow" selected lines? This is a common text editor feature, but I just cannot find it in CotEditor. 

To illustrate graphically: (1) I have some lines I want to join, so I select them:

<img width="555" alt="_join-00" src="https://user-images.githubusercontent.com/40625/107813667-a8be4400-6d68-11eb-9363-4ad99ad84bc2.png">

(2) Now, just with `CTRL-J` I can get this result:

<img width="555" alt="_join-0" src="https://user-images.githubusercontent.com/40625/107813715-b96eba00-6d68-11eb-9a1e-b13db553f4f0.png">

I feel like this ought to be available in CotEditor, but (as I say), I just can't find it. If it is, indeed, **not** available, please consider this a feature request! **Or** is it possible to get this functionality with [shell script or applescript][ss]?? Thanks!

**Platform**: Mojave = MacOS 10.14.6; CotEditor Version 3.9.7 (437) (I'm stuck on Mojave because I have essential software that I'm afraid requires 32bit libraries).

[ss]: https://github.com/coteditor/SampleScripts

**Comment by vassudanagunta** [comment]
I agree, but `Join Lines` and `Reflow Lines` **should be separate commands**.

In most of the editors that I've used, the `Join Lines` command (⌘J) joins the current line (cursor) with the next line. You can press ⌘J again to keep joining more lines.  I can't remember if my other editors do it, but joining multiple lines in one action if the selection spans more lines makes sense.  `Join Lines` would sit next to `Duplicate Line` and `Delete Line` in the menu.

The two questions for `Reflow Lines` would:

1. Does it reflow the entire doc if nothing is highlighted?
2. Is it a ***smart reflow***?  That is, does it respect the language syntax being reflowed?

**Comment by 1024jp** [comment]
Sorry for my late reply.

I added the "Join Lines" command to the next CotEditor 4.7.1 😉. The default shortcut is Command+Shift+J, but you can customize it in the Key Bindings settings.

As for Reflow Lines, it is not easy to define the behavior as @vassudanagunta pointed out.
So, let me have some more time to decide.

> Does it reflow the entire doc if nothing is highlighted?

I suppose the answer for CotEditor is "yes."
Most text modification commands in CotEditor perform only for selection if something is selected; otherwise, the entire text.

> Is it a smart reflow? That is, does it respect the language syntax being reflowed?

If CotEditor implements the reflow command, it should be aware of (natural) language.

**Comment by 1024jp** [comment]
I considered the Reflow command but concluded not to implement it because it is too complicated to take all possible language rules into account. The APIs provided by Apple are not enough to handle this kind of thing.
I don't want to implement a command for natural languages that supports only specific major languages, such as English.
If a user wants to have the command target a specific language, I recommend writing your script.
