### ISSUE TITLE
CotEditor 4.0.4 still doesn't terminate when all windows are closed

### ISSUE THREAD

**Issue by sohate** [coteditor/CotEditor#1183]
Subj. Changelog says that the problem was fixed, but CotEditor still active after all windows are closed.

**Comment by 1024jp** [comment]
Uwee, that's true. Thank you for reporting that.

cf. https://developer.apple.com/forums/thread/92622
The method `applicationShouldTerminateAfterLastWindowClosed` (suggested in the discussion above) cannot be easily replaced with `NSSupportsAutomaticTermination` because the timing to terminate is different. I need to find another solution.
Let me have time to think.

**Comment by 1024jp** [comment]
cf. https://developer.apple.com/library/archive/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW27

**Comment by sohate** [comment]
I don't know if this information will be useful, but IINA closes the application automatically if all windows are closed. It's open source.

**Comment by 1024jp** [comment]
@sohate Thanks for the information. I quickly looked the source code of IINA and found they use `applicationShouldTerminateAfterLastWindowClosed` method that I don't prefer to use.

Well, I found another way to activate the system's automatic termination that works. I now feel like this (the way in CotEditor 4.0.4 doesn't work) is a kind of a bug by Apple side. Not sure.

Anyway, this bug will be fixed in the next version (at last.) Please be patient for the next release.
