### ISSUE TITLE
Syntax Highlighting: Javascript One-line-Comments

### ISSUE THREAD

**Issue by chrisgrieser** [coteditor/CotEditor#1187]
While highlighting for multiline comments `/* comment */` works fine, one-line comments `// comment` do not work properly. See here:
![Screen Shot 2021-06-12 at 22 20 36](https://user-images.githubusercontent.com/73286100/121788301-85978a00-cbcc-11eb-85ac-b4090af55273.png)

**Comment by 1024jp** [comment]
Thank you for the report.

For the present, I've simply reverted the syntax highlight definition for JavaScript to resolve this issue. That is, the highlight issue on regex comes back instead of fixing this inline comment highlight issue.
I just close this issue and will discuss the further points about JavaScript highlight problems in the original #1185.
