### ISSUE TITLE
CotEditor opens file in new window instead of tab when minimized

### ISSUE THREAD

**Issue by dermu** [coteditor/CotEditor#1195]
## Environment

- CotEditor: 4.0.5 (463)
- System: macOS Version 11.4 (Build 20F71)
- Language: English

## Short Description

When CotEditor is running but window is minimized, new files are opened in a new window instead of new tab, even though the option "Prefer tabs" is set to "Always".

## Steps to Reproduce the Issue

1. Start CotEditor, ensure "Prefer tabs" is set to "Always" in the preferences.
2. Open any text file and minimize the CotEditor window (using the yellow dot)
3. Go to Finder and open any text file using double click or open-with CotEditor option

Observed behavior: CotEditor opens the file in a new window, resulting in mutliple CotEditor windows. This is not expected because "Prefer Tabs - Always" was selected.

## Expected Result

CotEditor shall open the file in a new tab of the existing CotEditor window and bring it to foreground (un-minimize).

**Comment by 1024jp** [comment]
This is regrettably by design and the standard behavior for macOS apps when the user prefers tabs. That is, there is almost the same setting in macOS'es system preferences > General. When you set it as "always" and try the same thing in another Cocoa app, such as Pages, it behaves the same manner as CotEditor.

<img width="780" alt="Screen Shot 2021-07-15 at 22 20 23" src="https://user-images.githubusercontent.com/1165044/125795005-5ede7985-1e27-4cf3-82c5-f764b8e57bdc.png">

Because the goal of CotEditor is to be the most native text editor on macOS, it also should behave so.

**Comment by dermu** [comment]
Hi 1024jp, thanks for the explanation. Actually, behavior is not consistent in macOS apps: Safari opens a file in a new tab even when minimized, if "prefer tabs" is selected in system preferences. So perhaps CotEditor can offer the same behavior and give the user the choice?
In any case, I want to say thank you for the great app you are developing! I'm using it every day.

**Comment by linuslau** [comment]
echo "Actually, behavior is not consistent in macOS apps: Safari opens a file in a new tab even when minimized, if "prefer tabs" is selected in system preferences. So perhaps CotEditor can offer the same behavior and give the user the choice?"

Previously opened tabs disappear when open a new while it is minimized does not makes sense as a text editor, look at notepad--,sublime text, vscode etc. almost all the text programs behaves the same.

**Comment by 1024jp** [comment]
@linuslau  Although Safari is developed by Apple, its window tabs don’t use Apple’s AppKit window tab API, nor does Safari adopt a document-based application architecture. As a result, its behavior naturally differs.
Applications such as TextEdit and Pages use the same mechanism as CotEditor.
Because this behavior isn’t controlled by CotEditor, please submit your request to Apple.

> while it is minimized does not makes sense as a text editor, look at notepad--,sublime text, vscode etc.

They don't use the native window tab APIs.

**Comment by 1024jp** [comment]
@cleesmith Then, you are welcome to use other editors.
