### ISSUE TITLE
Unable to Check For Updates on CotEditor 4.0.7

### ISSUE THREAD

**Issue by wenbingzhang** [coteditor/CotEditor#1208]
### Description

Unable to Check For Updates

The update checker failed to start correctly. You should contact the app developer to report this issue and verify that you have the latest version.

### To Reproduce

1、exit CotEditor
2、open CotEditor

### CotEditor version

4.0.7 (467)

### macOS version

macos 11.5.2

**Comment by 1024jp** [comment]
Thank you for the report. I confirmed the issue. Let me have time to fix it.

**Comment by 1024jp** [comment]
I've just released CotEditor 4.0.7-1 fixing this issue in haste. Sorry, but therefore, please update to it manually this time.

Also for others: If you use CotEditor downloaded not from the MAS but from our site and have already update to CotEditor 4.0.7, please download and replace it with CotEditor 4.0.7 manually. 
Because this issue is related only to the non-AppVersion, we don't release 4.0.7 on the MAS, and 4.0.7 is the latest.

https://github.com/coteditor/CotEditor/releases/tag/4.0.7-1
