### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by dmuratov-als** [coteditor/CotEditor#1212]
### Description

Memory leaks

### To Reproduce

1. Open any plain text document. The bigger the document, the quicker the amount of memory consumed. However, the bug is reproducible even with the smallest files (KB's), it just takes more time). Let's take, for example, a 40 MB file.
2. Close the file not quitting the app and open it again 10 times in a row.
3. The amount of memory consumed is about 1 GB, and is not going down.

### Expected behavior

Reasonable amount of memory consumed, purging upon closing a document.

### CotEditor version

4.0.7 (467)

### macOS version

macOS Version 11.5.2 (Build 20G95), M1

**Comment by 1024jp** [comment]
Thank you for the report.

I tested under similar environments to you:

- CotEditor 4.0.7, and 4.0.8-alpha (the latest dev ver.)
- macOS 11.5.1 (20G80), and 11.6 (20G165)
- MacBook Pro M1, late 2020
- test files: XML file with ~10 MB, ~100 MB, and ~500 MB

However, I could not so far reproduce the issue.
In addition, the memory leak detection feature on Xcode doesn’t capture such a large leak.
Maybe, it has some more specific conditions to reproduce.

Do you have any additional conditions for this?
I am interested in what happens if you disable the syntax highlighting and the contents count.
- Disabling syntax highlighting: Go to Preferences -> Format pane and uncheck "Enable syntax highlighting".
- Disabling contents count: Hide both the status bar and the document inspector in the side panel.


The memory usage opening and closing a 124MB file repeatedly:
<img width="860" alt="Screen Shot 2021-09-18 at 15 38 33" src="https://user-images.githubusercontent.com/1165044/133879039-bc312a70-7c74-4fb4-a01f-7981d763ad05.png">

**Comment by dmuratov-als** [comment]
There are no additional conditions I consciously know of. Here is how the workflow looks like with a ~40 MB text file and the syntax highlighting and the contents count disabled.
![cot](https://user-images.githubusercontent.com/4169988/133881194-86da104d-37f4-4e39-8142-2ba0e9eb7f6f.gif)

**Comment by 1024jp** [comment]
Thank you for answering my questions. It's helpful.
I'll look into it further.

**Comment by 1024jp** [comment]
Aha! I found the key. When I disabled the Autosaving (in Preferences > General pane), it reproduces. I'll dig the code around it tomorrow.

**Comment by 1024jp** [comment]
Ok, now the issue has been fixed.
I'll submit the new version to the MAS within a day.
I appreciate your help.

**Comment by 1024jp** [comment]
CotEditor 4.0.8 released.

**Comment by dmuratov-als** [comment]
Thank you!
