### ISSUE TITLE
如何进行多行操作？ /  How to operate multilines?

### ISSUE THREAD

**Issue by whfragrant** [coteditor/CotEditor#1221]
问题：
1，如何在多行操作的时候，将多行光标快速移动到尾部，现在想移动到尾部，需要一行一行选下去，有没有快捷方式，直接选到最后一行的头部如图：
![image](https://user-images.githubusercontent.com/26105622/139388658-18f64a21-a4bc-4a88-88f1-8efe9e279e27.png)

2，如何快速调转到文本的首行和尾行？

**Comment by gingerbeardman** [comment]
1) i don't think is possible, you need to do a new multi line selection. you can move the multi line using alt+cursor up/down but not extend it.
2) use Home and End keys

**Comment by 1024jp** [comment]
Sorry for my late, but because I don't speak Chinese, please write issues in English (or in Japanese) next time.

The following is the machine translated version of the original post:

> question:
> 1. How to quickly move the multi-line cursor to the end of the multi-line operation. Now, if you want to move to the end, you need to select it line by line. Is there a shortcut, directly select the head of the last line as shown in the figure:
> 2. How to quickly switch to the first and last lines of the text?

Answering those questions:

> 1. How to quickly move the multi-line cursor to the end of the multi-line operation. Now, if you want to move to the end, you need to select it line by line. Is there a shortcut, directly select the head of the last line as shown in the figure:

Do you mean to add the insertion point at the beginning of the last line to the existing insertion points? If so, it is impossible. Only the way to add an insertion point by keyboard shortcut is add an insertion point just above/below the existing insertion points by pressing the Control-Shift-↑/↓ keys but not for the last line.


> 2. How to quickly switch to the first and last lines of the text?

In addition to the Home/End keys @gingerbeardman suggested above, you can also use the Command-↑/↓.

You can see the document how CotEditor handles multiple insertion points in the Help.
 
![Screen Shot 2022-07-06 at 20 34 08](https://user-images.githubusercontent.com/1165044/177541151-9c64e77e-e15f-4c11-b626-bb39623966fc.png)
