### ISSUE TITLE
CotEditor takes too much time rendering a xml file of 8MB size

### ISSUE THREAD

**Issue by water137780117** [coteditor/CotEditor#1265]
### Description

CotEditor takes too much time coloring a 8MB xml file, while TextMate takes little time.
<img width="420" alt="coloring" src="https://user-images.githubusercontent.com/16634745/157489562-cd9e9c70-fa42-4d05-b655-95ad7c0de083.png">
 

### To Reproduce

1. download the file https://share.weiyun.com/4SoMDz5g
2. open it with CotEditor
3. open it with TextMate as comparison.

### Expected behavior

1. Processing the file faster in Coteditor.

### CotEditor version

4.1.3 (483)

### macOS version

12.2.1

### Additional context

The app is downloaded from Mac App Store, and my device is a MacBookPro with Apple Silicon (M1 MAX).

**Comment by 1024jp** [comment]
Thank you for the report.
However, I could not find how to get the sample file you attached without registration.
Could you upload it somewhere else?

Answering your report in general before looking into the test file, I'm fully aware of the issue for a long time that the syntax coloring sometimes on CotEditor takes unbearably long, especially in the latter part of the process with the rainbow cursor. This is caused by the implementation of Apple's TextKit framework on that CotEditor relies. There is no way for the 3rd party developers to shorten this process. I'll review the current implentation again and try adding another measure to the next version. But, unfortunatelly, it may not be able to shorten the time drastically unless I change the CotEditor-side implementation for syntax highlight completely.
Well, I'll try my best.

**Comment by water137780117** [comment]
> Thank you for the report. However, I could not find how to get the sample file you attached without registration. Could you upload it somewhere else?
> 
> Answering your report in general before looking into the test file, I'm fully aware of the issue for a long time that the syntax coloring sometimes on CotEditor takes unbearably long, especially in the latter part of the process with the rainbow cursor. This is caused by the implementation of Apple's TextKit framework on that CotEditor relies. There is no way for the 3rd party developers to shorten this process. I'll review the current implentation again and try adding another measure to the next version. But, unfortunatelly, it may not be able to shorten the time drastically unless I change the CotEditor-side implementation for syntax highlight completely. Well, I'll try my best.

[test.zip](https://github.com/coteditor/CotEditor/files/8237265/test.zip)
Thanks for your reply. The attachment is the file for testing. According to my test, TextMate also takes long time coloring the whole file, but the file can be operated at the mean time of coloring. In CotEditor, the file can only be operated after fully colored. Maybe this a way to improve the operating experience. Thank you very much for producing such a wonderful editor.

**Comment by 1024jp** [comment]
Hi, today, I finally found the solution to this long-standing issue! I'm now implementing it and on the next minor update, CotEditor 4.3.0, the time to highlight documents will reduce drastically and almost no rainbow cursor will appear.
According to trials on my environment, the current version takes more than 2 minutes to apply the colors (the process requiring the rainbow cursor) to an appx. 7MB document, but in the next version, it will be done in 1 second. The time doesn't include the parsing time; so it still takes time to highlight but the total time is definitely reduced significantly.
