### ISSUE TITLE
Print Dialog Option - Print Selection

### ISSUE THREAD

**Issue by RickDaniel** [coteditor/CotEditor#1269]
It would be helpful to have an option in the print dialog to directly print only selected text.

The section can be copied to another buffer or app and then printed, but it would be nice to eliminate that step.

**Comment by 1024jp** [comment]
I close this ticket just because the request already exists #1075.

Although it's in my to do list and even I'm already working on it, the implementation is pending because it was more complexed than I thought (First I need to determine the specifications such as what if users has multiple selections in a single line, and so on).

Well, I want to ship it pretty soon just after finishing all the tasks I currently working on. So maybe in this year?

**Comment by RickDaniel** [comment]
Sorry.  I did search for it and must have missed it.  Thanks.

**Comment by 1024jp** [comment]
@RickDaniel No problem. Triaging issues is also a task of the maintainer.

In addition, now I have an outlook on the implementation of this feature to the next minor update, CotEditor 4.2.0, that will be released in this early summer 😉.
