### ISSUE TITLE
Incremental Search

### ISSUE THREAD

**Issue by nvictor** [coteditor/CotEditor#1282]
**Is your feature request related to a problem? Please describe.**
I started using CotEditor and found that it lacked an incremental search feature. Incremental search is a great time saving feature of most text editors. It would be nice to have.

Also the groundwork is already done through `Find...`, `Find Next`, and `Find Previous`. Just need to bring all that together.

**Describe the solution you'd like**
Incremental search could shown above the status bar area. See how TextMate does it in the attached screen shot. TextMate uses the shortcut `^S` to trigger the feature.

**Describe alternatives you've considered**
The `Find & Replace` window is not incremental and it takes the focus away from the main window. It also makes you click on buttons `Next` and `Previous`. TextMate uses `Tab` to jump to next match. And `^Tab` to jump to previous match.

I also tried the `Use Selection for Find` and `^G`. But it's not incremental.

**Additional context**
![incremental_search](https://user-images.githubusercontent.com/76629/163197834-b2a20a80-14ea-49cc-8d30-2d18784ef0f2.png)

**Comment by 1024jp** [comment]
Hi, thank you for the feedback. I've just finished implementing the incremental search to CotEditor.

In my approach, the Find panel is used instead of adding a new find bar. When the user types letters in the find field in the Find panel, the incremental search automatically performs in the frontmost document, just like Pages.app by Apple does.

This change will be shipped with CotEditor 4.3.0, which will be in late June or early July.

**Comment by nvictor** [comment]
Thanks so much!!
