### ISSUE TITLE
font size not honored in the search or find all window

### ISSUE THREAD

**Issue by vvnrkvanapalli** [coteditor/CotEditor#1294]
### Description

Set the font size to 18.. font style can be anything
perform string search and click on find all.. A second window will open. 
Original font size is not honored. Some small font size appear sin search window

### To Reproduce

Set the font size to 18.. font style can be anything
perform string search and click on find all.. A second window will open. 
Original font size is not honored. Some small font size appear sin search window

### Expected behavior

font size should be honored across all the windows

### CotEditor version

4.1

### macOS version

Monterey 12.3.1

**Comment by 1024jp** [comment]
The current behavior is by design and there is no plan to change it.

**Comment by 1024jp** [comment]
I currently still don't have the plan to sync the font size in the find result and the document editor because the function is different between those two views.

However, taking your request, I added the feature to customize the font size of the find result view, just like I did in the Outline pane (ref. #946) in the upcoming CotEditor 4.2.3.
From this version, you can change the font size of the find result by pressing `Command`-`Plus sign` (+), -`Minus sign` (-), or -`0` while focusing on the result table (just click somewhere in the result table before performing the shortcut). When once changed the font size, the preference will be stored and used in future searches.
