### ISSUE TITLE
Automatic indentation at line breaks during selection

### ISSUE THREAD

**Issue by hazi** [coteditor/CotEditor#1308]
**Is your feature request related to a problem? Please describe.**
I often break lines with a selection in order to delete the string and break the line at the same time.
I am having trouble generating lines that are not indented when doing so.

![May-20-2022 23-03-00](https://user-images.githubusercontent.com/5656927/169545479-bb028b16-ff18-426b-8671-066a44923974.gif)

**Describe the solution you'd like**
I would like the auto indentation to be maintained even if a new line is inserted during selection.

**Comment by 1024jp** [comment]
This behavior is actually by design. CotEditor inserts indentation only when inserting a newline without other selection or modification.
However, this is just because historically so designed.

Honestly, I also feel it's more intuitive to insert indentation when replacing the selection with a newline too.
What do you think?
I now think it better to change the current behavior.

**Comment by hazi** [comment]
I have not seen this behavior in other editors except when auto-indent is turned off, and I think it is appropriate to turn off auto-indent if that is what you want.

I don't know the historical background so I can't speak to that point, but I am of course in favor of this change.

**Comment by 1024jp** [comment]
Thank you for the reply. Yes, then, let's implement it!
