### ISSUE TITLE
Pref for Jump to Beginning of Line Behaviour

### ISSUE THREAD

**Issue by Frizlab** [coteditor/CotEditor#1318]
**Is your feature request related to a problem? Please describe.**
I have a workflow to move lines:
- `cmd-left` to go to beginning of line;
- `shift-bottom` to select whole line;
- `cmd-x` to cut the line;
- put cursor on line below where I want the line I cut;
- `cmd-left` to go to beginning of line;
- `cmd-v` to paste.

Doing this in CotEditor does not work well if the line starts w/ a space as the cmd-left shortcut goes to beginning of _text_ instead of beginning of line.

**Describe the solution you'd like**
I’d love at least an option to change the behaviour of the `cmd-left arrow` shortcut (and `cmd-shift-left` and `cmd-delete` too, of course).

**Describe alternatives you've considered**
I guess I could use `ctrl-a`, but my fingers do not know this. Also this does not solve the `cmd-delete` issue.

**Additional context**
Not much more to say, except thanks for the app!

**Comment by hbmartin** [comment]
+1 to this, it's my biggest frustration right now and is different from most editors

**Comment by 1024jp** [comment]
Sorry for my late response.

The current implementation of `⌘←` adheres to the behavior of Xcode, the IDE by Apple.
While it may not be universally preferred, I’d like to maintain the existing design.
As you mentioned, you can use `^A` to accomplish your desired action.

> but my fingers do not know this.

I should implement a way to customize the shortcut keys for these key bindings one day.
However, it will take time, and there are many other higher priority features that need to be implemented first.
Sorry, but please let me have time.

**Comment by 1024jp** [comment]
similar request: #1674

**Comment by dimitrik-fr** [comment]
A simple "workaround" should work : start your "workflow" by involving "cmd-left" twice ! -- if there is a text in the line, the second "cmd-left" will go to the real beginning of the line, and if there is no text -- cursor will remain on the beginning of the line, and it'll just work.

NOTE : many editors are following the same logic -- "cmd-left" is going on the beginning of the text of the given line, and second press on "cmd-left" is the jumping to the line beginning, and this has its own logic, since you're more often working with text itself rather with lines beginning.
