### ISSUE TITLE
Require some feature enchancement

### ISSUE THREAD

**Issue by Tairraos** [coteditor/CotEditor#1329]
I'd like to introduce 3 useful feature that IntelliJ IDEA / vscode / visual studeo already have.
I think CotEditor implemenet this will become compatible to more user's habit.

- If I selected nothing, just put cursor at somewhere, Cmd-X should CUT whole line into clipboard.
- If I selected something, and press Cmd-F, the selected content will auto fill in "find box".
- If I press Home/End key, cursor will go to head of line and tail of line.

Thanks for you created this good app.

**Comment by 1024jp** [comment]
Thank you for your feedback, but first of all, please create issues per request and use the template for each feature request.


> - If I selected nothing, just put cursor at somewhere, Cmd-X should CUT whole line into clipboard.

No. This is not proper behavior in macOS.
Such a standard command, Cut, should not change its behavior in an individual application.

> - If I selected something, and press Cmd-F, the selected content will auto fill in "find box".

Also no, due to the same reason above.
Instead, in the macOS world, Command-E is used to use selection for the find string.

> - If I press Home/End key, cursor will go to head of line and tail of line.

Because the current behavior of the Home/End keys is also the standard behavior in macOS, I'd not change the default behavior.
However, I suppose it worse if users can customize key bindings. So, I'll implement a more flexible key binding feature in the future.

So, I'd say the first two requests should be rejected.
In contrast, the last one has room for consideration.

**Comment by Tairraos** [comment]
Gotcha, thanks.
