### ISSUE TITLE
Add XAML to extensions in XML syntax highlighting

### ISSUE THREAD

**Issue by deseven** [coteditor/CotEditor#1335]
I think it makes sense to add [XAML](https://en.wikipedia.org/wiki/Extensible_Application_Markup_Language) as an extension for XML syntax highlighting in the default configuration.

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/1761803/180211762-f8bdd263-6905-4725-97af-02fb3b0f4f6e.png">

**Comment by 1024jp** [comment]
Do you have any specific issue with XML syntax highlighting doesn't have the definition of XAML extension?
Because the XML syntax style has a special rule that detects automatically when the document has an XML declaration at the first line. I suppose it's already enough.

**Comment by deseven** [comment]
Yes, because the autodetection didn't work for me. XAML is based on XML and syntax highlighting works fine (as you can see on the screenshot above), but the declaration can be different.

**Comment by 1024jp** [comment]
Aha, I see. It omits XML declaration. Thank you for the reply. Let me think.

**Comment by 1024jp** [comment]
I have been on hold for a long time but have come to a conclusion.
Since CotEditor currently has a policy of not adding too many miscellaneous extensions to the XML syntax settings, and since I suppose there are not many users of XAML in CotEditor users, I decided no to bundle it as a default.

CotEditor's syntax is customizable, so please customize it individually.
