### ISSUE TITLE
Line number margin

### ISSUE THREAD

**Issue by Mateus109** [coteditor/CotEditor#1337]
It would be nice if there was the option to have line numbers within their own margin, that was either a different colour to the main document and/or with a vertical line.  For example:

![image](https://user-images.githubusercontent.com/11629946/181215612-2d998f6a-30b0-4109-b1e2-c388c357a0bf.png)

**Comment by 1024jp** [comment]
I considered for more than a year whether I should add this option, but because I've received requests multiple times I decided to add it to the next minor update, CotEditor 4.4.0, which will be released this fall.

In my implementation, the option draws a separator between the line number view and the editor but does not change the background color.

<img width="760" alt="Screen Shot 2022-07-30 at 23 00 56" src="https://user-images.githubusercontent.com/1165044/181917798-7785be4d-51b7-499a-b45d-35f8f6712df7.png">
