### ISSUE TITLE
"查找所选内容"这一功能并没有弹出搜索框

### ISSUE THREAD

**Issue by chaofan2685** [coteditor/CotEditor#1370]
### Description

"查找所选内容"这一功能并没有弹出搜索框，甚至没有任何动静，仅仅是将所选内容设为了查找对象，如果此时再进行其他的查找操作，则可以正常的进行，比如“查找下一个”，的确会选中下一个目标文本，我不明白这算是BUG还是就是这样的逻辑

### CotEditor version

版本4.3.5 (529)

### macOS version

macOS Monterey 12.6

**Comment by 1024jp** [comment]
Because I don't speak Chinese, I answer in English to the machine-translated post.

Shot answer:
This is the expected behavior.

Long answer:
1. The command labeled "查找所选内容" is named "Use Selection for Find" in English. This command is one of the standard commands in macOS. That is, you can find it in so many applications including ones provided by Apple, such as TextEdit.app. The behavior is the same, just set the selected text to the find text.
2. Regarding the localization of this command in simplified Chinese, "查找所选内容," I suppose this is also standard localization in macOS. Other apps also translate it to "查找所选内容".

So, to keep consistency, CotEditor continues using this label for the command.
