### ISSUE TITLE
Command to surround lines with tags

### ISSUE THREAD

**Issue by Tekl** [coteditor/CotEditor#1380]
**Is your feature request related to a problem? Please describe.**
It would like to add a prefix and suffix to every line in the selection. So this …

```
line1
line2
line3
```

… can become this:

```
<li>line1</li>
<li>line2</li>
<li>line3</li>
```

**Describe the solution you'd like**
Add this command to CotEditor: "Surround Selection With > Custom for every line… ⇧⌥⌘L".

**Describe alternatives you've considered**
Add the option "Every line in selection" to the existing Surround-With-dialog (⇧⌘L).

**Comment by 1024jp** [comment]
For that, I recommend to use the multi cursor editing feature rather than adding a new command.
Find the detail in "Edit multiple points in CotEditor" page in the bundled help.
(You can access to it by typing the page title in the help field in the menu.)

https://user-images.githubusercontent.com/1165044/206062641-0f3a1d20-427d-4ecb-aee3-7856940b35f3.mov

**Comment by Tekl** [comment]
Thanks for the tip with multi cursor editing. It's not very helpful for HTML tags, so I wrote an AppleScript for my needs. It can surround lines with tags, create Markdown lists and headings. If you use a HTML tag with attributes, the script will remove them for the closing tag.

https://gist.github.com/Tekl/54ef3a305346e2a5557bee3fb51c122c
