### ISSUE TITLE
Minimal style titlebar on macOS

### ISSUE THREAD

**Issue by p1x44r** [coteditor/CotEditor#1387]
**Is your feature request related to a problem? Please describe.**
This is only an esthetics issue. You can theme the rest of the app all you want, but that thick brown the title-bar will standout in most cases.

**Describe the solution you'd like**
Shrink/hide/style (not entirely sure how it's accomplished) the title-bar entirely (i. e. minimal style like iTerm2, Typora or many other apps use.

Here's CotEditor with iTerms2 and Typora for comparison. 

<img width="1800" alt="canvas" src="https://user-images.githubusercontent.com/1068500/197323476-a4572ad9-6d9e-4579-b5fd-4eddaebfa6c0.png">
[](url)

Thank you!

This is a superb text editor I chose over all the rest easily due to its performance, flexibility and features.

**Comment by 1024jp** [comment]
I suppose this is by design.
The titlebar color should have influence from the desktop picture.
Titlebars of the Finder may behave in the same manner.

FYI, You can turn off the titlebar tinting, in the System Settings (or the System Preferences in Monterey) by turning off the "Allow wallpaper tinting in windows" option.

<img width="827" alt="Screenshot 2023-02-19 at 9 36 47" src="https://user-images.githubusercontent.com/1165044/219937810-792d813c-9ad7-4be8-b3b8-d4b6f997c66e.png">


If your titlebars of the Finder behave differently from the ones in CotEditor, let me know.
