### ISSUE TITLE
Customizing Touch Bar Issues

### ISSUE THREAD

**Issue by hnlkaitan** [coteditor/CotEditor#1390]
## Environment

- CotEditor: 4.4.0 (540)
- System: macOS Version 13.0 (Build 22A380)
- Language: English

## Short Description

Trying to customize the Touch Bar is a nightmare!

Icons seem to not respond to being placed anywhere on the right half of the Touch Bar, nor the left-most portion of the Touch Bar.

Furthermore, the Default Set provides some Flexible Spaces (at least it appears to), yet none are available in the editor? The regular Space takes up over half of the available space.

Sometimes, the cursor seems to jump around all over the place (therefore making it impossible to select certain items).

## Steps to Reproduce the Issue

1. Click on View → Customize Touch Bar.
2. Attempt to move icons on the right side of the Touch Bar.
3. Attempt to move certain icons to the left-most side of the Touch Bar.

## Expected Result

Being able to put any icon in any position, have smooth movement around the Touch Bar when using the trackpad.

**Comment by 1024jp** [comment]
> Icons seem to not respond to being placed anywhere on the right half of the Touch Bar

Apple provides only room for the lest side to individual applications.
The right side is for the macOS system and the application doesn't have the right to customize there.

> , nor the left-most portion of the Touch Bar.

You can put items in the leftmost position.

> Furthermore, the Default Set provides some Flexible Spaces (at least it appears to), yet none are available in the editor? The regular Space takes up over half of the available space.

There is the (flexible) Space item for customization at the last position in the Touch Bar customization field.

Because your requests here are the specification of the Touch Bar, there is no room to do on a 3rd party application side. I close the issue.
