### ISSUE TITLE
Option to disable auto-search due to lags on large documents

### ISSUE THREAD

**Issue by NorDogroth** [coteditor/CotEditor#1447]
**Is your feature request related to a problem? Please describe.**
Sometimes when you type text in the search box, it starts searching after typing the first or second letter, which causes the program to lag for a long time on large documents.

**Describe the solution you'd like**
I need an option to disable search while typing.

**Describe alternatives you've considered**
Do not start auto-search after only a few letters on large documents.

**Additional context**
## Environment 
- CotEditor: 4.4.5 (550)
- System: macOS Version 12.5.1 (Build 21G83)
- Language: German

**Comment by dimitrik-fr** [comment]
+1

"generally" in other Editors it's solved by config option "search for complete since N letters only" (where N is configurable) or by having an option to use <Tab> at the end of the word to manually involve auto-complete suggestions. 

currently I should fully disable complete suggestions in CotEditor as it quickly becomes very annoying to get a long list of suggestions for an every second letter you're typing in any new word..

**Comment by 1024jp** [comment]
@NorDogroth Thank you for the feedback. I'll see the source code to find a room for optimization on the incremental search. I'd like to ask you to be my reference, how large (number of characters of file size) was your document that faced the issue.

> I need an option to disable search while typing.

You already have the option. Disable the "Search incrementally" option.

<img width="710" alt="Screenshot 2023-03-08 at 11 30 29" src="https://user-images.githubusercontent.com/1165044/223604412-996c66eb-6673-48f7-8b10-cbd814ad45ee.png">


@dimitrik-fr You seems to talk about another thing. The reporter is talking about the incremental search and your issue is about auto-completion. Please create another issue if you have a suggestion for the completion feature.

**Comment by dimitrik-fr** [comment]
@1024jp -- you're right ! sorry for confusion, will file a new feature request, np ! ;-))

**Comment by 1024jp** [comment]
@NorDogroth 

> I'll see the source code to find a room for optimization on the incremental search.

I've reviewed the source around the incremental search but felt there is currently no room to optimize, unfortunately...
So, please use the option to disable incremental search on large documents.
