### ISSUE TITLE
Improve auto-completion

### ISSUE THREAD

**Issue by dimitrik-fr** [coteditor/CotEditor#1449]
Currently auto-completion in CotEditor is involved from the fist letter typed, which can be very annoying when you have a long document or many words in the text / code starting form the same letter and so on.. -- additionally you can even observe temporary "frozen" state in CotEditor while it's looking for completion candidates (while you don't really need so many) and also wasting your CPU resources.

From the other side, auto-completion feature is very useful and generally well appreciated by many users, so just having it "disabled" is not a good option either ;-))  

A better "trade-off" could be to allow users to decide since how many typed letters the auto-completion should be involved. For ex. it can be configuration option (or hardcoded to 3 letters for ex. if configurable solution is not possible or complicate to implement).

Additionally would be great let involve auto-completion "on demand" by pressing "Tab" key for ex. at the end of the word (currently pressing "Tab" is only used for indent, regardless cursor position)

And also would be great to allow auto-completion not only based on the words list from the current file, but also from all opened files (or all files from the tabs opened in the current window, etc.)

**Comment by 1024jp** [comment]
Thank you for the detailed feedback! It helps me a lot.

Firstly, I need to say the current implementation of auto-completion is actually poor.
It uses the system-level feature to display completion suggestions, which has a lot of limitations, especially in timing control.
I've felt for a long time CotEditor needs to rewrite it completely one day in the future; however, at the same time, it is not the highest priority in my TODO list so far.


> A better "trade-off" could be to allow users to decide since how many typed letters the auto-completion should be involved. For ex. it can be configuration option (or hardcoded to 3 letters for ex. if configurable solution is not possible or complicate to implement).

Yes, this is a realistic solution for the current. I'd say hard coding to three letters is the best since I tend to avoid as possible to add new options in the Settings panes. I'll implement it to the next version. Wait for a while.

> Additionally would be great let involve auto-completion "on demand" by pressing "Tab" key for ex. at the end of the word (currently pressing "Tab" is only used for indent, regardless cursor position)

You can assign a keyboard shortcut for the Complete command in the Edit menu (the default one is Option-Escape). However, maybe as you know, a single stroke like Tab or Esc can not be assigned for keyboard shortcuts for some technical reasons.

> And also would be great to allow auto-completion not only based on the words list from the current file, but also from all opened files (or all files from the tabs opened in the current window, etc.)

This is a bit difficult. I don't think it will be worth implementing by investing a lot of code and making the thing complex.

**Comment by dimitrik-fr** [comment]
Hardcoding to 3 letters probably will be the most simple "short term" workaround, after what you can see if users are needing anything more advanced, or it's already "good enough" ;-))

However, agree that the current Complete feature need some more love, because it's not always matching expectations, specially when writing a code..

For ex.:

- I have many macros in the code starting with MY_TIMER_...
- if I type "MY" and then involve Complete => it'll show a list with everything starting with "MY"
- but if I type "MY_" and involve Complete => it'll not propose anything, because seems like "_" is seen as word separator or so
- and if I type "MY_T" and involve Complete => it'll propose anything starting with "T" or "t" letters, while rather everything starting with "MY_T" would be expected ;-))

**Comment by 1024jp** [comment]
I changed the spec to auto-complete terms first 3 letters were typed.

> For ex.:

That's also a good one to point out.
I've just added `_` character to the completion candidate characters to solve your issue.

**Comment by dimitrik-fr** [comment]
Thank you ! ;-))
