### ISSUE TITLE
Make Hide/Show action for Status Bar / Navigation Bar "global" for a Window, and not per-Tab

### ISSUE THREAD

**Issue by dimitrik-fr** [coteditor/CotEditor#1455]
I was surprised to discover that Hide / Show actions for Status and Navigation Bars are "local" to the current Tab, rather to be "global" for the whole Window.. -- any special reason to do it so ? 

Because it's pretty confusing when you're switching from one Tab into another on the same Window and see Status / Navigation Bar to be present in one Tab, and not in another, and so on..

More "logical" expectation would be to have such a setting global to the whole Window, and not per-Tab, or maybe there is some special idea behind this to implement this way, may you clarify ?

**Comment by 1024jp** [comment]
I'd say it is actually the standard behavior for documentation-based applications in macOS.
See Pages.app, for example.
The visibility of penes in a document is not synchronized among tabs in the same window.
In this world, the window tab is just a band binding multiple windows and there is no communication or relationship among tabs, in general.
In addition, CotEditor stands exactly the same footing.
CotEditor is absolutely a document-based application and not project-based or directory-based, or similar.

Well, on the other hand, CotEditor does extra work for the inspector to sync its visibility among tabs, as a kind of exception.
But I'd rather say, in the macOS world, per document (per tab) or per application is natural rather than per tabbed window.

Then, let's get back on the track, the navigation bar and status bar in CotEditor.
In the current implementation, the change in the visibility of those bars are not synced with other document but the last change will be cascaded to future documents.
I believe the current implementation is not bad at all.
However, taking your feedback into consideration, I now suppose the change of those visibilities should be applied to all windows in the application at the same time.
It is also not unnatural and convenient for users who open a bunch of windows in CotEditor (although I'm not a such user...

Maybe, I'll make the change in the next version (or, 4.5.1.
