### ISSUE TITLE
Add Bookmark feature

### ISSUE THREAD

**Issue by rovf** [coteditor/CotEditor#1484]
**Is your feature request related to a problem? Please describe.**
When editing large files, it would  be convenient to be able to boomark certain lines and be able to go back to those lines quickly.

**Describe the solution you'd like**
Set/Remove bookmark for the current line
Go to next/previous bookmark

**Comment by 1024jp** [comment]
duplicate #300

**Comment by dimitrik-fr** [comment]
No idea if the following comment will help you, but personally I largely prefer Outline tags over Bookmarks (regardless many other code editors are providing Bookmarks feature pretty often).

- Bookmarks are "anonymous", and once you have a lot of them, you're lost again
- while Outline tags will stay forever, and even if you reopen your document a year later, they will help you to find your main parts of code / text / etc..

How you can add Outline tags ?
- personally I'm simply extending the syntax for the given type of files I'm using
- generally it'll be a new regex pattern to match in the comments
- after what I can easily find all my tags in Outline and quickly jump over them

For ex. for files with C code I'm using tagged comments like this `// >>: comment describing this place`

And to make it visible in Outline I need to open C file syntax style in CotEditor and extend it:
- Preferences -> Format
- select "C" in "Available syntax styles:" and click on Pencil icon
- once syntax editing is opened, select Outline
- in Outline add with "+" a new line in Regular expressions: `(// >>:)(.+)`
- and in Title pattern your tag symbol and $2, like ">> $2" for ex. (or you can use emoji instead of ">>" etc.)
- then you click on "OK" and it's done !

Now, whenever in your C code you'll add a comment like `// >>: here is my bookmark` -- you'll see it at once in Outline !! -- as well you can always filter your Outline to reduce the list of items, which is very useful with big files, etc..

**Comment by rovf** [comment]
Bookmarks are not necessarily anonymous. For instance the Kate editor implements them by showing in the bookmarks menu the bookmarks along with part of the code in this line, which helps to identify them.

I certainly don't want to put a comment in my file for showing a bookmark. Of course it is convenient to - for instance - have an alphabetical list of functions (or whatever you have in your file) so that we can directly jump there. However this feature IMO complements bookmarks and does not replace them. 

I use bookmarks during editing to quickly jump between two or three points in the code where I place related edits. I don't even need the bookmarks to survive a restart of the editor, although this could be included for people who want to have "permanent" bookmarks.

**Comment by 1024jp** [comment]
Actually, implementing the bookmark feature is already on [my TODO list](https://github.com/coteditor/CotEditor/milestone/125) and just waiting for its turn.
Since CotEditor is a project I work on in my spare time, everything goes step-by-step.
The use cases you provided are helpful to consider the implementation design. Thank you.
Let me have time.
