### ISSUE TITLE
Option to change font size for the interface (not for the text)

### ISSUE THREAD

**Issue by bemfica** [coteditor/CotEditor#1486]
Tried searching but didn't find any request or issue about that specific subject. If the option already exists, or if it has been discussed before, I ask that you kindly point me to the page.

**Is your feature request related to a problem? Please describe.**
While the options for changing font family and size in CotEditor are great, the interface always stays at a small font body. People with less than optimal sight could find the status bar, sidebar, and other interface elements hard to read

**Describe the solution you'd like**
Add an option in preferences (and/or in the "View" menu) to change the font size for the interface, not only for the text being edited

**Describe alternatives you've considered**
MacOS doesn't offer a built-in option for system-wide font enlargement other than the zoom feature, which is way less than optimal since it requires one to keep roaming through parts of the interface instead of just offering larger elements

**Additional context**
However, macOS _does_ offer ways for individual apps to have their font size enlarged/reduced with Cmd + + or Cmd + -. In CotEditor, as one would expect, this works for the text being edited. Since the system-side option exists, implementing it even without using the hotkeys could be possible.

**Comment by 1024jp** [comment]
Thank you for the request and for sharing your use case.

> could find the status bar, sidebar, and other interface elements hard to read

The font sizes of CotEditor's UI are determined by their respective roles, each with a semantic font size specification provided by macOS, like `small`, `regular`, and so on. Thus, The UI elements less important than the normal UI elements, such as the status bar and sidebar, are drawn in the smaller size. That is, those font sizes are common among the applications in macOS. The UI elements should not be applied to any specific font size only in a specific application.

> MacOS doesn't offer a built-in option for system-wide font enlargement other than the zoom feature, ...

No, unfortunately, the macOS system doesn't provide the option to change those semantic font sizes. I understand it. However, because of the reason I mentioned above, I recommend rather change the resolution of your displays at the system level (System Settings > Displays) instead of forcibly changing the UI elements hierarchy in each individual app. macOS provides various options to increase accessibility.

**Comment by 1024jp** [comment]
However, in order to increase the readability of the data areas (not pure UI elements), CotEditor provides the availability of font size changes. You actually can adjust the font size of the find text fields, find result table, and the outline table in the sidebar in addition to the main editor area. To change them, press the ⌘-Plus or ⌘-Minus keys while focusing on those areas.
Moreover, in the next version, CotEditor 4.5.6, the font size of the script console will become changeable as well.

I suppose those options don't fulfill your request, but please utilize them if they help.
