### ISSUE TITLE
Automatically inserted period after pressing space twice

### ISSUE THREAD

**Issue by clayton256** [coteditor/CotEditor#1497]
### Description

Is there a way to prevent CE from automatically inserting a period after pressing space twice without turning it off system wide? I depend on the feature when writing documentation and emails. But when coding, it create errors.

### To Reproduce

1. type a block of text
2. press the space key twice
3. notice there is a period following the text

### Expected behavior

I would rather there isn't a period inserted

### CotEditor version

Version 4.5.6 (571)

### macOS version

13.5 Beta (22G5059d)

### Additional context

Yes, i'm running macOS ventura beta but this has been happening since the new editor core rolled out.

**Comment by 1024jp** [comment]
> Is there a way to prevent CE from automatically inserting a period after pressing space twice without turning it off system wide?

Currently, CotEditor doesn't have an option to turn it off application-wide.
I understand it is annoying for writing code. Let me think for the future implementation.

**Comment by 1024jp** [comment]
cf. [NSTextView - Any way to prevent the "double space to enter period" MacOS feature? - Apple Developer Forums](https://developer.apple.com/forums/thread/121828)

**Comment by 1024jp** [comment]
I initially planned to implement this feature in the next minor update.
However, now I realized this is way more complicated than I thought since Apple doesn't provide a proper API for it.
So I would like to wait for better API in upcoming systems.

Instead, I recommend you to use the following command in Terminal.app. This allows you to disable the "Add period with double-space" option only in CotEditor.

```sh
defaults write com.coteditor.CotEditor NSAutomaticPeriodSubstitutionEnabled NO
```

**Comment by 1024jp** [comment]
Filed: FB13669125

**Comment by 1024jp** [comment]
While Apple still does not provide any relevant API for this feature, I've implemented it by myself in a redundant way.
I added the option for it in the Mode settings so that the user can customize the behavior per syntax.

<img width="712" alt="Screenshot 2024-11-28 at 11 00 40" src="https://github.com/user-attachments/assets/d3602ef0-247c-4b8c-b7f4-dcda28fe6a07">

This feature will be added to the next version, CotEditor 5.0.6, which will be released in mid-December.
