### ISSUE TITLE
The inspector state is not saved

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1517]
### Description

When a window is closed and the same file is reopened, the inspector state is not saved.

### To Reproduce

1. Create a file. Show "Inspector". Save the file.
2. Quit CotEditor, and then open the file again. There is no problem.
3. However, close the file window (not "Quit") and reopen the file, the inspector state is not saved.

### CotEditor version

4.6.0-beta.2 (583)

### macOS version

13.5.2（22G91）

**Comment by 1024jp** [comment]
The inspector state is not saved for each document file since plain text has no information besides the content text.
CotEditor does remember the inspector states either the application-wide (the last selection will be adopted for the following document) or for per opened document for window restoration (restoring document windows from the last session).

Therefore, this is in spec.

**Comment by tatsy-ymj** [comment]
My point was that the behavior about keeping the outline sidebar visible/hidden seems to have changed from 4.5.9 onwards and before.
However, after re-installing CotEditor, this symptom no longer occurs.
