### ISSUE TITLE
Potential Collaboration?

### ISSUE THREAD

**Issue by mattmassicotte** [coteditor/CotEditor#1524]
Hello!

I work on a bunch of open source projects, many of which are either directly or indirectly related to text editing. I just thought I'd drop in to see if you have any interest in finding a way we might collaborate. Via shared packages could certainly work, but I'm open to any ideas you have!

Some potential starting projects:

https://github.com/ChimeHQ/SwiftTreeSitter
https://github.com/ChimeHQ/Neon
https://github.com/ChimeHQ/LanguageClient
https://github.com/ChimeHQ/WindowTreatment
https://github.com/ChimeHQ/TextStory
https://github.com/ChimeHQ/Rearrange

**Comment by 1024jp** [comment]
Thank you for the kind offer.
I've personally avoided relying on other packages to continue CotEditor development for many years to come. However, LSP is, for instance, one of the things I've been interested in but had no time to touch.
Let me read through the packages you suggested and have time for consideration.

**Comment by mattmassicotte** [comment]
> I've personally avoided relying on other packages to continue CotEditor development for many years to come.

I'm the opposite! I really enjoy collaboration via shared packages. If you have any, or are interested in making some, I'd love to see if I can use them.

I'm also open to other forms of collaboration, I just don't know how it would work.

> However, LSP is, for instance, one of the things I've been interested in but had no time to touch.

That would be great! A number of other projects use the LSP libraries, and I'd be happy to help however I can.

I have tons more libraries too, these were just the ones I thought would be most interesting. I'm very into small, focused libraries. Perhaps there are things you'd like to share with others from CotEditor too! You've done amazing work here.

**Comment by adamshand** [comment]
LSP support would be great!

**Comment by 1024jp** [comment]
I am going to close this post once since it is not tied to a specific issue that needs to be addressed.
I have not forgotten your goodwill, I just don't feel the time has come yet.
Please allow me to consider this in the long term.
Thank you.

> LSP support would be great!

I also believe LSP is a good thing.

**Comment by mattmassicotte** [comment]
Yes, closing this does make sense.

Of course, please take your time! I would love to find a way that would work for you.

**Comment by sihayas** [comment]
Any updates on LSP support? For me the primary things I am missing are LSP, Go To Definition support.

**Comment by 1024jp** [comment]
@mattmassicotte Starting with the next major update, version 7.0, CotEditor will incorporate tree-sitter for several standard languages (syntaxes) and will use your SwiftTreeSitter! Thank you for releasing this useful OSS.

CotEditor 7.0.0 is scheduled for release in late 2026.
At this point, I've completed the basic implementation and plan to continue making improvements to ensure it can withstand actual use going forward.

**Comment by furbytm** [comment]
Hello @1024jp! First off, lovely work with CotEditor so far!

I’ve looked into this space a few times in the past — particularly around the idea of improving Swift LSP support in editors outside of Xcode (for example, experimenting with what cleaner sourcekit-lsp integration could look like for editors such as Zed).

One thing I’ve consistently run into is that the hardest part does not actually seem to be Swift-specific functionality itself, but rather the shared LSP client/runtime infrastructure that editors typically need to implement:

* JSON-RPC transport
* process lifecycle management
* async request routing
* document synchronization
* diagnostics/completion plumbing
* semantic token handling
* workspace coordination

Because of that, I’ve been increasingly wondering whether there may be value in a reusable Swift-native, editor-agnostic LSP client layer that projects like CotEditor could integrate with, while also remaining useful to other editors and tooling projects in the future.

Something conceptually along the lines of:
```swift
let client = LSPClient(
    server: .process("/usr/bin/sourcekit-lsp")
)
```
with editor-specific adapters layered on top.

My thinking is that this could potentially help streamline ecosystem efforts around Swift tooling support instead of each editor independently solving similar LSP infrastructure problems.

I’d be very curious how beneficial or interesting the CotEditor maintainers would view that direction architecturally.

Would CotEditor potentially have interest in integrating with a lightweight/shared LSP infrastructure layer if one existed and stayed modular enough, or would a more self-contained implementation still be preferable?

**Comment by mattmassicotte** [comment]
I'm not sure this issue is the right place to discuss, but what you are suggesting is, more or less, one of the projects I listed above: https://github.com/ChimeHQ/LanguageClient

**Comment by furbytm** [comment]
> I'm not sure this issue is the right place to discuss, but what you are suggesting is, more or less, one of the projects I listed above: https://github.com/ChimeHQ/LanguageClient

Ah, thank you for pointing that out! I somehow completely overlooked `LanguageClient` while researching this space earlier.

Some [potential gaps with `LanguageClient` here](https://github.com/furbytm/CotEditor/issues/1#issuecomment-4494345954) that we can collaborate on?

**Comment by 1024jp** [comment]
@furbytm Thanks for your interest in CotEditor. CotEditor primarily aims to be a simple, lightweight, general-purpose plain-text editor with fully native macOS behavior, and it is not intended to provide extensive IDE-like features or deep support for specific programming languages.

This is not meant as a denial of the value or appeal of LSP features. However, from the current CotEditor project’s perspective, there are several other areas that should take priority, and I’m not interested in supporting LSP at this time.

@mattmassicotte Thanks for the follow-up.
