### ISSUE TITLE
LineNum is not fully shown

### ISSUE THREAD

**Issue by cuilichen** [coteditor/CotEditor#1541]
## Environment 

- CotEditor: 4.6.2 (594)
- System: macOS  Version 13.2（Version No. 22D49）
- Language: Chinese (Simplified)

## Short Description 

The CotEditot does not show line number fully. 
Only 4 cols are shown, but there are millions of lines in my file.
Most of line numbers are not readable for me.

**Comment by 1024jp** [comment]
CotEditor is implemented to expand the line number view when the number grows. I could not reproduce your issue.

So, could you tell me:
1. font name and font size
2. screenshot or screencast of when a part of the number is hidden

In addition, the versions of your CotEditor and system are not the latest. Please update them and check what happens.

![Screen Recording 2023-10-24 at 11 23 56](https://github.com/coteditor/CotEditor/assets/1165044/76dbec35-7917-460e-8f63-954836b32328)

**Comment by liziqiang** [comment]
遇到了相同的问题，@1024jp 试一下这个文件，然后直接定位到文件末尾
<img width="1728" alt="image" src="https://github.com/coteditor/CotEditor/assets/208130/8a580226-fe45-4daa-af28-9993f374440c">

[log09221.txt](https://github.com/coteditor/CotEditor/files/13110417/log09221.txt)

**Comment by wanik** [comment]
This is my case.
The file has 43,312 lines.
When I open it and scroll it down to the end, then the top digit of the line-number is lost (i.e. “3312”, instead of “43312”).
Next, when I change the font-type to ‘fixed,’ then all the digits appear.

- CotEditor: 4.6.3 (596)
- System: macOS バージョン13.3.1（ビルド22E261）
- Language: Japanese

![line_number](https://github.com/coteditor/CotEditor/assets/34469683/2d2971db-0302-495a-b5ee-e5b2401f686e)

**Comment by 1024jp** [comment]
@liziqiang, @wanik Thank you guys for screenshots.
I confirmed and fixed it.
The change will be shipped with CotEditor 4.6.4.
