### ISSUE TITLE
Add Insertion Point to All Selections

### ISSUE THREAD

**Issue by justinnoel** [coteditor/CotEditor#1562]
**Is your feature request related to a problem? Please describe.**
The current "Select Rectangular Area" and "Edit Multiple Points" works well for a few lines of text. However, dozens or hundreds of lines, it is slow and tedious.

Other editors allow a single key combination to insert a cursor at the same column on each selected row. For example, Visual Studio Code has "Add Cursors to Line Ends ⌥⇧I".

**Describe the solution you'd like**
Add A keyboard shortcut and menu item to add multiple insertion points to an entire selection at once.

**Comment by 1024jp** [comment]
> However, dozens or hundreds of lines, it is slow and tedious.

Humm, this year, CotEditor changed the implementation to hold multiple insertion points to support the new insertion point feature on macOS 14. Due to it, I can imagine it is now hard to have a large number of insertion points. However, I suppose, there is no way to detour it. Sorry.
I personally recommend to utilize regex to insert the same text at a bunch of points at once. 

> Add A keyboard shortcut and menu item to add multiple insertion points to an entire selection at once.

Could you elaborate a bit more on your request?
Is the “Add Cursors to Line Ends” command fulfill it straightforwardly?

By the way, CotEditor accepts the most of emacs key bindings.
In addition, CotEditor has a command to add an insertion point above/below the current one by pressing <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>↓</kbd>/<kbd>↑</kbd> keys? Does it work for you?

<img width="876" alt="Screenshot 2023-12-18 at 18 29 02" src="https://github.com/coteditor/CotEditor/assets/1165044/3d3f85c9-0392-415b-a259-b15ccc2ee0eb">

**Comment by 1024jp** [comment]
Note: I also found the “Split Selection by Lines” command in Xcode.

<img width="630" alt="Screenshot 2023-12-18 at 19 00 26" src="https://github.com/coteditor/CotEditor/assets/1165044/51483220-c76e-4371-a569-34cef0b48fcf">

**Comment by justinnoel** [comment]
Thanks so much for getting back to me. Here's a link to a short video to show the comparison between CotEditor and VS Code.
 
 https://customer-2haawx7cuvbfttcn.cloudflarestream.com/f1234ddb514abcedf46e4828952ad92d/watch

**Comment by 1024jp** [comment]
“Split Selection by Lines” command will be added to the Edit > Select menu in the next minor update, which will be released this autumn.
