### ISSUE TITLE
Opening previous files that were not closed 

### ISSUE THREAD

**Issue by mlcampbe** [coteditor/CotEditor#1576]
### Description

Sometime over the last release or 2 it seems that the editor is now starting to open previous used files. For example, if I open a text file and then quit the editor the next time I use the editor on a different file then the previous text file also gets opened. I modified the setting 'reopen windows from last session' to be unchecked and that has helped some but now I get a blank "untitiled" window every time I open any file.

### To Reproduce

See above use-case

### Expected behavior

I expect that the editor only open the 1 file I double click, not all previously unclosed files nor open a new untitled window when editing an existing file.

### CotEditor version

4.7.2 (625)

### macOS version

14.1.2

**Comment by 1024jp** [comment]
This is by design.
The current CotEditor opens at least one window (either a previously opened document, an untitled document, or the open dialog) on launch.
This is the standard behavior among proper macOS apps.
If you open any document after CotEditor creates a blank untitled document, CotEditor substitutes the blank document with the one you opened.
