### ISSUE TITLE
A more visible, block-type text cursor

### ISSUE THREAD

**Issue by YBPN** [coteditor/CotEditor#1605]
With my vision, sometimes I have trouble locating the text cursor at a glance. I miss the customizability of the text cursor on Windows. It would be very nice to be able to customize the the text cursor to be much wider for better visibilty, e.g. as wide as the letter 'm'.

**Comment by 1024jp** [comment]
Which version of macOS do you use?
CotEditor once had a feature to change the width of the cursor before but deprecated in CotEditor version 4.6.0 because macOS changed the system cursor mechanisms to use a thicker line on macOS 14.
And with the new cursor system, it is hard to change the cursor shape with the current implementation in CotEditor.

So if you still use macOS 13 and feel hard to find the cursor, I recommend upgrading your macOS.
If you already use the thicker cursor in macOS 14; sorry, but I cannot support a cursor shape customization immediately.

 
<img width="284" alt="Screenshot 2024-04-05 at 9 15 32" src="https://github.com/coteditor/CotEditor/assets/1165044/d270a501-0014-49ed-97dd-bfaf0d02ae7b">

**Comment by 1024jp** [comment]
Thank you for your reply.
Then, I have to say I cannot change the current cursor shortly because customizing the shape of the new cursor system provided by Apple is not possible with the current CotEditor implementation.
I am sorry.
But I will remember for the future change that some people need a more prominent curso.
