### ISSUE TITLE
The Open dialog always shows up on launch despite the setting on CotEditor 4.8.3

### ISSUE THREAD

**Issue by ykqmain** [coteditor/CotEditor#1638]
### Current issue

Because I often use CotEditor as a draft paper, I hope that when opening CotEditor, it is a new blank text by default. The new version adds a new function. it opens the document selection by default, which seriously affects daily work.

### The solution you'd like

Restore the default behavior of the previous version, or add a switch for users to choose from.

### CotEditor version

4.8.3 (649)

### macOS version

macOS 14.5

**Comment by 1024jp** [comment]
Hmm, this is not an intentional change but can be a side effect of an implementation change in 4.8.3.
It works as expected in my environment but perhaps there is a case that is out of order.
This behavior on launch can be affected by multiple conditions.

Therefore, to break down the issue, could you share a screenshot of the General settings pane and also whether you use the iCloud Drive feature in CotEditor?
Regarding the iCloud Drive, you can check it in System Settings > Your account (the first item in the sidebar of the System Settings window with your icon) > iCloud > iCloud Document > Apps Syncing to iCloud Drive.

<img width="712" alt="Screenshot 2024-05-15 at 2 20 08" src="https://github.com/coteditor/CotEditor/assets/1165044/6173d0b6-4615-4bbf-aab3-7e5854e66370">


> when opening CotEditor,

In addition, could you also let me know more exactly when?
Is there a difference in the two following actions?:
- When you launch the application that has not been started yet.
- When you click the app icon in the dock which has already been started.

**Comment by inf0dr0id** [comment]
I have the same issue since 4.8.3 installed from the Apple app store.

> When you launch the application that has not been started yet.

It now opens the "file open" dialog despite the settings.

> When you click the app icon in the dock which has already been started.

It opens a new empty document window as configured in the settings.

<img width="712" alt="Bildschirmfoto 2024-05-15 um 10 29 03" src="https://github.com/coteditor/CotEditor/assets/24397146/cf19fc2d-1071-48ad-b405-673584112f33">

App syncing to iCloud is enabled.

**Comment by wanik** [comment]
Maybe the same case:
- CotEditor: 4.8.3 (649)
- System: macOS バージョン13.6.6（ビルド22G630）
- Language: Japanese

1. 設定 ＞ 一般 ＞ 起動したとき　において、もともと「新規書類を作成」を選択していましたが、「"開く"ダイアログを表示」にして、アプリを再起動しました。
2. 結果は、確かに、「"開く"ダイアログ」になりました。
3. 次に、もとに戻そうとして、**「新規書類を作成」を選択して、アプリを再起動しました**。
4. しかし、今度は、**再び「"開く"ダイアログ」が現れ、「新規書類」が開かれませんでした**。
5. その後、「新規書類」が開かれない状態が続いています。

**Comment by Phate0001** [comment]
I have the exact same issue too.

It always happens when I  launch the application that has not been started yet!
It does not happen when click the app icon in the dock which has already been started!

CotEditor syncing to iCloud Drive: YES!

## Environment (Environment)

- CotEditor: 4.8.3 (649)
- System: macOS Version 14.5 (Build 23F79)
- Language: German


## Short description (Short description)
Instead, the “Open file” dialog appears, although it is set differently in the settings.
The “Create new document” behavior does not work and the “Open file” dialog is always displayed when the program is restarted.

## Steps for reproduction (Steps for reproduction)

## Expected result (Expected result)
When restarting, a new window and an “Untitled” file should be created where you can start directly.

**Comment by faiare** [comment]
- CotEditor: 4.8.3 (649)
- macOS 14.5（23F79）(Same problem in 14.4)
- Language: Japanese
- iCloud Drive: Yes

I have the same issue too.

I updated CotEditor from a previous version in the App Store.
I have not made any changes to configuration during that time.

Please let me know if you need any other information.

![スクリーンショット 2024-05-17 10 59 37](https://github.com/coteditor/CotEditor/assets/11206952/f303c2fb-4e7f-4c95-95a2-120723fb5fde)

**Comment by Ryo-ryomac** [comment]
I am also experiencing the same inconvenience.

The environment is the same.
    CotEditor: 4.8.3 (649)
    macOS Sonoma 14.5（23F79）
    Language: Japanese
    iCloud Drive: Yes

**Comment by ykqmain** [comment]
@1024jp 

When you mention iCloud Drive, I think I understand its logic because when I used macOS's textEdit.app before, they had similar behaviors.

Closing iCloud Drive in CotEditor can solve this problem, but this setting is hidden too deeply in macOS, which may be too complex for beginners.

As far as I know, it is precisely because of this feature of textEdit.app that a large number of people use CotEditor as a substitute for textEdit.app. Will this feature be adjusted in future versions?

**Comment by 1024jp** [comment]
Thank you for the report, guys.
I realized the Open dialog forcibly shows up when the "Reopen windows from last session" option is turned off.
I'll fix it in the next version. Please be patient for a while.

**Comment by 1024jp** [comment]
Sorry for taking time.
Contrary to intuitive sense, it is incredibly complex to reliably suppress the Open dialogs in modern Cocoa applications...
(I don’t understand why Apple hides the chance to control it.)

Well, anyway, I believe now I succeed in fixing this in all possible setting combinations.
The fix will be shipped within this week.

**Comment by 1024jp** [comment]
Submitted feedback to Apple: FB13807016
