### ISSUE TITLE
Request: Option to wrap at page guide column setting

### ISSUE THREAD

**Issue by timclloyd** [coteditor/CotEditor#1649]
### Current issue

I use Coteditor for writing in markdown, and reading prose is easier when the line length isn't very long. 

### The solution you'd like

I would like an option to wrap text at a specified column. If this option were enabled at the same time as 'Wrap lines to editor width', I would want the lines to wrap at the editor width if it was shorter than the specified column. 

### Alternatives you've considered

Making the window narrower isn't always a good solution, or an option. E.g. if I want to focus on writing by making Coteditor full screen, there's currently no way to have a readable line length.

### CotEditor version

4.8.5 (653)

### macOS version

14

**Comment by 1024jp** [comment]
Duplicated #529.

**Comment by 1024jp** [comment]
The same request was already registered in #529 (it was posted in Japanese, tough).
So I close his one.

I am actually trying to implement it for years, but still not finished because text wrapping in CotEditor is already quite complex since it supports right-to-left writing, vertical writing, pinch zoom, promotional font, etc.
