### ISSUE TITLE
Strikethrough not highlighting on markdown

### ISSUE THREAD

**Issue by cal-ellevation** [coteditor/CotEditor#1651]
### Description

Highlighting not working for strikethrough when doing something like "~~this should be striked out~~". Highlighting is as if it is all just text.

### To Reproduce

Type text into editor with ~~ surrounding text and see that it isn't striked out.

### Expected behavior

Text would have some way to show that it should be striked out.

### CotEditor version

4.8.5

### macOS version

Sonoma 14.5

**Comment by 1024jp** [comment]
Oops it is a kind of bugs that the current Markdown syntax doesn't highlight (= colorize) strikethrough.
I've just fixed it so that the fix will be shipped with the next version, CotEditor 4.8.6.

But CotEditor never actually draw strikethrough line for strikethrough markup in Markdown syntax.
CotEditor is a general text editor. It colorize keywords, or specific patterns of text, but not style it as Markdown says.

**Comment by cal-ellevation** [comment]
Colorized is great!
