### ISSUE TITLE
CotEditor doesn't display all invisible characters

### ISSUE THREAD

**Issue by victormoliveira1** [coteditor/CotEditor#1662]
### Description

The following characters aren't displayed as invisible characters in CotEditor, even with all checkboxes enabled in General > Invisible characters:

[Next Line](https://unicode-explorer.com/c/0085) (Codepoint U+0085, NEL)
[Zero Width Joiner](https://unicode-explorer.com/c/200D) (Codepoint U+200D, ZWJ)
[Line Separator](https://unicode-explorer.com/c/2028) (Codepoint U+2028, LS)
[Paragraph Separator](https://unicode-explorer.com/c/2029) (Codepoint U+2029, PS)
[Zero-Width No-Break Space](https://unicode-explorer.com/c/FEFF) (Codepoint U+FEFF, ZWNBSP)
[Soft Hyphen](https://unicode-explorer.com/c/00AD) (Codepoint U+00AD, SHY)

Operators of [General Punctuation](https://www.w3.org/TR/2010/REC-MathML3-20101021/chapter3.html#presm.invisibleops):
[Function Application](https://unicode-explorer.com/c/2061) (Codepoint U+2061, FA)
[Invisible Times](https://unicode-explorer.com/c/2062) (Codepoint U+2062, IT)
[Invisible Separator](https://unicode-explorer.com/c/2063) (Codepoint U+2063, IS)
[Invisible Plus](https://unicode-explorer.com/c/2064) (Codepoint U+2064, IP)

My observation was based from this [table of non-printing characters](https://npp-user-manual.org/docs/views/#show-symbol) where only NEL, ZWJ, LS, PS, ZWNBSP and SHY wasn't detected by CotEditor, and from this [post](https://community.notepad-plus-plus.org/topic/24209/new-n-feature-to-show-hide-non-printing-characters) / [issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13408) where only FA, IT, IS, IP (General Punctuation block) wasn't detected.

Note: In some instances, when editing the open document, it appears that CotEditor actually detects these characters. Unfortunately, this behavior was not predictable enough to be reproduced.

### To Reproduce

1) Create a new document

2) Open every Unicode description mentioned above

3) Click on "Copy to the clipboard" and paste on the open document

### Expected behavior

The specified characters should be marked as invisible (non-printable) characters.

### CotEditor version

CotEditor 4.8.6

### macOS version

MacOS Sonoma 14.5

**Comment by 1024jp** [comment]
related #1462

**Comment by 1024jp** [comment]
cf. The current spec in CotEditor (“Display invisible characters in CotEditor” page in the CotEditor User Guide)

<img width="875" alt="Screenshot 2024-07-02 at 14 19 32" src="https://github.com/coteditor/CotEditor/assets/1165044/7c6cfcae-3252-4dfb-ae90-09f9792f631c">

**Comment by 1024jp** [comment]
Thank you for the feedback.

> Operators of General Punctuation:
> Function Application (Codepoint U+2061, FA)
> Invisible Times (Codepoint U+2062, IT)
> Invisible Separator (Codepoint U+2063, IS)
> Invisible Plus (Codepoint U+2064, IP)

These are currently missing from the list.
I'll add them in the next update, CotEditor 4.8.7.

Regarding the rest of the codepoints, they are either already added or intentionally excluded.

> Next Line (Codepoint U +0085, NEL)
> Line Separator (Codepoint U+2028, LS)
> Paragraph Separator (Codepoint U+2029, PS)

These three characters are registered and displayed as “Line ending.”
You could not see those invisible characters shown because you did not correctly enter those characters.
In CotEditor,  all line endings are automatically replaced with the line endings in the document.
This is to prevent unintentional mixing of line ending codes when the user copies and pastes text from another source while editing their document.
To input a line ending other than the document's line ending:
- Perform the “Paste Exactly” command.
- Input a character by specifying its code point using the “Input In Unicode Code Point” command. 

See the “Handle various types of line endings” page in the CotEditor User Guide for details.

<img width="796" alt="Screenshot 2024-07-02 at 19 22 03" src="https://github.com/coteditor/CotEditor/assets/1165044/bab5ebcb-fd7c-4185-ab2a-2a5a4b3b52c1">


> Zero-Width No-Break Space (Codepoint U+FEFF, ZWNBSP)

<img width="350" alt="Screenshot 2024-07-02 at 19 35 59" src="https://github.com/coteditor/CotEditor/assets/1165044/03ee9062-fa4d-4083-807e-2bc1676ca88f">

This character is already on the list. It should be drawn as an invisible control character.
You may have missed something.
Try inputting it with the Unicode code point.


> Soft Hyphen (Codepoint U+00AD, SHY)

I have previously tried but found out it is technically difficult with the current implementation because there is no way in the framework to distinguish whether the (soft) hyphen is displayed or not.
See #1462 for details.


> Zero Width Joiner (Codepoint U+200D, ZWJ)

I have intentionally excluded this as an invisible control character to be drawn also due to limitations in the framework.

**Comment by 1024jp** [comment]
Actually, there is no specific definition of "invisible characters" to be drawn by editors, so each editor must define them on its own.
I do my best, but it can be differed from other editors.

**Comment by victormoliveira1** [comment]
Hi @1024jp, thanks for your feedback and the quick fix! I already updated to CotEditor 4.8.7 and can confirm that the characters mentioned are now drawn as expected.

> In CotEditor, all line endings are automatically replaced with the line endings in the document.
This is to prevent unintentional mixing of line ending codes when the user copies and pastes text from another source while editing their document.

I see, now I understand why these line endings codes was "disappearing" when I opened a text file with them included.

However, there's one thing I noticed that is closely related to this: when I open a text file with those line endings codes, even if I click on "Ignore" or "Review" in the dialog below, CotEditor still tries to replace them with the default line ending. I have to do ⌘Z (Undo Line Endings to X) so I can see them and inspect it in the Inspector window.

<img width="281" alt="CotEditor_Inconsistent_Line_Endings_Dialog" src="https://github.com/coteditor/CotEditor/assets/82281570/9805250a-8434-4f5a-9ef2-7164a0b263a3">

> This character is already on the list. It should be drawn as an invisible control character.

You're right, I can confirm that the Zero-Width No-Break Space character is being drawn as an invisible control character.

About the Soft Hyphen and Zero Width Joiner, it's a shame that it's not possible, but it's okay.

**Comment by victormoliveira1** [comment]
@1024jp, I forgot this one. While not technically a non-printable character, I think that this one is worth adding, because it's considered a format character (CF):
[Syriac Abbreviation Mark](https://unicode-explorer.com/c/070F) (Codepoint U+070F, SAM)
