### ISSUE TITLE
Add option to quit the app when last window closed

### ISSUE THREAD

**Issue by arvet333** [coteditor/CotEditor#1666]
### Current issue

Please add an ability to automatically quit the app when no opened windows left.

### The solution you'd like

It would be nice to have such an option in settings of the app...

### CotEditor version

Version 4.8.6 (655)

### macOS version

14.5 (23F79)

**Comment by 1024jp** [comment]
ref. #1233

**Comment by 1024jp** [comment]
See my comment in https://github.com/coteditor/CotEditor/issues/1233#issuecomment-1015082478

If you still have a issue (e.g. the app does not terminate 100% even the application goes to background), let me know.

Additionaly, since this behavior is done automatically by the system for optimization purposes, the application may not be terminated depending on the state of the Mac's memory at the time.
