### ISSUE TITLE
Shortcut keys to operate Folder Navigation

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1698]
### Current issue

It is not possible to move the focus to the Folder Navigation, move between files, and then move the focus back to the main window again using only the keyboard.

### The solution you'd like

I'd like to set keyboard shortcuts for Folder Navigation operations.
It would be more convenient to be able to use shortcuts such as Command+1 or Command+2 to directly access files listed in the Folder Navigation.
I'd like to use this feature to quickly switch between multiple files for notebooks.

### CotEditor version

5.0.0-beta.2 (663)

### macOS version

14.6.1（23G93）

**Comment by 1024jp** [comment]
Implemented in v5.0.0-beta.3.
(Used <kbd>Control</kbd>+<kbd>Command</kbd>+<kbd>1</kbd> for the shortcut keys since <kbd>Command</kbd>+<kbd>1</kbd>–<kbd>9</kbd> are already used to switch window tabs.)

<img width="510" alt="Screenshot 2024-09-08 at 13 12 20" src="https://github.com/user-attachments/assets/823a0b5f-8be6-4667-92fb-946844a96484">

**Comment by tatsy-ymj** [comment]
@1024jp Thank you for Control+Command+1! 
How about shortcut keys for Folder Navigation -> Main Windows?
If CotEditor had this shortcut key, I could go back and forth between multiple files and edit them using only keyboard.

**Comment by 1024jp** [comment]
> How about shortcut keys for Folder Navigation -> Main Windows?

Not yet implemented. I'm just struggling with naming and shortcut key mapping...

**Comment by 1024jp** [comment]
> How about shortcut keys for Folder Navigation -> Main Windows?

I've finally fixed the spec.
In the next version, CotEditor 5.0.6, I improved the behavior of the "Move Focus to Next/Previous Editor" to move the focus on the editor if the focus is out of the editor, for example, on the file browser, so that you can move your focus from the file browser to the editor.
I'll assign the new shortcuts to these commands to be the same as the corresponding commands in Xcode.
