### ISSUE TITLE
Cant enable sidebar - file pane 

### ISSUE THREAD

**Issue by Fischmuetze** [coteditor/CotEditor#1717]
### Description

Cant enable sidebar file browser. .. both menu entries for the sidebar are always greyed out
No idea how to enable ... if there is a way its far away from intuitive

### To Reproduce

Start the app, open a file .. try to enable the sidebar 

### CotEditor version

5.0.0

### macOS version

macOS Sonoma 17.4 (23H124)

**Comment by Fischmuetze** [comment]
ok got it ... click on a folder in the open dialog will enable the sidebar, but this is a very, very strange idea.
The standard macOS behaviour for selecting an folder and click on the the open button will dive the dialog browser into the selected directory. This is NOT a macOS standard conform behaviour and far away from intuitive ... :( 
The reason why all other macOS editor I know have an extra menu entry for open a directory

**Comment by 1024jp** [comment]
>  click on a folder in the open dialog will enable the sidebar

I believe just clicking a folder in the Open dialog does not open a document with the sidebar but just moves into the folder in the dialog. In order to open a folder as a window, you need to click the "Open" dialog.
In addition, this is the standard behavior of the Open dialog in macOS, as CotEditor does nothing for the file browser in the open dialog.

> The reason why all other macOS editor I know have an extra menu entry for open a directory

Hmm, for instance, macOS-native editors such as Nova, CodeRrunner, and CodeEdit have only the Open command performing in the same manner.
(I suppose BBEdit also has only the Open command.)


> and more there are no tabs for open documents in such file browser windows nor a switcher for open files and all files will always saved even the option is disabled

It's a feature task already posted in another thread: #1712.

**Comment by aydindemircioglu** [comment]
sorry, if i reopen.

first thanks for the incredible editor!

i just wanted to ask if this can be changed-- 
in 5.0.4, i have this behaviour:
- open file directly, then view->sidebar->file browser is greyed out.
- open directory first, then sidebar is visible, and ican select file browsers.
i find this unintuitive, somehow. why not allow view->sidebar->file browser anytime? 
for me, it means i have to close the file, reopen the directory, open the file again,
although the option is nearly there.

**Comment by 1024jp** [comment]
@aydindemircioglu The short answer is unfortunately “no.”

CotEditor adopts the Sandbox security mechanism and document-based app design both by Apple.
That is, an app with Sandbox has a strict file access limitation. A sandboxed app can open only files/folders the user intentionally opened.
When a file is opened in a document-based app, it becomes a file document, which has a standard window without the file browser.
Likewise, only when a folder is opened in the app, it becomes a folder document, of which window has a file browser.
A folder document has the access permission only to its file and therefore cannot turn into a folder document afterward.

**Comment by Fischmuetze** [comment]
> CotEditor adopts the Sandbox security mechanism and document-based app design both by Apple.
> That is, an app with Sandbox has a strict file access limitation. A sandboxed app can open only files/folders the user 
> intentionally opened.

There are many applications that can do this by asking for permission in advance. 

I can only agree with @aydindemircioglu that this behavior and the resulting operation is completely unintuitive and I have never seen this approach in this way in any other app. This weird solution is also far away from any design giudelines ...

Anyway of course your design decision - if you are lucky with it - some users obviously are not.

**Comment by Fischmuetze** [comment]
> ... i do not second your tone.
fine with me - guess this is a language to language transforming issue ...

**Comment by 1024jp** [comment]
Hmm, for instance, Xcode and CodeEdit behave similarly.
However, apart from that, different apps have different purposes.
CotEditor is not intended to be a replacement for VS Code.

CotEditor is actually designed to edit random document files rather than work with projects.
Furthermore, CotEditor principally aims to function perfectly in the macOS manner.
Therefore, I prefer to adhere to the standard macOS application principles for document-based applications.
I also don’t want to carelessly grant access permissions to the entire disk, even if I have the ability to do so.
This may sometimes not suit some users’ needs, but designers must make a choice, and this is how CotEditor makes decisions.
