### ISSUE TITLE
check spelling setting not saved

### ISSUE THREAD

**Issue by ndxyz00** [coteditor/CotEditor#1750]
### Description

Hi, 
the setting "edit - spelling and grammar - check spelling while typing" is not saved,
if you deselect it, the next time you open the document, next document you open in the same session etc it will be on again

**Comment by 1024jp** [comment]
Toggling it from the Edit menu is just for temporal change for the current window.
This is by design.

If you want to change the setting permanently, set it in the Mode settings pane.

<img width="712" alt="Screenshot 2024-11-02 at 0 12 44" src="https://github.com/user-attachments/assets/704c22ca-a6af-4468-be56-6254847a17a5">
