### ISSUE TITLE
Stubborn / unpredictable window sizes

### ISSUE THREAD

**Issue by TheTreesKnees** [coteditor/CotEditor#1783]
### Description

This issue probably started around the 5.0.3 and 5.0.4 releases. No matter the size / position of the CotEditor window, after quitting the program and relaunching, it insists on using all the available space (like using <kbd>fn</kbd> <kbd>^</kbd> <kbd>F</kbd>).

Is there a setting to prevent this? Sometimes it even happens when creating a new tab (<kbd>⌘</kbd> <kbd>N</kbd>). Starts to eat away my sanity...

### To Reproduce

-

### Expected behavior

-

### CotEditor version

5.0.7 (690)

### macOS version

15.2 (24C101)

**Comment by 1024jp** [comment]
Thank you for the report.

However, I’ve never encountered this phenomenon before and couldn’t replicate it.

So, could you please provide additional information so that I can narrow down the register?

1. Your window size setting in the Window settings pane. 
2. Screen recording of this phenomenon.
3. Is the document window facing this issue has the side bar (for folder documents)?
4. Whether the situation changes if you run the following lines in Terminal.    ```sh
     $ defaults delete com.coteditor.CotEditor "NSWindow Frame Document"
     $ defaults delete com.coteditor.CotEditor "NSSplitView Subview Frames WindowContentSplitView"
     $ defaults delete com.coteditor.CotEditor "NSWindow Frame DirectoryDocument"
     $ defaults delete com.coteditor.CotEditor "NSSplitView Subview Frames DirectoryWindowContentSplitView"
     ```

**Comment by TheTreesKnees** [comment]
Thanks for your quick reply!

It started to work as expected just after executing the first command (**defaults delete com.coteditor.CotEditor "NSWindow Frame Document"**) 👍

But... (there's always a "but") try the following:

1. use the "fill" window command (<kbd>fn</kbd> <kbd>^</kbd> <kbd>F</kbd>)
2. quit CotEditor (<kbd>⌘</kbd> <kbd>Q</kbd>)
3. launch CotEditor
4. resize the window
5. quit CotEditor again
6. launch CotEditor
7. it's filled ("maximized") again 🤔

So as long I don't use the fill command it keeps remembering the window size / position. Otherwise I have to use the terminal command to restore the correct behavior.

**Comment by 1024jp** [comment]
Great! Thank you for providing the additional information.
I’ve successfully reproduced this phenomenon and identified its cause.
I appreciate your help.

That is, when a user changes the document window size, the geometrical values are stored in a specific format, such as:

```
"NSWindow Frame Document" = "795 90 644 717 0 0 1440 875 ";
```

This is the standard and expected behavior.
However, when the user performs the shortcut Window > Fill (`fn` + `-` `F`), additional information, `tilingState`, is appended. This information may indicate that the user prefers the fill tiling.

```
"NSWindow Frame Document" = "105 56 641 720 0 0 1440 875 {"tilingState":{"tilingPosition":9,"normalizedSize":1,"untiledFrame":"{{373, 93}, {641, 720}}"}}"
```

The problem is, this tiling state information is not updated even the user changes the window size later and also I have been unable to find a way to update this “tilingState” as of my investigation.

I'll investigate more is there any way to update this additional values for taking a workaround in CotEditor.
But I feel this is a kind of issues by the Apple's framework side.
I'll send a feedback to Apple.

**Comment by 1024jp** [comment]
Ok, I gave it another try after my work, and this time, I revealed what happens with this phenomenon.

In short, Apple itself should improve this behavior, and 3rd party app has nothing to do.

Telling the details, this phenomenon occurs due to the following logic:

1. CotEditor updates the initial window size and position using the window frame saving API provided by the macOS app framework, AppKit, whenever a document window is moved or resized. <- This is intentional.
2. AppKit sets the tiling state flag for a window when the Window > Fill command is performed.
3. While the flag is set, AppKit stores the tiling flag state along with the window frame.
4. When the flag is stored with the initial window frame settings, the app uses it for a new document window or the next time it launches.
6. This fill tiling state is removed **only when the window is moved** by the user. Namely, the state still remains when the user only resizes the window. -> You can notice by the window resizing animation that ends the fill-tiling mode

You may not have moved the document window, but you just resized it. To terminate the fill-tiling mode, you need to move the window.
Thus, the current behavior would be by design rather than a bug.
The other apps behave in the same manner.
For example, you can reproduce the same behavior on other Apple apps, such as Text Edit.

So, I’d like to conclude that CotEditor simply follows the current behavior without taking any workarounds.

However, because I understand your confusion with this design, I believe Apple should change it to remove the fill-tiling state flag also when the user resizes the window.
Therefore, I'll send the feedback about it to Apple later.

**Comment by TheTreesKnees** [comment]
Thank you for this extensive investigation!

> You may not have moved the document window, but you just resized it. To terminate the fill-tiling mode, you need to move the window.

True, I didn't even think of that. If I snap the window out of this "tiling state" first (by moving it) and resize it after that, it works as expected.

Interesting enough, on my end TextEdit refuses to keep any size / position information and just does "whatever" with every launch, tiling or not. 😂 Safari seems to be safe, it works either way.

I agree that this *looks* like an oversight on Apple's part. You may have been caught off guard by sticking to recommended way of handling this, and they broke it.

**Comment by 1024jp** [comment]
Reported to Apple. [FB16862942](https://github.com/1024jp/AppleFeedback/issues/8).
