### ISSUE TITLE
行移動機能 / Swap Line Up/Down commands

### ISSUE THREAD

**Issue by ha810** [coteditor/CotEditor#338]
行移動の機能があったら便利と思い、要望させていただきます。
現在カーソルがある行を、ショートカットキーで行ごと上下に移動させるイメージです。
言葉でうまく伝えにくく、他エディタの話で恐縮ですがSublimeTextの　^ + ⌘ + ↑　を押した際の挙動です。
行を複数選択している状態で行った場合、選択されている行がまとめて移動します。
ご検討頂けたらと思います。

**Comment by 1024jp** [comment]
フィードバックありがとうございます。

Sublime Text で挙動確認しました。たしかにこれは慣れていると便利そうな機能ですね。
ただ、現時点では CotEditor はコマンドでのニッチなテキスト操作に対してあまり積極的にカバーしておらず、このあたりはユーザが各自スクリプトで対応するという姿勢を取っています。
この機能だけ安易に追加すべきかは少し考える必要がありそうです。

とはいえ、利用価値が高く利便性が高まるのであれば今度盛り込んでいくべきでしょう。
アプリケーション全体の方向性の話になるので、採用するかも含めて、少々検討させてください。

-- 
Thanks for your feedback.

I can't say at this moment that I implement it, because CotEditor doesn't support such relative trivial text  handling commands proactively so far.

However, CotEditor should, of course, implement such features in the future if it makes users feel convenient.
Well, I'll consider about it.

**Comment by ha810** [comment]
ご検討ありがとうございます。
SublimeTextから乗り換えてきた身としては、マルチカーソル同様実現したら嬉しい機能の一つです。

**Comment by 1024jp** [comment]
お待たせしました。
この機能は CotEditor 2.3.0 で実装されます。


---

This feature will be implemented on CotEditor 2.3.0.

**Comment by ha810** [comment]
ありがとうございます。
作業が捗り大変助かります。
バージョンアップ後確認したいと思います。
