### ISSUE TITLE
Version 2.1 β find & replace tool panel loses "highlight"

### ISSUE THREAD

**Issue by cool8jay** [coteditor/CotEditor#346]
The layout change in general is good, some tweaks are really nice, like:

1. focus highlight effect for "find" and "replace" input frame.
2. move "clear history" function to the right place as next to the history itself.
3. the regexp tip button is nice!
...

However, I notice one thing, my favorite thing, is missing:
![cotedit find](https://cloud.githubusercontent.com/assets/55504/5953674/2f32da36-a7c8-11e4-9b17-60cbc45ab326.jpg)

For me, the "highlight" function is a good way to spot something in a global view, different from a list of  dispersive occurrences with "find all" function.

So, I suggest restore this button like this, very easy, huh!

![last 3](https://cloud.githubusercontent.com/assets/55504/5953983/33754b52-a7cc-11e4-8ad0-b765ae8f59ec.jpg)

**Comment by 1024jp** [comment]
Hi, thanks for your feedback.

I dropped the Highlight button once because layouting all buttons in a single line makes find panel too wide.
However, I know some users (and in fact also I) prefer to use "Highlight" action instead of "Find All."
I need to find a solution.

The proposals I come up with are:

1. Just add "Highlight" button and accept the size of the panel
2. Add a custom option to swap "Find All" button with "Highlight"
3. Add a custom option to change "Find All" button action to perform the Highlight action (the button label is still "Find All").
4. Leave it as it is.
5. Other

How do you guys think about it?
 
Anyway, I'll bring back the Highlight button somehow on the next β2 that will be released in the next days.
At the moment, you can still perform Highlight from the Find menu in app's menu bar.

---

フィードバックどーもです。

ハイライトボタンは、1列にすべてボタンを並べると検索パネルの幅が大きくなりすぎるので一旦削除してみました。
しかしながら、ユーザによっては（というか私も）「すべて検索」アクションよりも「ハイライト」アクションの方を好んで使っていることも理解しています。
解決策を探す必要がありそうです。

目下思いつくものとしては：

1. 単純に「ハイライト」ボタンを追加して、パネルサイズが大きくなることは受け入れる
2. 「すべて検索」ボタンを「ハイライト」ボタンを入れ替えられる設定オプションを追加する
3. 「すべて検索」ボタンのアクションを「ハイライト」アクションと入れ替えられる検索オプションを追加する（ボタンのラベルは「すべて検索」のまま）
4. 現状まま
5. その他

どう思いますか？

**Comment by 1024jp** [comment]
the sixth option:

6. Highlight all matched strings on "Find All" action and remove "Highlight" action. (This takes a bit time to implement. But when it's better.)

**Comment by 1024jp** [comment]
I've remove the "Replace & Find" button from the find panel since its function is similar to "Replace" so users might not use them at the same time. Now, a new "Select Next Match after Replace" option is added.

Hence, the button space issue is now resolved. We have now enough room for Highlight button. However, it is still a question whether I should merge "Highlight" function to "Find All" action.

![screen shot 2015-01-30 at 00 19 20](https://cloud.githubusercontent.com/assets/1165044/5960037/fe7ca96e-a815-11e4-99bc-d3d8e0da5357.png)

---
「置換と検索」と「置換」は機能が似通っており同時に使用するユーザは少なそうなので、「置換と検索」ボタンを検索パネルから削除しました。その代わりに新たに「置換後に次のマッチを選択」オプションを追加しました。

これにより、「ハイライト」ボタンを置く場所がない問題は解決しました。とはいえ、「ハイライト」ボタンを復帰させるべきか「すべて選択」に統合すべきかという課題はまだ残っています。

**Comment by 1024jp** [comment]
I’ve studied the OgreKit framework again and then realized that it’s really hard to highlight Find All results. Thus, unfortunately, we must give up the sixth choice; to hightlight matched texts on “Find All”.

So I've just quick restore the Highlight button to find panel. I believe it's now better than the first beta version.

![screen shot 2015-01-30 at 22 50 56](https://cloud.githubusercontent.com/assets/1165044/5976538/7738b66a-a8d2-11e4-8d39-ca65f5416535.png)
