### ISSUE TITLE
icalendar形式のシンタックススタイルはありませんか？/Is there the syntax style of icalendar format?

### ISSUE THREAD

**Issue by takei3kakkei** [coteditor/CotEditor#384]
## 環境 

- CotEditor: 2.1.3 (2.1.3)
- システム: OS X バージョン 10.10.3（ビルド 14D136）
- 言語環境: 日本語

## 簡単な説明

**icalendar形式**のシンタックススタイルはありませんか？
RFC5545に規定されている内容を全部網羅すると大変そうなので、主立ったものだけでいいんですが。
例えば、ちょっと古めですけど以下のURLぐらいの内容で。
http://www.asahi-net.or.jp/~CI5M-NMR/iCal/ref.html

あと、**BEGIN**,**END**が入れ子になっているのに対応できれば言うことありません。

以上、よろしくお願いします。

**Comment by 1024jp** [comment]
なるほど、面白そうですね icalendar 形式。
まずの質問の答えとしては「ありません」という回答になります。

ただ、個人的に興味があるので、数ヶ月内に作ってみようかと思います。
作った際にそれをデフォルトスタイルのひとつとして CotEditor.app に同梱するか、追加スタイルという形で個人的に配布するかは、ちょっとまだ未定ですが。
icalendar 形式がどの程度普及しているかに寄りますが、感覚的にはそんなにニッチなものでもないように思うので同梱してもいいかもしれません。


-- 
Currently, there is no syntax style for the icalendar format.

However, because I'm personally interested in the format, I'll make it anyway in the next months.
I'm not sure whether I'll put the style into CotEditor.app as one of the default styles or distribute it personally.
It depends on how popular the format is.

**Comment by 1024jp** [comment]
遅くなりましたが、作成しました。
CotEditor 2.3.0 で本体に同梱される予定です。
