### ISSUE TITLE
Syntax highlighting only works via file extensions, not file contents

### ISSUE THREAD

**Issue by BonzaiThePenguin** [coteditor/CotEditor#385]
HTML files containing PHP, JavaScript, and CSS only have the HTML highlighted, since the highlighting works based on the file extension rather than file contents. If I add the `html` extension to the CSS options in the Preferences, it only applies the highlighting to the inline CSS and none of the HTML.

**Comment by 1024jp** [comment]
On CotEditor, a single document can have only a single highlighting style. And currently, we don't have any plan to implement multiple highlighting styles for a single document parsing content because of the performance issue, the time restriction for developing, very low priority, and so on.

Well, you can also switch the highlighting style via toolbar menu or menu bar after opening the file, if you wanna focus to edit a section written in another language.
