### ISSUE TITLE
Print in vertical layout

### ISSUE THREAD

**Issue by Winebear** [coteditor/CotEditor#386]
Currently it support vertical text input, however, when we want to print out, the format changes to horizontal. Hope it can keep the layout as what we see on screen.

Also supporting PDF saving and keep the vertical layout as well.

Many thanks.

**Comment by 1024jp** [comment]
Thanks for the request.

Actually, we have a plan to implement vertical layout.
However, it probably takes time to be implemented because of some historical reasons. I can't say at this moment when it will be supported, but it will not be a distant future.

For PDF export, OS X support it natively in the print panel. So we will not add an extra "Export as PDF..." action in the menu. If CotEditor supports vertical layout printing, it means at the same time CotEditor supports vertical layout PDF exporting.

**Comment by Winebear** [comment]
Thanks for the reply. Hope to see that in next release :)
