### ISSUE TITLE
`#` in code block will be treated as headers in outline menu

### ISSUE THREAD

**Issue by gogozs** [coteditor/CotEditor#391]
## 环境

- CotEditor: 2.1.3 (2.1.3)
- 系统: OS X 版本 10.10.3（版号 14D136）
- 语言: 简体中文

## 简单描述

`#` in code block will be treated as headers in outline menu, when editing markdown file.

## 重现问题步骤
edit a markdown file.

\```objc
#import "XYZPerson.h"

\```
![2015-06-28 1 20 59](https://cloud.githubusercontent.com/assets/3871341/8395261/8db2c17a-1d98-11e5-8a05-f2fbf533900e.png)

## 期待结果
treated as code, not headers.

**Comment by 1024jp** [comment]
Thanks for the feedback.
I understand your problem.
However, it is actually hard to resolve it due to implementation limits. To fix it, we need to change not only with Markdown style setting but also the fundamental structure of the syntax highlighting engine itself.
Therefore, I cannot say that it will be resolved in the near future.

**Comment by gogozs** [comment]
I understand that.
2015年6月29日 下午11:56于 "1024jp" <notifications@github.com>写道：

**Comment by 1024jp** [comment]
I suppose this enhancement may not make cense, since there is often a situation in which comment lines are used to put outline anchor, and CotEditor cannot distinguish commented-out headings from such case.

Hence, at the moment, I will not accept this. Sorry for that.
