### ISSUE TITLE
Not able to resize the window on dragging on OS X 10.8 and 10.9

### ISSUE THREAD

**Issue by solidcolour** [coteditor/CotEditor#402]
If you move the mouse cursor to the right edge of the main editor window area (not the toolbar/status bar), and start dragging, it seems that it triggers the split view rather than resize the window. I thought it is the correct behavior until I tried it out on OS X 10.10 (it is for window resizing).

**Comment by 1024jp** [comment]
Actually, this is in the specifications. Apple changed the behavior of such split views on OS X 10.10.
I suppose the behavior on 10.10 is more natural and better, but at the same time, I don't wanna wast my limited develop time to look for the workaround code in order to improve such behavior on the old operation systems which are going to be dropped in the future. 
Therefore we implemented it as is.

**Comment by solidcolour** [comment]
To clarify, it's not split view, it's kind of like a document inspector, attached an screenshot when drag the right edge towards left hand. Well, if that is the right behavior then I suppose that it went wrong on OS X 10.10, in the other words it gets corrected accidentally. Anyway, I have no further comments if you believe continuing support previous OS versions is wasting your time.  

![screen shot 2015-07-27 at 4 08 05 pm](https://cloud.githubusercontent.com/assets/1742906/8916469/cc0967c4-3479-11e5-9c51-1a85fe6fe604.png)

**Comment by 1024jp** [comment]
Oops, sorry, such a component that separates a view into two (or more) sections is called "split view" in OS X development. It has no relationship with CotEditor's split view (split editor) feature. Sorry for my unclear explain.

Anyway, I'll examine it later again whether there is a easy solution for the previous operation systems.
Thanks for pointing it out.

**Comment by solidcolour** [comment]
No worries, sorry for not making it clear in the first post. Let me know if you need any further clarification.
