### ISSUE TITLE
Sessions or Reopen Windows from Last time

### ISSUE THREAD

**Issue by madebyjeffrey** [coteditor/CotEditor#463]
In lieu of a useful project management or file management feature, an almost equally useful feature would be to remember the windows open when you close the program and reopen them next time.

**Comment by 1024jp** [comment]
On the next version 2.3.0 that will be released in this November, CotEditor start supporting the Auto Saving.

It means, if you combine:

- Auto Saving on CotEditor
- Turning off "Close windows when quitting an app" checkbox in the General pane in the System Preferences<br/>
    ![screen shot 2015-11-05 at 18 18 03](https://cloud.githubusercontent.com/assets/1165044/10964290/975ab43c-83e9-11e5-9c56-41fecccf583c.png)

you will be able to resume last session on the next launch.

However it means at the same time:

- You need to change the behavior for all apps.
    - Actually, you can change the behavior only for CotEditor setting it via `defaults` command in Terminal.app.
- It is still impossible to resume last session without enabling Auto Saving.

Thus, when you are going to turn on the Auto Saving on CotEditor 2.3.0, your wish will come true soon.
Otherwise, well, I need to work with code. I'm actually interested in this feature, but still considering what the best way is, or in the first place whether I should add the setting option for this to CotEditor, even the system itself has the option for this behavior.

**Comment by groovyd** [comment]
Wondering when this version with restore of open files will be released?  I badly need this feature.

**Comment by 1024jp** [comment]
You can already set it in the __System Preferences__ (not CotEditor's preferences).

However, if you mean window restoring without auto-saving, I currently don't have any plan. Furthermore, I still doubt whether CotEditor should have its own setting although the System has a more general one.

**Comment by groovyd** [comment]
I don't see a setting in System Preferences to restore CotEditor open documents on launch?  I don't want every app on the computer to do this, just CotEditor.  Auto-save is also fine but that is a separate issue.

**Comment by 1024jp** [comment]
Well, ok, I'll consider.

**Comment by 1024jp** [comment]
note:
- `NSCloseAlwaysConfirmsChanges`
- `NSQuitAlwaysKeepsWindows`

**Comment by 1024jp** [comment]
I've added “Reopen windows from last session on launch” (the name can be changed) option to CotEditor 3.3.0, which is planned to be released in the next spring 😉.

<img width="662" alt="screen shot 2017-11-26 at 19 09 03" src="https://user-images.githubusercontent.com/1165044/33239056-68f10f02-d2dd-11e7-8a93-e25b9fd38ae6.png">

**Comment by groovyd** [comment]
Thanks!  Mind if I test the beta until then ?

**Comment by 1024jp** [comment]
@groovyd I normally release betas at [beta distribution page](https://coteditor.com/beta) every time before releasing a minor update. Currently, I provide no beta yet since the main features of 3.3.0 have not been implemented yet. A release of a beta version will be announced on the [beta page](https://coteditor.com/beta) and [CotEditor's Twitter account](https://twitter.com/CotEditor)

If you even wanna try the latest one with this feature from right now on, build the end point of the development branch by yourself. It's open source.
