### ISSUE TITLE
2.3.3導入後「⌘/」によるコメントアウトができなくなりました。/ Comment-out doesn't work on 2.3.3

### ISSUE THREAD

**Issue by tomg25** [coteditor/CotEditor#489]
## 環境 

- CotEditor: 2.3.3 (91)
- システム: OS X バージョン 10.11.2（ビルド 15C50）
- 言語環境: 日本語

## 簡単な説明

2.3.3導入後「⌘/」によるコメントアウトができなくなりました。
試しに2.3.2に戻すと問題なく動作します。

## 不具合が発生したときに行っていた操作、または再現手順

html, css, phpなど、どのファイル形式でも同様です。

## 期待される挙動

動作の正常化です。

**Comment by 1024jp** [comment]
アァ、本当ですね。報告ありがとうございます。
なんでだろう。修正して今月中に新しいバージョンを出します。

**Comment by tomg25** [comment]
1024jpさま、いつもお世話になりありがとうございます。
どうぞよろしくお願いします。

**Comment by 1024jp** [comment]
たった今この修正を含む CotEditor 2.3.4 を App Store に提出しました。

もし何もなければ1週間程度でリリースされるはずです。それまでは不便をおかけしますがご辛抱ください。

報告ありがとうございます。こんな基本的でよく使うコマンドを潰してしまって申し訳ないです。

---

I've just submitted the next version includes the fix for this issue.
If nothing happens by Apple, it will be released in the next week. Please bare with it until that one.
I'm sorry, and thanks for your report.

**Comment by tomg25** [comment]
1024jpさま、いつも迅速なご対応誠にありがとうございます。
今後ともどうぞよろしくお願いします。
