### ISSUE TITLE
Feature Request... Hide menu bar for distraction free mode.

### ISSUE THREAD

**Issue by jeffmikels** [coteditor/CotEditor#528]
I recently learned of this setting in the Info.plist file:

```
<key>LSUIPresentationMode</key>
<integer>4</integer>
```

By using that setting, the app runs with no visible system menu bar. I tried editing the Info.plist of CotEditor and I got an error that the app had been corrupted, so apparently, I can't make this change myself. Could this be added as an option to the settings? Or alternatively, is there a way to switch the menubar on and off with a keyboard shortcut?

**Comment by 1024jp** [comment]
As you mentioned, users cannot modify the info.plist in a sandboxed app. On OS X El Capitan and later, there is a global option "automatically hide and show the menu bar" in the General preference. So, use it instead of setting it in a hacky way. CotEditor will not add an original option for it.

![screen shot 2017-01-14 at 16 47 56](https://cloud.githubusercontent.com/assets/1165044/21953408/3c108ea2-da79-11e6-926a-7f5d7244775a.png)
