### ISSUE TITLE
Italian localization

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#608]
@AgostinoM offered us to localize CotEditor to Italian and we're now working together. So far, we contacted each other by e-mail, however I suppose it's now easier do it on GitHub because we can mix text and images or codes easily on this Issues.

So, this issue is the working space for the Italian localization.

**Comment by 1024jp** [comment]
@AgostinoM, Thank you for your hard work. Here is the list of the additional work based on the it.lproj folder I've got.

Please localize the followings additionally and post as a comment on this page. Or feel free to ask me if you have any questions.

## Additional localization for strings that were added on CotEditor 3

The list of strings that were added on CotEditor 3.0 after CotEditor 2.5.x.
So, please localize the followings.

### Advanced find options on the find panel

![screen shot 2016-09-28 at 18 34 59](https://cloud.githubusercontent.com/assets/1165044/18908352/4602ba26-85aa-11e6-8d38-b2c31ed5048d.png)

```objc
"Distinguish characters strictly"
"Exact character-by-character equivalence."  // tooltip description

"Ignore diacritic marks"
"Search ignores diacritic marks (ex. ö = o)."  // tooltip description

"Ignore width differences"
"Search ignores width differences in character forms (ex. ａ = a)."  // tooltip description

"Regular Expression Search"

"Dot matches line separators"
"Allow . to match any character, including newline characters (singleline)."  // tooltip description

"Anchors match lines"
"Allow ^ and $ to match the start and end of lines (multiline)."  // tooltip description

"Use Unicode word boundaries"
"Use Unicode TR#29 to specify word boundaries"  // tooltip description

"Unescape replacement string"
"Unescape meta characters with backslash in replacement string."  // tooltip description
```


### Go To panel

![screen shot 2016-09-28 at 18 38 31](https://cloud.githubusercontent.com/assets/1165044/18908498/c6ae9d7a-85aa-11e6-970c-b644b0935645.png)

```objc
"Line Number"  // placeholder of the Go To field
```

### Main menu items

```objc
"New Tab"

"Toggle Comment"
"Inline Comment"
"Block Comment"

"Insert IANA Charset Name"
"Insert encoding name as IANA charset"
```

### Localizable.strings

```objc
// undo action name
"Line Endings to “%@”"

// error message for file encoding reinterpretation
"The document doesn’t have a file to reinterpret."

// error message on modifying user setting files
"No original file for “%@” was found."

// error message heading
"Regex Error: %@"

// error messages for key-bindings setting
"Single type is invalid for a shortcut."
"Please combinate with another keys."

// error messages for macros
"No document to get input."
"No document to put output."
```

### Unicode

```c
"a letter consisting of %d characters"
// The background of this sentence:
// In computer world, some apparent single letters are actually built from multiple Unicode characters.
// For example, the emoji letter 🇮🇹 actually consists of two Unicode characters with codes U+1F1EE and U+1F1F9.

// Variation selectors
"Emoji Style"
"Text Style"
"Skin Tone I-II"
"Skin Tone III"
"Skin Tone VI"
"Skin Tone V"
"Skin Tone VI"
"Variant"

// placeholders
"No Block"
"No Category"
// The terms "block" and "category" (and also "variant" above) here are the specific terms on Unicode. So please refer some documentation about Unicode.
```



## Strings to be shorten

Because of the limitation of the space, some labels must have a shorter sentence than the sentence that @AgostinoM originally localized.
Please make the following strings a bit shorter than the original. Or tell me if you really need an additional space to display the whole message (namely, if there is no better translation).

### toolbar item label on Preferences

![screen shot 2016-09-28 at 18 56 20](https://cloud.githubusercontent.com/assets/1165044/18909110/497598ce-85ad-11e6-9ef7-04b7857d16aa.png)

```c
"Key Bindings"
// currently: "Abbreviazioni da tastiera"
```
note: if you really hard to shorten this words, try using the following strategies:

- abbreviate a word using ".". 
    - For example on German localization, I use "Tastenbeleg." for "Tastenbelegungen"
- localize the word "shortcut" instead of "Key Bindings".
    - Then, we need to change all of "key bindings" in the app to "shortcut".


### Preferences -General Pane

![screen shot 2016-09-28 at 18 48 21](https://cloud.githubusercontent.com/assets/1165044/18908832/28842190-85ac-11e6-86a1-aceb3f961e1a.png)

```c
"Trim trailing whitespace on save"
// currently: "Rimuovi gli spazi bianchi a fine riga quando si salva il documento"

"Inline script menu items into contextual menu"
// currently: "Quando il documento è modificato da un’altra applicazione:"
```

### Preferences - Window Pane

![screen shot 2016-09-28 at 19 09 58](https://cloud.githubusercontent.com/assets/1165044/18909602/3134433a-85af-11e6-83b2-0ade87be2fec.png)

```c
"Status bar shows:"
// currently: "La barra di stato mostra:"
// or use just "Status bar:" instead of "Status bar shows:" if there is no enough space.

"Line Count"
// currently: "Conteggio righe"

"Char Count"
// currently: "Conteggio caratteri"

"Editor opacity:"
// currently: "Trasparenza dell’editor:"
// I'd like just to ask whether the word "trasparenza" is correct in this context.
// Because at least in English, the terms "transparency" and "opacity" are different.
// - 100% transparent means: the object is invisible.
// - 100% opaque means: the object is visible.
```


### Syntax style editor

![screen shot 2016-09-28 at 18 57 27](https://cloud.githubusercontent.com/assets/1165044/18909145/6e04e8c0-85ad-11e6-852a-8cc4b0c516a6.png)


```c
"(blank matches the whole string)"
// currently: "(Per corrispondenza con l’intera stringa: lasciare in bianco)"
```

I think it's better than to shorten "Motivo del menu del titolo".

**Comment by AgostinoM** [comment]
Hello,

here you are. 

---

****Advanced find options on the find panel

"Distingui i caratteri con precisione"
"Equivalenza assoluta dei caratteri."  // tooltip description

"Ignora segni diacritici"
“La ricerca ignora i segni diacritici (es. ö = o)."  // tooltip description

"Ignora le differenze di ampiezza"
“La ricerca ignora le differenze di ampiezza nei caratteri (es. ａ = a)."  // tooltip description

“Ricerca espressioni regolari"

“Il punto vale come separatore di riga"
“Consente al . di equivalere a qualunque carattere, anche quello di nuova riga (singola)."  // tooltip description

“Le Anchors valgono come righe"
“Consente a ^ e $ di valere come inizio e fine riga (multipla)."  // tooltip description

"Usa Word Boundary Unicode"
"Usa Unicode TR#29 per specificare i Word Boundary"  // tooltip description

“Stringa di sostituzione Unescape"
“Metacaratteri Unescape con backslash nella stringa di sostituzione."  // tooltip description




**** Go to panel


“Numero riga"  // placeholder of the Go To field
// If it’s too long, you can use “N.ro riga”



*** Main menu items

"Nuovo pannello"

“Attiva commento"
"Inserisci commento"
"Blocca commento”

"Inserisci nome set di caratteri IANA"
"Insert il nome della codifica come set di caratteri IANA"

*** Note: if the word “caratteri” is too long, you can use    “car. ”



**** Localizable.strings

// undo action name
“Termine riga a “%@”"

// error message for file encoding reinterpretation
“Il documento non ha un file da reinterpretare."

// error message on modifying user setting files
“Nessun file originale trovato per “%@”."

// error message heading
“Errore Regex: %@"

// error messages for key-bindings setting
“Un solo tasto non è una scorciatoia valida."
“Si prega di abbinarlo ad altri tasti."

// error messages for macros
"Nessun documento da cui ottenere dati."
"Nessun documento dove salvare il risultato."


**** UNICODE

“una lettera composta di %d caratteri"
// The background of this sentence:
// In computer world, some apparent single letters are actually built from multiple Unicode characters.
// For example, the emoji letter 🇮🇹 actually consists of two Unicode characters with codes U+1F1EE and U+1F1F9.

// Variation selectors
“Stile Emoji"
“Stile Testo"
“Tono pelle I-II"
“Tono pelle III"
“Tono pelle VI"
“Tono pelle V"
“Tono pelle VI"
"Variante”

// placeholders
"Nessun Blocco"
"Nessuna Categoria"
// The terms "block" and "category" (and also "variant" above) here are the specific terms on Unicode. So please refer some documentation about Unicode.



**** STRINGS TO BE SHORTENED

**Toolbar item label on Preferences

"Key Bindings"
// currently: "Abbreviazioni da tastiera"
//** You may alternatively use “Abbrev. da tast.”

** Preferences -General Pane
"Trim trailing whitespace on save"
// currently: "Rimuovi gli spazi bianchi a fine riga quando si salva il documento"
//** You can use: “Elim. spazi a fine riga al salvataggio”

"Inline script menu items into contextual menu"
// currently: "Inserisci gli elementi del menu degli script nel menu contestuale"
// ** You can use: "Inserisci menu degli script nel menu contest."


** Preferences - Window Pane
"Status bar shows:"
// currently: "La barra di stato mostra:"
// or use just "Status bar:" instead of "Status bar shows:" if there is no enough space.
// ** You can use: “Barra di stato:”

"Line Count"
// currently: "Conteggio righe"
// ** You can use: “N.ro righe”

"Char Count"
// currently: "Conteggio caratteri"
//** You can use: “N.ro caratteri”, or “N.ro caratt.”

"Editor opacity:"
// currently: "Trasparenza dell’editor:"
// I'd like just to ask whether the word "trasparenza" is correct in this context.
// Because at least in English, the terms "transparency" and "opacity" are different.
// - 100% transparent means: the object is invisible.
// - 100% opaque means: the object is visible.

// also in a menu item title in the main menu
"Set Editor’s Opacity…"
// currently: "Imposta la trasparenza dell’editor…"
// You might use “opacità” instead of “trasparenza”. But usually, in Italian language, we never use the word “opacità” when talking about the opacity/transparency level of an element. The only “opacity” I have seen is in the Photoshop levels. :-) 

** Syntax style editor
"(blank matches the whole string)"
// currently: "(Per corrispondenza con l’intera stringa: lasciare in bianco)"
// You can use: “Non compilato: intera stringa”. A little cryptic, but it should be ok.

**Comment by AgostinoM** [comment]
> I think it's better than to shorten "Motivo del menu del titolo".

You might use "Motivo menu titolo".

**Comment by 1024jp** [comment]
@AgostinoM Thank you a lot.

We'll soon release a release candidate of CotEditor 3.0 that includes your Italian localization.
When it released, please check it all through and tell me here if there is any strange thing.

**Comment by AgostinoM** [comment]
Good.
I've just spotted a mistake, here:

"Insert il nome della codifica come set di caratteri IANA"

That INSERT should be INSERISCI

**Comment by 1024jp** [comment]
>> "Trim trailing whitespace on save"
>> // currently: "Rimuovi gli spazi bianchi a fine riga quando si salva il documento"
>
> //** You can use: “Elim. spazi a fine riga al salvataggio”

I combined your new suggestion and the original translation and put "Rimuovi gli spazi bianchi a fine riga al salvataggio" on the checkbox. I hope this sentence make a sense.

> You might use “opacità” instead of “trasparenza”. But usually, in Italian language, we never use the word “opacità” when talking about the opacity/transparency level of an element. The only “opacity” I have seen is in the Photoshop levels. :-)

I've googled the term “opacità” and found that people use it as a term to represent English “opacity”. So, I preferred to use “opacità” to make more clearly (and to reduce the space a bit ;-P ).

**Comment by 1024jp** [comment]
> I've just spotted a mistake, here:
>
> "Insert il nome della codifica come set di caratteri IANA"
> 
> That INSERT should be INSERISCI

Ok, I'll fix it now.

**Comment by 1024jp** [comment]
> "Key Bindings"
> // currently: "Abbreviazioni da tastiera"
> //** You may alternatively use “Abbrev. da tast.”

Unfortunately, “Abbrev. da tast.” was still bit too long, so I used just the term “Abbreviazioni” instead.

In addition to that, I also changed some strings from your original translation to make them the same as Apple's localization (mainly menu items in the menu bar menu).

**Comment by AgostinoM** [comment]
I see. How about

Abbrev. tast. 

?

**Comment by 1024jp** [comment]
> I see. How about
> 
> Abbrev. tast.

Aha, It also works.

I used “Abbreviazioni” because I saw it also in the system preferences.

![screen shot 2016-09-29 at 19 50 44](https://cloud.githubusercontent.com/assets/1165044/18951101/28e4cfa4-867e-11e6-947f-ea794eead1cc.png)

In this situation, this “Abbreviazioni” is the localization of English “Shortcuts”, however the function of the pane is actually the same as CotEditor's one. Therefore it makes sense.
Generally speaking, I suppose full spell-outed words are better than abbreviated words.
And Apple also suggest not to use abbreviation as possible.
I feel both two words are abbreviated is kind of too much.

How do you think? I respect your decision as I don't now how abbreviation is usual in Italian.

**Comment by AgostinoM** [comment]
"Abbreviazioni" is fine:-)

**Comment by 1024jp** [comment]
@AgostinoM Thanks 🐈

**Comment by 1024jp** [comment]
We've released CotEditor 3.0.0-rc on <https://coteditor.com/beta>. It includes your Italian localization.
Please give it a try when you have time and feel free to tell us feedback.

I'm planning to submit the stable CotEditor 3.0 to the App Store in the next week (as long as there is no critical issues any more).
So, it doesn't need to be hurry.

**Comment by AgostinoM** [comment]
Excellent, thanks!

**Comment by 1024jp** [comment]
I'm scheduled to submit CotEditor 3.0 to the App Store on the next Tuesday (4, Oct).
Please tell me if you find any issue about Italian localization until then.

(Of course, It's also ok after that time limit. I'll just include it to the CotEditor 3.0.1 or other)

**Comment by 1024jp** [comment]
CotEditor 3.0.0 is released today on the MAS 🎉.
Again, I appreciate your contribution very much".
I believe it's now easier to use CotEditor for Italian users.

Future plan:
By the future releases, I'll make an issue page every time when additional localizations are required and call you with @ in the issue (Just as I did in this issue page).
Please pay attention to such notifications from GitHub.
Or just tell me If you become busy and therefore have no time any more to take care of CotEditor's Italian localization.

**Comment by AgostinoM** [comment]
Okay, excellent! Have a nice day.
