### ISSUE TITLE
[highlight] Simple quote char (') breaks PHP syntax highlight

### ISSUE THREAD

**Issue by lapinos03** [coteditor/CotEditor#619]
Presence of a simple quote on a comment line breaks the syntax highlight in PHP code :
![coteditor_v3 0 1_php_wrong_syntax_highlight](https://cloud.githubusercontent.com/assets/891923/19300948/46b14b64-905d-11e6-8b54-40205438919e.png)
Version 3.0.1 (161)

**Comment by 1024jp** [comment]
Thanks for the feedback.
I understood your matter. I'll consult on it.


--- 

### test code

```php
<?php

# Comment
echo "Hello!";

# Comment with simple quote'jjsdkmdjq
echo "Hello!";
# syntax highlight it wrong
```

**Comment by Max840** [comment]
I found other cases where this happens:

Here it breaks the parser:
<img width="641" alt="message_error_php_et_untitled" src="https://cloud.githubusercontent.com/assets/2321239/20975406/6c768922-bc6d-11e6-92a5-268c5613e212.png">
But it will not break it if I remove the second quote.
<img width="645" alt="message_error_php_et_untitled" src="https://cloud.githubusercontent.com/assets/2321239/20975436/88855800-bc6d-11e6-86e6-59d0ee4767dc.png">

Breaks also when mixing a single quote and a double quote
<img width="638" alt="message_error_php" src="https://cloud.githubusercontent.com/assets/2321239/20975547/d0faa02c-bc6d-11e6-958e-0be19fda1d3e.png">

Breaks if the quote is inside a tag
<img width="641" alt="message_error_php_et_message_sent_php" src="https://cloud.githubusercontent.com/assets/2321239/20975578/e90cb8f8-bc6d-11e6-92ee-9a7bfc049d0d.png">

The codes I used

```HTML
<title>Title with a ' quote</title>
<p>All the content is considered as a string until ' another quote is inserted</p>
```
```HTML
<title>Title with a ' quote</title>
<p>Random " content</p>
```
```HTML
<title>Title with a ' quote</title>
<script src=""></script>
```

I hope this helps.

**Comment by Max840** [comment]
The bug seems to be coming from the fact that the syntax highlighting system only supports one inline comment delimiter per language.

In [CotEditor/CotEditor/Syntaxes/PHP.yaml](https://github.com/coteditor/CotEditor/blob/develop/CotEditor/Syntaxes/PHP.yaml#L6306) the inline comment delimiter is defined as `//`. However, PHP also supports `#`.

Extracted from PHP.yaml:
```yaml
commentDelimiters:
  endDelimiter: "*/"
  beginDelimiter: "/*"
  inlineDelimiter: "//"
```

I changed the inline comment delimiter to `#` and the quote is correctly ignored.
<img width="639" alt="untitled" src="https://cloud.githubusercontent.com/assets/2321239/20991135/b79fc0c0-bcaa-11e6-80a7-94a667c7c498.png">
And, as expected, the `//` comments now have the quote problem.

I looked into the syntax highlighting code and it cannot accept multiple inline comment delimiters. However, the change seems fairly straightforward.

I would like to work on this bug if that's good for everyone.

**Comment by 1024jp** [comment]
It's all based on the current syntax highlighting mechanism. CotEditor's syntax definition is easy to customize, but it has some weakness in specific situations.

I knew I need to extend the definition format more to solve those issues. Changing definition format must be done carefully. I postponed this so far just because of other high-priority tasks and my limited time resource.

Well, but now, there is no specific issues or goals for next update, CotEditor 3.2. Thus, I'll try working improve the syntax highlighting for next update.  Such a fundamental issue should be resolved before adding other fancy features.

**Comment by 1024jp** [comment]
ref #636.

**Comment by maximeplante** [comment]
Could CotEditor use an already existing format for syntax highlighting? For example, it could use Notepad++'s [userlang definition](http://docs.notepad-plus-plus.org/index.php/User_Defined_Languages) . CotEditor could support a lot of different languages right from the start without having to recreate the grammar files for each language. There is also the Atom Editor which supports a wide variety of languages.
