### ISSUE TITLE
Scripts folder can't be synchronized with Dropbox

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#666]
How can I sync a script folder of CotEditor between two Macs?

I tried:
1. Place a substance of script folder of CotEditor("com.coteditor.CotEditor") on Dropbox.
2. Make a symbolic link of (1) and place it in "Application Scripts" folder.

However, CotEditor couldn't recognize the symbolic link.
Is there any way to sync a script folder of CotEditor?

**Comment by 1024jp** [comment]
Ach, I probably just forgot to follow symbolic links in the scripts folder.
I'll implement it in the next release.
Thanks for your feedback.

**Comment by 1024jp** [comment]
Hmmm, resolving symlinks under a Sandboxed app seems harder than I thought. I'm even not sure if it's possible at the first place.

@tatsy-ymj Is it impossible to flip the direction of the symlink? I mean, create a symlink to `~/Library/Application Scripts/com.coteditor.CotEditor`from the inside of the Dropbox directory. I don't know if it works because I've never used Dropbox before. But I think it is an easier way.

**Comment by umireon** [comment]
> 1. Place a substance of script folder of CotEditor("com.coteditor.CotEditor") on Dropbox.
> 2. Make a symbolic link of (1) and place it in "Application Scripts" folder.

@tatsy-ymj I don't believe such a configuration is possible with Apple's strict security policy.
Users are required to install the script into the application script directory by **hand** to permit the script execution to the application explicitly.
Instead, you can have a synchronization script in Dropbox such as:

```bash
#!/bin/sh
SRCDIR=~/Dropbox/coteditor
DESTDIR=~/"Library/Application Scripts/com.coteditor.CotEditor"
mkdir -p "$DESTDIR"
rsync -rtuv "$SRCDIR" "$DESTDIR"
rsync -rtuv "$DESTDIR" "$SRCDIR"
```

**Comment by tatsy-ymj** [comment]
Thank you for your useful advice! I'll try it.

**Comment by 1024jp** [comment]
It seems I cannot solve this issue as long as CotEditor is Sandboxed. Therefore, I close this.
