### ISSUE TITLE
Syntax style not re-evaluated correctly after saving a  new file

### ISSUE THREAD

**Issue by rovf** [coteditor/CotEditor#668]
I am creating a new file, which therefore has the default syntax style applied ("plain text"). In my case, it is a zsh program, so the first line of the new file is
   
 #!/bin/zsh

Now I'm saving this file under a new name, say: _myscript_

I would have expected, that the syntax style now changes to "shell script", but it doesn't. Only after closing and re-opening the file, the style changes.

**Comment by 1024jp** [comment]
Yes, CotEditor doesn't evaluate the shebang (and also any other document contents) while the file is opened. The syntax style is updated only when the file is newly saved with a known extension. It's currently by design. You need to select a syntax style from the menu manually. 

However, I suppose it is reasonable to evaluate also the shebang when a file is newly saved. I'll implement it.

Thanks for the feedback.
