### ISSUE TITLE
Snippet feature for search / replacement

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#679]
I have a request about search/replace feature.
It is a snippet feature.
If CotEditor has snippet feature, I can choose search/replacement strings sets speedily.
I understand there are plenty of clipboard utilities, but I have to input search strings and replacement separately with these clipboard utilities.

**Comment by 1024jp** [comment]
I have an idea that I want to implement to CotEditor in this year. I can't say at this moment when I can finish it. But it may helps your request. Look forward to it :)

**Comment by tatsy-ymj** [comment]
Thnx! I'm really looking forward to it.

**Comment by 1024jp** [comment]
Sorry, but I'll postpone this feature to CotEditor 3.3.0 because it may take more time than I thought in  the beginning. Since the fundamental functions have been already implemented, I suppose I still can finish it in this year. Actually, I'm just undecided about the user interface of this feature 🤔.

**Comment by tatsy-ymj** [comment]
No problem! I always appreciate your work.

**Comment by masonraycn** [comment]
The search behavior of Notepad++ is pretty good。

**Comment by 1024jp** [comment]
This feature will be added to the next CotEditor 3.4.0.

<img width="575" alt="screen shot 2018-03-31 at 7 36 48 pm" src="https://user-images.githubusercontent.com/1165044/38162371-e02fbc86-351a-11e8-898a-2a30ad77716b.png">
