### ISSUE TITLE
CotEditor crashes on saving in an unmatched encoding

### ISSUE THREAD

**Issue by cenestrien** [coteditor/CotEditor#682]
Thank you very much for the nice text editor! I'm really impressed by CotEditor's vertical text mode.

## Environment

- CotEditor: 3.1.5 (184)
- System: macOS Version 10.11.6 (Build 15G1217)
- Language: English

## Short Description

CotEditor crashes when saving a document window containing a character not supported by the chosen encoding.

## Steps to Reproduce the Issue

1. Open an new document window;
2. Set the encoding to Shift_JIS [or ISO Latin 1];
3. Type a non Shift_JIS character , for example, 剝 (U+525D)  [or an non-ISO Latin 1 character, for example, œ (U+0153) ];
4. Save.

## Expected Result

CotEditor will not crash ;-) **_and_** will show character(s) not supported by the chosen encoding and show the encoding(s) supporting all the characters in the current document.

**Comment by 1024jp** [comment]
Finally, I could reproduce this crash!

Since I saw this kind of crash in anonymous crash logs several times, I've been working on this issue for a long while but couldn't reproduce it so far. Because the anonymous crash log has poor information.
Now with your report, I did it. When a bug can be reproduced, it may be going to be fixed soon.

I appreciate you a lot.

**Comment by 1024jp** [comment]
Fixed. I'll release a patch version including this fix within few days.

**Comment by cenestrien** [comment]
Wow! Thank you very much for the quick fix.
