### ISSUE TITLE
TextEdit can not open CotEditor RTF files

### ISSUE THREAD

**Issue by jpietrangelo** [coteditor/CotEditor#685]
On MacOS 10.12.3 (Sierra) TextEdit will not open Rich Text Format files created with CotEditor (version 3.1.6. 

Likewise, when CotEditor opens a Rich Text Format file created in TextEdit the file will open, but with code/metadata displayed.

TextEdit file attached.

[test2.rtf.zip](https://github.com/coteditor/CotEditor/files/814521/test2.rtf.zip)

**Comment by 1024jp** [comment]
CotEditor's Rich Text Format syntax style can just highlight raw Rich Text file that is normaly created with other applications. Since Rich Text Format is actually a kind-of text file containing the style information also as text data (cf. [Human Readability of Rich Text Format](https://en.wikipedia.org/wiki/Rich_Text_Format#Human_readability)), some developers want to read the source code with syntax highlighs. (If you open a RTF file created with TextEdit.app in CotEditor, you may understand what I'm talking about.)

CotEditor's RTF sytnax style is generally designed to help readind or modifying existing RTF source code. Not to create a RTF file. CotEditor is a plain-text editor. Therefore, it doesn't create RTF code.

**Comment by jpietrangelo** [comment]
Well that explains it well. Thanks for the quick reply.
