### ISSUE TITLE
coteditor consider files locked but not Textedit

### ISSUE THREAD

**Issue by michel4638** [coteditor/CotEditor#688]
Hello,
I work on macOS Sierra 10.12.2, and I use coteditor. I have now plenty of files coteditor consider as locked, but textedit can read and write on these files. The rw access under Unix is correct, and commands as sudo chflags -R noschg *, not efficient.
What' s happening ?

BR.

Michel Froidevaux

**Comment by 1024jp** [comment]
Is this the same problem talked in the following issue?
[Cannot open document due to incorrect permission error](https://github.com/coteditor/CotEditor/issues/674)

If so, I suppose this is actually a kind of bug by Apple. I have no idea so far how I can fix it.

However to collect more information of this isusue I'd like ask you:
- Do you use `cot` command or something command-line to open the file faced to this issue?

**Comment by michel4638** [comment]
Hello,

-The problem I have leads effectively to the same "kind of" pop-up, with a message slightly different, saying "File xxx is locked do you want to create a copy".
-This morning, all the files considered as locked by apple/coteditor are now working fine ?!
-To open the files I use the finder, not the command line,

I effectively consider this issue as being an apple/coteditor pb, fixed by the logout of yesterday. As textedit was able to open files, and as the problem was effective on some files, but not all, I am more thinking the pb comes from internal data structures of coeditor, not correctly reset. And this reset has been done by the logout. If this pb occurs again, I will try to restart the session.

You may consider the pb as closed.

BR

**Comment by 1024jp** [comment]
Thank you for sharing your additional information and I close this as it's duplicate.

As you mentioned, the access permission of the file is not actually changed but just CotEditor strangely begins to think at some time point it's locked.
