### ISSUE TITLE
Trouble scrolling to end of Markdown document

### ISSUE THREAD

**Issue by alanorth** [coteditor/CotEditor#742]
I have an issue where I open a Markdown file `todo.md` with about 400 lines, but I'm not able to scroll to the end of the document (only about half way). Interestingly, if I select all, copy, and paste into a new document, all the lines are there. Also, if I switch to vertical orientation I can see all the lines, and when I switch back to Horizontal again I can see more lines (though not all of them).

I'm using CotEditor 3.2.3 on macOS 10.13.1 Beta (17B45a) with APFS. I've been hitting this bug for a few weeks, and now that I think of it, it could be due to the High Sierra / APFS upgrade?

**Comment by 1024jp** [comment]
Thank you for the report.
I guess this issue is the same as #736 (Hence, #736 was not fixed in CotEditor 3.2.3, unlike I hoped).

It means that the APFS plays no role by this bug. The file itself is read correctly to memory (I suppose) but something about view layout calculation was changed on High Sierra.

Anyway, I have to fix this.

**Comment by 1024jp** [comment]
I’d close this issue as it’s duplicated. I’ll reopen the original #736.
