### ISSUE TITLE
Displaying outline menu with a shortcut key

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#756]
CotEditor has a feature to jump a previous/next outline item.
Adding to it, I want CotEditor to have a feature which displays outline menu with a shortcut key to select items more easily!

**Comment by 1024jp** [comment]
Thank you for the feedback.
I've been thinking several years about what if CotEditor has an outline menu in the sidebar.
Then, users can select from leaving the menu open, seeing temporally with an action, or ignore all the time.
Opening the existing menu with a shortcut may be easy to implement; however, opening a menu in this way appears not to be recommended for a Cocoa application.

My idea is still in the conceptual stage because of other things I need to implement first.
But, I feel now your request is +1 for this idea.
I'll consider.

**Comment by tatsy-ymj** [comment]
> I've been thinking several years about what if CotEditor has an outline menu in the sidebar.
I was using WZ Editor on Windows because its outline side bar was very convenient. (I'm not sure about its present version)
http://www.wzsoft.jp/wza/outlin.htm

I understand implementing outline menu needs much cost, but I'm looking forward to it.

**Comment by andylima** [comment]
> I've been thinking several years about what if CotEditor has an outline menu in the sidebar.

Yes. Love this idea!

**Comment by 1024jp** [comment]
Finish implementation.
This feature will be added to CotEditor 3.4.0.

![screen shot 2018-03-06 at 14 11 17](https://user-images.githubusercontent.com/1165044/37015120-441c8058-2148-11e8-9a51-dc41616b9024.png)

**Comment by yoshihirotameike** [comment]
I appreciate the wonderful and easy to use editor.

Now, the sidebar shows the outline hierarchy, and the whole thing is easy to see and use.

To make it even easier for cultural researchers to use coteditor, could you add the following features to the outline sidebar display?

1)Collapsible (It makes it easier to see the chapters, sections and connections.)
2)You can set the item color for each hierarchy.

I often write long papers, so if I have this function, I think I will be able to read papers while looking at the whole.

I am sorry for all the requests, but I would appreciate your consideration.

**Comment by 1024jp** [comment]
@yoshihirotameike 
Thank you for the feedback.
First, it's better to create a new issue for a new request.
So, I've created one (#1080) for your request and will write the current answer and future updates there.
