### ISSUE TITLE
Files do not open in a tab in fullscreen mode

### ISSUE THREAD

**Issue by Andrew1X** [coteditor/CotEditor#757]
## Environment

- CotEditor: 3.2.7 (212)
- System: macOS Version 10.13.2 (Build 17C88)
- Language: English

## Short Description

When the editor is in fullscreen mode, double-clicking a file from the Finder always open in a new window even with _Prefer tabs: Always_ selected.

## Steps to Reproduce the Issue

Open CotEditor
Click top-left green icon to activate fullscreen
Go to Finder
Double-click a file

## Expected Result

The file should open in a new tab within the first CotEditor window.

**Comment by 1024jp** [comment]
Thank you for the feedback.
But I have to say; this behavior is in spec.

I studied again with some document-based applications by Apple (e.g.: Pages.app) with the option "Always" and confirmed that Apple treats a new document in the same way.
CotEditor is aimed at behaving in the macOS manner.
Hence, I'd say this is the correct behavior.

I personally understand it's kind of what you expected with the label "Always."
However, because of the reason, I let it be.
