### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by bluemix** [coteditor/CotEditor#759]
Hello dears,
will it supports align right? 

and thank you for this cool editor.

**Comment by 1024jp** [comment]
Like this?

<img width="972" alt="screen shot 2018-01-17 at 7 56 52 pm" src="https://user-images.githubusercontent.com/1165044/35039254-a47bd654-fbc0-11e7-8d15-9e52486895ef.png">


I've just quickly implemented the option changing the text alignment.

However, since I don't speak any RTL languages, I'm not sure whether this is correct and fulfill your guys needs.

My current question is:
Which option is better for RTL languages: text alignment  (the current implementation) vs. writing direction?
(You can see the difference between them in TextEdit.app's Format > Text.)

I'll release a beta version of the next CotEditor 3.3.0, which support this feature, at the end of January or begin of the February. So, please review it and give me feedback.

**Comment by bluemix** [comment]
Actually, and in order to avoid confusion, in the **Format** menu, **Text** item should now have two options: _Direction_ -> Left-to-right (LTR) | Right-to-left (RTL) options; as well as _Alignment_ => Left | Center | Right.

> Which option is better for RTL languages: text alignment (the current implementation) vs. writing direction?

Both. The alignment and writing direction can be chosen from the menu according to the user needs of the selected lines or paragraphs. Sometimes I write mixed RTL and LTR texts, and if VS Code or Sublime supports alignment, neither supports RTL direction. As far as I know, if this feature implemented, this will be the first (after the TextEdit) GUI-based editor that truly supports RTL languages on macOS.

**Comment by 1024jp** [comment]
Thank you for answering my question. I understood the situation of the RTL writing.

> Alignment => Left | Center | Right

IMO, the centring alignment is less important than other light or left ones. So, I'll definitely not implement it because it's also practically hard for a code editor. For example, to calculating indent positions or drawing a page guide.

> The alignment and writing direction can be chosen from the menu according to the user needs of the selected lines or paragraphs.

Applying a style information, such as alignment, to a part of a document exceeds a function of a plain-text editor. A plain-text editor should handle documents as a plain-text even while editing on it. Therefore, CotEditor should only apply the alignment (or writing direction) option to the entire document.

Honestly speaking, I’m going only to implement either the alignment or the writing-direction. Sorry for such limitations.
So then, if CotEdtior needs to choose only one from them, which do you prefer?
Observing the TextEdit.app's implementation, TextEdit offers only the writing-direction option when the document is a plain-text. From this point of view, the writing-direction seems more important than alignment. Is it correct?

---

*Considerable compromise*: CotEditor may be able to implement applying writing-direction partly just like TextEdit.app does in the plain-text mode. That is, the direction of specific lines (namely, not "selection" one in TextEdit but "paragraph" one) becomes RTL only while editing in CotEditor, and such information is removed when the document is saved to a file, duplicated, or restored from a modification by another process. So, if you reopen the file next time, all text is aligned to a single side. However, I feel this implementation is kind of insufficient and, therefore, should be avoided.

**Comment by bluemix** [comment]
Ok, I completely agree with your arguments.

>  So then, if CotEdtior needs to choose only one from them, which do you prefer?

Writing direction, as you said, because, it is more important and necessary than text alignment.
Thank you for your explanation and the work on this project :)

**Comment by 1024jp** [comment]
Thank you for the advice.
This feature will be added to CotEditor 3.3.0, which will be released (probably) in this February.

**Comment by 1024jp** [comment]
Today, I released a beta version for CotEditor 3.3.0 at [coteditor.com/beta](https://coteditor.com/beta).
It would be helpful if you try it and give me feedback about the RTL whether it works correctly.

**Comment by bluemix** [comment]
@1024jp i tested it against some of my Arabic articles, and it worked perfectly for me.

TextEdit was having a problem when setting the RTL,  where it changes characters to the equivalent one of the language. For example, it was using a different character code for the hash (#) that it is used in the normal English, and caused problem when rendering the markdown content.
This issue didn't occur in CotEditor.

There is some suggestion, regarding the RTL, is that, I think, it would be good if line numbers of the editor would be on the right side when text is from right-to-left.
<img width="742" alt="screen shot 2018-01-24 at 09 22 22" src="https://user-images.githubusercontent.com/3332274/35317625-b3110de2-00e8-11e8-888a-cff5136aa37d.png">

And, thank you very much 💯

**Comment by bluemix** [comment]
Another thing I found today, is that, _Syntax Style_ always shows _None_ for any file I open.

<img width="417" alt="screen shot 2018-01-24 at 11 47 03" src="https://user-images.githubusercontent.com/3332274/35322774-8213db3e-00fc-11e8-89cd-b12b64f416ce.png">

**Comment by 1024jp** [comment]
Thank you for testing. I'm glad to hear that it works pretty well.

> There is some suggestion, regarding the RTL, is that, I think, it would be good if line numbers of the editor would be on the right side when text is from right-to-left.

I agree with you. Actually, I already tried to implement it (as well as putting the vertical scroller to the opposite side); however, I found it is much much harder than I thought.
I keep looking for another way, but, I'm not sure if there is another easier way.

Apropos, I'm brushing up the RTL behaviors in CotEditor 3.0.0-beta.2 including adding a toolbar icon for writing direction toggle. I'll release this second beta soon.


> Another thing I found today, is that, Syntax Style always shows None for any file I open.

It seems as if CotEditor failed to read bundled syntax styles for some reason.
Try simply restarting your Mac.
In addition, when it occurs only on CotEditor 3.3.0-beta, download .dmg again, place it somewhere on your computer, then launch CotEditor again.
If the issue still isn't resolved, then please create another issue.

**Comment by bluemix** [comment]
> In addition, when it occurs only on CotEditor 3.3.0-beta, download .dmg again, place it somewhere on your computer, then launch CotEditor again.
If the issue still isn't resolved, then please create another issue.

I restarted my Mac and downloaded it again, and still shows None Syntax Style.
OK, I'll open an issue about it.
