### ISSUE TITLE
File is auto saved when changing encoding

### ISSUE THREAD

**Issue by pedrohex** [coteditor/CotEditor#777]
## Steps to Reproduce the Issue

When editing a file with a different encoding (not sure what), coteditor changes to Japanese (Mac OS) and saves the file automatically. I was editing on a samba share so i was unable to undo my changes.

## Expected Result
Dont save file automatically and it must be possible the use of undo command.

**Comment by 1024jp** [comment]
It seems the document was restored to the file's version because the file contents had been changed by another process.
Then, therefore, the undo history was restored and the file encoding was reinterpreted.

Your choice is:
1. Go to General pane in Preferences window.
2. Change the option for "When document is modified by another application"

<img width="672" alt="screen shot 2018-02-21 at 13 00 32" src="https://user-images.githubusercontent.com/1165044/36462512-3e220894-1707-11e8-80bb-88c74b0657f6.png">

In addition, if you want to prevent unwanted change to "Japanese (Mac OS)", change the priority level of such encodings in Preferences > Format > Edit List (in encoding section).

**Comment by 1024jp** [comment]
No reply anymore? Then, I close this issue.
