### ISSUE TITLE
Get Info option change window width

### ISSUE THREAD

**Issue by juanfcocontreras** [coteditor/CotEditor#783]
If I enable and disable "Get Info", the window size is not preserved. To reproduce it:

- Click "Get Info"
- Info panel is shown
- Click "Get Info"
- Info panel is hidden, but window width is the initial one minus Get Info panel width

The same occurs with Show Incompatibles characters.

I think that this behavior is not wanted, because you can set the preferred window width in Preferences.

**Comment by juanfcocontreras** [comment]
MacOS Sierra 10.12.6

I attach you a screencast:

![screen](https://user-images.githubusercontent.com/4047415/36314221-6e5972f8-1334-11e8-89b0-712ad5a57017.gif)

Thanks!

**Comment by 1024jp** [comment]
Thank you for the screencast.
I understood the phenomenon.

Another question:
On the initial state, did the window have an extra space in the right side to expand the sidebar, or the initial window width was kind of full screen wide?

**Comment by juanfcocontreras** [comment]
The window width was the initial one (1000 px in my case) specified in settings. It isn't the full width of my monitor.

**Comment by 1024jp** [comment]
Thank you for the answer.
I'll try to reproduce the phenomenon with my submachine, which has macOS 10.12, later.

**Comment by 1024jp** [comment]
Thank you for the answer.
I've just succeeded in reproducing your issue.
The sidebar opens inward when there is not enough space to open outward. Then after that, when it closes, the sidebar closes inward because it is the standard behavior.
Honestly speaking, I'd like to say it's by design, at this moment; however, I also understand this is unwanted one.
I'll try to improve it in a future version.

**Comment by 1024jp** [comment]
Ok, I changed the behavior to close sidebar inward (only) when it was opened inward.
This change will be applied to the next CotEditor 3.3.3.
