### ISSUE TITLE
[Feature Request] Support for Underscore Proper Names

### ISSUE THREAD

**Issue by Berovowilare** [coteditor/CotEditor#799]
Hello 

Like on https://www.bible.com/bible/139/1CH.1 I would love if your App can handle underscore proper names.

Thanks

Greetings

**Comment by 1024jp** [comment]
Thank you for the feedback.
Do you mean that you wanna set underline for specific syntax keys in a theme?
Because CotEditor already uses underline for link anchors, I'll not implement underline for other things.
Sorry.

**Comment by Berovowilare** [comment]
No in the Chinese text from the link there  have all proper names a underline which shows to the reader it is a proper name and not characters which has by itself another meaning. If I copy paste such proper names the underline will be there in Word, but lost in CotEditor. I know Sublime Text, BBEdit and so on also can't handle this. But I think you have more interest in Asian characters so I hoped you are willing to support this.

Greetings

**Comment by 1024jp** [comment]
Because that underline information is not a part of a plain-text. CotEditor, Sublime Text and BBEdit are all plain-text editors. They cannot handle such info.
The underline information is kind of additional layout information, such as font or text color, which only rich text can handle. 
And, Word is a rich text editor. It's different.
