### ISSUE TITLE
Hotkey feature

### ISSUE THREAD

**Issue by asasuzumi** [coteditor/CotEditor#803]
Please consider to implement the hotkey feature to bring the all windows in front like iTerm2. I believe this feature is convenient in a situation where CotEditor and two other softwares are used simultaneously.

Thank you.

**Comment by 1024jp** [comment]
It already exists. You can assign your original key binging to __Window__ > __Bring All to Front__ command.

![screen shot 2018-03-22 at 8 41 49](https://user-images.githubusercontent.com/1165044/37743333-0148033a-2dad-11e8-8818-0ce8000772ef.png)

**Comment by asasuzumi** [comment]
I'm sorry I was not clear. Please let me explain further.

I would like to get the system-wide hotkey feature to bring all CotEditor windows to the front. For example, it is very useful if I can switch to CotEditor imediately while I am using Safari, Terminal or other applications. I know that I can switch between two applications easily using Cmd-Tab. But I am confused when I switch between three or more applications. Although Spotlight may be solve this problem, this solution becomes to be complex if I am using the input method in the mode Hiragana not English.

Thank you.

**Comment by 1024jp** [comment]
> I would like to get the system-wide hotkey feature to bring all CotEditor windows to the front.

I see. Sorry for my misunderstand.
However, then I have to say I'll not implement this feature, since it would be a feature not for specific normal applications but for some system-wide helper application such as [CLCL Lite](http://itunes.apple.com/app/clcl-lite/id495511246?mt=12) or [Alfread](https://www.alfredapp.com).

FYI, this article may help you: [Is there a way to start a specific application with a keyboard short cut?](https://apple.stackexchange.com/questions/54/is-there-a-way-to-start-a-specific-application-with-a-keyboard-short-cut)
