### ISSUE TITLE
[Feature request] MS Windows like home / end

### ISSUE THREAD

**Issue by dullus** [coteditor/CotEditor#805]
Hello,

It would be nice to have some settings to allow Home / End keys on extended Apple keyboard behave like in MS Windows:
Home - moves cursor at beggining of current line (same as CMD+LArrow)
End - moves cursor at end of current line (same as CMD+RArrow)

Other editors for macOS such as Atom or Visual Studio Code allows that behavior.

**Comment by 1024jp** [comment]
I'd like not to change the behavior of Home / End keys because the default commands for Home / End are already assigned to "to document top" / "to document end", which are the standard behavior in the macOS world.

However, I understand some users want to customize action for those keys, although the current implementation of the CotEditor's Key Binding feature doesn't allow them. I'll consider.

**Comment by 1024jp** [comment]
I close this issue because #839 will take the request to customize key bindings over.

**Comment by h8ku** [comment]
How do I setup home/end keys to work like on Windows in CotEditor? I couldn't find anything explaining it in searching.

I'd rather use CotEditor for simple writing and the macOS key bindings are not my favorite. I'll use Visual Studio Code until I can figure it out...

**Comment by 1024jp** [comment]
> How do I setup home/end keys to work like on Windows in CotEditor?

You can change keyboard shortcuts for menu commands in Settings > Key Bindings.

<img width="712" alt="Image" src="https://github.com/user-attachments/assets/720d18b3-f1cb-43b5-8d48-0ad68154e3cf" />
