### ISSUE TITLE
character count and location should increment by 2 for crlf line endings

### ISSUE THREAD

**Issue by alvint** [coteditor/CotEditor#827]
This issue is closely related to issue #828.

## Environment
- CotEditor: 3.4.2 (257)
- System: macOS Version 10.13.5 (Build 17F77)
- Language: English

## Short Description
When navigating past a new line in a file with CRLF line endings, the character count and location should increment by 2.

## Steps to Reproduce the Issue
- Create a new file.
- Set line endings to CRLF.
- (!) Add a new line. The character count and location increment by only one if the "Count each line ending as one character" option is selected, and count/location are not incremented at all if the option is clear.

## Expected Result
Count/location should increment by 0, 1 or 2, depending on the outcome of issue #828.

**Comment by 1024jp** [comment]
Character counting is very complex.
Furthermore, there is no single **correct** way.
Besides CRLF, it is also question whether a surrogate pair is a single character, or whether an emoji consists of multiple (surrogate) characters would be counted as a single character.
Therefore, I don't think CRLF **should** be counted as two characters.

Regarding CotEditor, I (wanna) keep it very simple. Therefore, the current CotEditor count characters as they visually presented. This way is easy to understand (also for non-programmers) and also performance efficient.

Currently, with "length", CotEditor counts characters like UTF-16 (CRLF is two characters, and a surrogate pair is also two characters). You can see it instead of "character count" in the document Inspector pane.

<img width="846" alt="screen shot 2018-12-12 at 19 53 59" src="https://user-images.githubusercontent.com/1165044/49865232-bfdf0f80-fe47-11e8-9688-439bf442e34a.png">

A future improvement adding more detailed options for character counting may be good. And actually it is in my todo list. But I don't have a fixed plan for that yet.
