### ISSUE TITLE
Auto save overwrites files unexpectedly in non-macos shared folders like smb

### ISSUE THREAD

**Issue by bob-hta** [coteditor/CotEditor#829]
### Problem:
When auto-saving option is enabled,
  opening a text file in non-macos shared folders(like smb folder),
  editing it,
  and exiting cot editor
 makes the text file overwritten without notification. 

This leads to overwrite shared files unexpectedly when opening the files just for preview.

### Expected:
In non-macos shared folder,
even when auto-saving option is enabled,
save dialog always appears.

**Comment by 1024jp** [comment]
Sorry for my **very late** response.
This is the behavior of the standard macOS applications, and I believe that CotEditor should follow the standard behavior of macOS applications.
Since adding a specific branching process for a specific storage environment may cause unintended side effects, please let me leave it as it is now.
