### ISSUE TITLE
Request: allow keybindings without command key

### ISSUE THREAD

**Issue by tedthetrumpet** [coteditor/CotEditor#839]
I'd like to use ctrl-down-arrow and ctrl-up-arrow to move lines up and down, but it looks like shortcuts require the command key. Is there a good reason for this? Could this be changed?

**Comment by alvint** [comment]
For one thing, ctrl-up/down are already mapped to PAGE UP/DOWN on the mac, and these are standard Mac shortcuts so having them do something else--especially something that modifies the text when the user isn't expecting it--would be very confusing and unwanted by most people. Some IDEs use shift-ctrl-down for this operation so that may be a better choice.

**Comment by tedthetrumpet** [comment]
I don't think I've explained myself clearly, sorry. I was not asking for the *default* shortcut to be changed, just for the ability to change a shortcut myself. Apparently, the CotEditor preferences do not allow *any* shortcut that does not include the command key? Also, I'm not sure that's correct, that ctrl up/down the standard shortcuts for page up/down – that's Fn up/down.

**Comment by alvint** [comment]
My mistake--I thought you were asking to change the default.

Interestingly, ctrl-up/down is mapped to multiple things by default on MacOS. Nowadays by default they map to Mission Control and Exposé respectively, but if you remove them they map to functions that work similarly to the PAGE UP/DOWN you get when you use Fn-up-down. The difference is that it bypasses the scrolling animations--at least in text editing widgets.

**Comment by bungle** [comment]
Yes, I would prefer to change some of the settings too:
1. home / end -> start of line, end of line (cursor moved updated)
2. page down / page up -> to also move cursor

So option to configure keybindings would be great! This is a really nicely done editor.

**Comment by 1024jp** [comment]
Taking a long time, but this request will be finally implemented in the next CotEditor 4.1.0😉

**Comment by jan-malkiewicz** [comment]
I've CodEditor 4.2.1 and I could not find a way to modify behaviour of Home, End, PageUp and PageDown buttons.
Could you please explain how to do it?
I would like change the Home, End button to work like in Windows (the same as crtl + arrow on mac)

**Comment by johnny-the-coder** [comment]
I've CodEditor 4.2.1 and I could not find a way to modify behaviour of Home, End, PageUp and PageDown buttons.
Could you please explain how to do it?
I would like change the Home, End button to work like in Windows (the same as crtl + arrow on mac)

**Comment by 1024jp** [comment]
@johnny-the-coder You can modify those behaviors in Preferences > Key Bindings > Menu Items.

**Comment by johnny-the-coder** [comment]
Hi 1024jp, but where exactly i looked all available items in Key Bindings -> Menu Items and I haven't found behaviour related to Home, End (window style).
I would like to achieve that Home button navigates to first column in the line and End button to end of the line.
PageUp and PageDown buttons also seems no to work.

Additionally if i hold a button it does not produce more chars - if i press and hold a key only one char is produced in the editor - can it be changed with a setting - if so could you explain where?

**Comment by 1024jp** [comment]
@johnny-the-coder The current implementation can change only the commands available in the menu. Therefore, such key binding actions that are implemented at the editor level but not in the menu cannot be modified. Likewise, CotEditor accepts only a single character keystroke (+ modifier keys, such as Shift, Command, etc) for shortcuts. They are by design.

**Comment by jan-malkiewicz** [comment]
@1024jp Would it be possible to implement those two features in the (nearest) future? I like the editor a lot but lack of those features is (for me) a bit annoying since i'm new in mac world and it's hard to customise. 
I guess many "newcomers" from other platform would be a bit confused by the different behaviour in CotEditor.

**Comment by johnny-the-coder** [comment]
@1024jp Would it be possible to implement those two features in the (nearest) future? I like the editor a lot but lack of those features is (for me) a bit annoying since i'm new in mac world and it's hard to customise.
I guess many "newcomers" from other platform would be a bit confused by the different behaviour in CotEditor.

**Comment by 1024jp** [comment]
> Would it be possible to implement those two features in the (nearest) future?

Hmm, the first one, can be added to the to-do list, but I can not promise it will be done in the near future. The second one, using multiple keys for a shortcut, is the one that CotEditor does definitely not support.


> I guess many "newcomers" from other platform would be a bit confused by the different behaviour in CotEditor.

CotEditor (extremely) aims to behave in the macOS manner. So, sorry, but those people who don't wanna accustom themselves may not be our target.

**Comment by bungle** [comment]
@1024jp,

Can you add to the menu some things like:
- move to the end of the line (so one can bind that to `END` key)
- move to the start of the line (so one can bind that to `HOME` key)
- make PAGE UP / PAGE DOWN also move caret

> CotEditor (extremely) aims to behave in the macOS manner. So, sorry, but those people who don't wanna accustom themselves may not be our target.

All extremism is not good. VSCode and all JetBrains editors on macOS have different behavior than CotEditor. A lot of programmers use CotEditor as a quick editor in addition to their bigger IDEs. Now jumping between those two is most annoying because of the mentioned issues with `END`, `HOME`, and to some extend `PAGE UP` and `PAGE DOWN` behavior.

I wish you are open to reconsider whether the extremism or purism in this case is hurting more than what it is good for. Apple has had eras where they wanted to go minimilastic and think too much differently, only to end up with worse products.

**Comment by 1024jp** [comment]
> Can you add to the menu some things like:

Yes, as I mentioned above, I don't reject this request. I also think it must be helpful for some users. It is just an issue about the priority. 


CotEditor is an OSS project actually developed only by me in my spare time for free. I cannot implement all requests in a short time even if they look good. I just do step-by-step from ones that are easier to implement, more critical, more reasonable, have an impact on more number of users, and look more interesting personally.


> VSCode and all JetBrains editors on macOS have different behavior than CotEditor (by default, and I think most of the programmers' editors)

I know. They are not my business and users have the right to choose other editors. CotEditor has its own philosophy.

**Comment by bungle** [comment]
@1024jp this is definitely my favourite small editor, even with this keybinding thing. I checked that Apple Pages and Microsoft Word also differ in these (and I couldn't find easily how to change).

**Comment by johnny-the-coder** [comment]
Hi, any update on this?

**Comment by 1024jp** [comment]
I come here again just to maintain existing issues/requests.

The latter replies in this thread were talking about another topic than the original request in addition to this ticket has already been closed by implementing the original request.
If you still have the request, please open another issue and organize the points again; otherwise I'll just forget it.
(It doesn't mean I'll implement it in the near future.)

**Comment by stl-victor-sudakov** [comment]
Any updates on this? It is still not possible to make good use of the Home and End keys on the additional keyboard?

**Comment by stl-victor-sudakov** [comment]
> What does this “this” refer to? 

"this" refers to the possibility **to make good use of the Home and End keys on the additional keyboard**, as I wrote in the comment you are replying to.

Specifically, as written in one of the previous comments:

> Can you add to the menu some things like:

> move to the end of the line (so one can bind that to END key)
move to the start of the line (so one can bind that to HOME key)
make PAGE UP / PAGE DOWN also move caret

**Comment by johnny-the-coder** [comment]
I've also struggled for a long time with the problem of END/HOME buttons.
Luckily, today, I've found a solution (workaround) in an another issue related to that :)

https://github.com/coteditor/CotEditor/issues/1674
