### ISSUE TITLE
Document icon template

### ISSUE THREAD

**Issue by grylem** [coteditor/CotEditor#846]
Maybe you can also share document icont template?

**Comment by 1024jp** [comment]
That's a good idea.
Thank you for the suggestion.
I'll prepare it when I have time.

**Comment by grylem** [comment]
thank you it will be great

**Comment by grylem** [comment]
please do not forget

**Comment by 1024jp** [comment]
I don't forget. But, this task is not so high priority for me. I'll do when I feel like doing.
Actually, I will make document icons by myself when a new document type is added. Why you then need it?

**Comment by grylem** [comment]
I apologize for my impatience
I like CotEditor and i like its icons. I would like make icons for some custom file, which I associate with CotEditor for one style icons etc.
I will have patience and will wait
Thanks.

**Comment by 1024jp** [comment]
Sorry for my late reply. However, I (finally) decided the license of the image resources to handle them more strictly than the source code in order to protect the project from evil pirate editions of CotEditor that regrettably happen sometimes. Reusing source code is ok for the macOS application development ecosystem, it's open source. However, in my opinion, just copy the entire application and sell it in the Store is what I do not want to see. The image resources are, on the other hand, more application specific. It's like the face of the application and there is no reasonable excuse to use it in other applications. So I decided not to distribute the image source files as long as I organize this project.

Sorry for taking the time to answer it.
