### ISSUE TITLE
[request] Select inside of parentheses when doubly clicked / 括弧文字をダブルクリックで内部のみを選択を希望

### ISSUE THREAD

**Issue by kkdd** [coteditor/CotEditor#849]
こんにちは。
括弧文字をダブルクリックしたとき、現状は、下記例のように括弧文字を含めて選択されるようです。
* 例： ```(abc, def)```

私は上記よりも、下記例のように内部のみが選択される方が、テキスト編集作業効率が良く、例えば内部を対象に cut, copy, paste することの方が多いです（人によると思いますが）。
* 例： ```abc, def```

というわけで内部のみを選択対象にする方法も欲しいと思っています（人によると思いますが）。

**Comment by unnamedd** [comment]
Hi @kkdd,
do you mind to write your issue in English for those who doesn't understand Japanese be part of your issue?

@1024jp do you mind if I ask this here? I'm following the project and unfortunately I don't know Japanese.

**Comment by alvint** [comment]
Hey @unnamedd, Google Translate doesn't suck as much as it used to. It's not good, but it usually (sometimes) does the job adequately enough to get the gist of the conversation, and it hardly takes any time at all.

In this case, I believe kkdd is asking if the action of double-clicking on a parentheses/bracket/etc (which selects all the text inside the parentheses) could be altered so that it doesn't include the parentheses. For example, if you double-click on the `(` in `(abc, def)`, the whole thing gets selected. kkdd is asking that only `abc, def` be selected.

@1024jp: If I had a vote, my vote would be against this, since it would be unexpected if the item you're clicking on is not part of the selection. As a compromise, how about adding an option in settings where triple-clicking text within brackets would select the text within the brackets. Or if the text is not within brackets, select the line as usual?

**Comment by kkdd** [comment]
Hello,
Double-clicking a parenthesis is observed to select the parentheses and the inside content in present Coteditor:
* ```(abc, def)```, for example

I personally hope that Coteditor would have another functionality of selecting the inside content only, on the other hand:
* ```abc, def```, for example

**Comment by 1024jp** [comment]
クリックした文字自身が選択に含まれないのは、macOSの一般的な振る舞いに反するかと思います。
また、オプションを設けるほどニーズがあると思わないので、処理が煩雑になることもあり提案を棄却させてください。



It is not natural behavior (at least in the macOS world) that the clicked character is not included in the selection.
So, I will not adopt it also because I suppose there are not so many needs.


---
Regarding the language to write issues, I will not ban writing it in Japanese because I want to hear feedback also from users who are not fluent in English.

I always add English translation for the issue title at least it is written in Japanese. Furthermore, I sometimes add English translation when I feel the issue is important or needs a discussion. But adding an English translation to all Japanese issues is too much work for me. Unfortunately, Google translate does not always work especially Japanese -> English translation. So, please just ask in a reply if you wanna know the content (just like this case). I, or a volunteer, will translate.

**Comment by kkdd** [comment]
Thank you for your consideration.

So I hope some method to change selection after double-clicking

1. firstly selecting by double-clicking on a parenthesis as follows: "abc ```{def ghi}``` jkl"
2. then changing it to its inside by some method (but presently not existing) as follows: "abc {```def ghi```} jkl"
