### ISSUE TITLE
Enable Code Intelligence for a vast amount of languages via Language Server Support

### ISSUE THREAD

**Issue by gobijan** [coteditor/CotEditor#874]
Hi would it be feasible to enable code intelligence by offering language server protocol support?

The cool thing is that you only need to implement the protocol once and the code intelligence logic is made available via the language servers (each language can provice one).

See more here: https://langserver.org

**Comment by 1024jp** [comment]
Thank you for the suggestion.
However, it is too much for CotEditor as CotEditor already has its own language parser.
This project is maintained only by a single person using the spare time. Because of that, there is no space to implement a brand-new parser and language definition maitanance system. Sorry.

**Comment by 1024jp** [comment]
cf. [SwiftLSPClient](https://github.com/ChimeHQ/SwiftLSPClient)
