### ISSUE TITLE
AutoSave / Versions support

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#88]
以前 AutoSave 対応をやろうとしたとき、自動保存時にファイル更新通知が来てしまう問題があったため、無効化していた。

今はその問題が解決しているため、AutoSave 対応できるはず？ 有効化してみて動作確認が必要。

**Comment by 1024jp** [comment]
I'm now not sure whether Autosave (in Place)/Versions will be supported on the version 2.2.0.
I suppose Autosave in Place can obstruct users work-flow in many situations especially when they use CotEditor.
May be, I don't support it on v2.2.0, or at least as one of options.

-- 

現在、Autosave (in Place)/Versions の ver. 2.2.0 での実装は見送ろうかと考えています。
CotEditor の利用場面を考えると、Autosave がユーザのワークフローを邪魔する可能性が高いためです。
もしやるとしても v 2.2.0 以降に、設定で無効にできるオプションをつけた上でサポートしたいと思います。
Autosave in Place を有効にした時に初めて使える Versions や タイトルバーからのファイル名変更なんかは便利だから今すぐ取り入れたいくらいなんですけどね、いやはや...。

**Comment by 1024jp** [comment]
Finally, I've implemented the feature.
Now, it must work correctly.
I introduced it as an option since some of users may not want to let overwrite their files without permission.

--- 

ついに追加しました。多分今度こそ正常に動くはずです。
勝手に上書きされるのが嫌な人も多いと思うのでオプション扱いとします。

![screen shot 2015-10-14 at 01 16 15](https://cloud.githubusercontent.com/assets/1165044/10460840/4ec67678-7211-11e5-8edd-e8aa90551c20.png)
