### ISSUE TITLE
Font size in outline

### ISSUE THREAD

**Issue by JRPtau** [coteditor/CotEditor#946]
Thank you for your work! I'd like to ask to add a font size selector for the outline sidebar in CotEditor. I would personally prefer if it will scale up/down together with the main text by Command-(-/+), but any option in Preferences or menu will be also OK.

**Comment by 1024jp** [comment]
Thank you for the request.
I've just improved the outline view to accept Command-(-/+/=) shortcuts.
Due to some reasons, I didn't make the font size sync with the main text editor.
Therefore, this is a kind of a hidden feature but still useful for uses who wanna change font size of outline inspector, IMPO.
