### ISSUE TITLE
Merging all window shortcuts cannot be customized

### ISSUE THREAD

**Issue by hrxind** [coteditor/CotEditor#955]
Merging all window shortcuts cannot be customized？
This APP is currently the best text software for the MACOS platform. It's very, very good. There are two regrets:
1. Merge all windows - cannot customize shortcuts
2. Not the default multi-label
It would be great if these two problems were solved.
Is there any way to solve the first problem?

**Comment by hrxind** [comment]
I will focus on the progress of this issue and work together to make this APP better.

**Comment by hrxind** [comment]
Strange. Aren't developers concerned about this?

**Comment by 1024jp** [comment]
"Merge All Windows" command is omitted from the shortcut cutomization purposely due to a technical reason. The commands relating to window tabbing in the Window menu are added afterwards automatically by the system and developers cannot touch like other normal commands.  

https://github.com/coteditor/CotEditor/blob/9b28d388fea800d3335e9216562314a2611b7174/CotEditor/Sources/MenuKeyBindingManager.swift#L192-L198

> 2. Not the default multi-label

Sorry, but I didn't understand this item well. Could you explain some more?


> Strange. Aren't developers concerned about this?

CotEditor is a small project that is developed by a single non-professional person. Therefore, I cannot invest all my effort into all the issues evenly and rapidly. It takes time sometimes.

**Comment by hrxind** [comment]
I understand. I'm sorry. Thank you for your reply.
Multiple tags, multiple files are completed in one window, and multiple files are switched through tags in one window.
Thank you for developing such a good APP, very useful, very suitable for me, thank you.

**Comment by hrxind** [comment]
I'm so happy that I found the multi-label function. This app is really good.
Now there is a new problem:
The email address in the file does not want to have a URL (e.g. admin@123.com), so that the email address can be displayed properly. How to operate?

**Comment by 1024jp** [comment]
> The email address in the file does not want to have a URL (e.g. admin@123.com), so that the email address can be displayed properly. How to operate?

You can toggle the "Link URLs in document" option in General pane in the preferences window so that the links to email addresses are also disabled. However, as the label of the option says, it also disables links to normal URL (like http://example.com). There is no option to disable only email address link.

<img width="672" alt="Screen Shot 2019-05-26 at 6 35 55 PM" src="https://user-images.githubusercontent.com/1165044/58379933-32523f00-7fe5-11e9-8d5a-2f8c7f74132c.png">

**Comment by hrxind** [comment]
This is a defect and I hope to improve it. Thank you for your reply. Good luck!
