### ISSUE TITLE
Long URLs in text/notes are broken in resulting PDF

### ISSUE THREAD

**Issue by crankygeologist** [coteditor/CotEditor#958]
There is an issue with URL link conversion when printed or saved to a PDF. Current functionality recognizes the text after "http://" as a link only until the end of the line on the resulting PDF page. Once the system inserts the new line symbol, the text is still shown underlined, but it is not the part of the link anymore — this is where the break in link formatting happens.

Steps to Reproduce:
1. Open the CotEditor.
2. Print > PDF > Save to PDF a text file containing a long, multi-line URL.

Expected Results:
The full URL should apply to the entire length of linked text.

Actual Results:
The linked text is shown in the resulting PDF, but the URL after the first line is incomplete, which often takes the user to a 404 page for that domain.

Example long, multi-line URL:

http://www.jaycoowners.com/forums/f32/just-bought-jay-feather-2011-x20e-and-cant-turn-on-water-heater-3703.html#post71139

**Comment by 1024jp** [comment]
Thank you for the report.

This phenomenon is actually unexpected and a kind of interesting...
Because I've just forgotten to implement URL links for printed documents so far. Then, the Cocoa framework (the native framework for macOS applications by Apple) tried creating links in PDF file automatically but wrongly under the condition you reported.

Well, anyway, I've just implemented the URL linking for printed documents officially and thereby the issue is also solved.
Thank you again. The change will be shipped with the next version, CotEditor 3.7.5.

**Comment by crankygeologist** [comment]
Thank you, so much, for the quick fix. I have also filed a bug report with Apple.

**Comment by crankygeologist** [comment]
Thank you. Is there a way I can donate money to the CotEditor project?

Cheers,
Ken
