### ISSUE TITLE
Performance issues with large text files

### ISSUE THREAD

**Issue by rsahara** [coteditor/CotEditor#959]
## Environment (環境)

- CotEditor: 3.7.4 (351)
- System: macOS バージョン10.14.4（ビルド18E226）
- Language: Japanese

## Short Description (簡単な説明)

Slow at editing the end of a large text file.

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

- Extract and open this file: [メモ2.txt.zip](https://github.com/coteditor/CotEditor/files/3200435/2.txt.zip)
- Press COMMAND+DOWN to go to the last line.
- Type a few lines of text. For example:
```
test
test
test
test
```
- Compare with MacOS's pre-installed text editor.

## Expected Result (期待される挙動)

Edit text files as fast as MacOS's pre-installed text editor if possible. (This is just a text file without syntax highlight.)

**Comment by 1024jp** [comment]
duplicated #957

**Comment by 1024jp** [comment]
Because CotEditor processes more things (character count, invisible character drawing, line-height adjustment, etc...) than TextEdit.app, it is sometimes hard to be the same as TextEdit.app especially on performance.
However, regard to the latest version, CotEditor 3.7.4, there is a performance regression due to a workaround of the issue on Swift 5.1.
This regression has already been solved and this fix will be shipped with the next version.
