### ISSUE TITLE
Insert file content via drag/drop

### ISSUE THREAD

**Issue by lojza3d** [coteditor/CotEditor#967]
Hi, just a small request: would it be possible to extend the "Insertion Format" within "File Drop" configuration with something like <<<FILE-CONTENT>>> variable?

This would, naturally, insert the whole file content at the drop position.

Thanks for considering! :)

**Comment by 1024jp** [comment]
Thank you for the request.
I'll implement in the next version (or 3.7.7).

**Comment by 1024jp** [comment]
Implemented in CotEditor 3.7.6😉

<img width="790" alt="Screen Shot 2019-06-09 at 8 21 44 PM" src="https://user-images.githubusercontent.com/1165044/59158364-1f704d80-8a6e-11e9-939f-0c9d52a0b9ba.png">

**Comment by 1024jp** [comment]
@igithublab Thank you for the feedback. I've just confirmed the phenomenon that file drop settings are not saved if both the syntax styles and extensions are set "All." If one of them is specified and the insert format is `<<<FILECONTENT>>>` in the current CotEditor 4.0.8, it should work correctly.

Because, off course, this is a bug, I'll release a new version fixing it pretty soon.

**Comment by cprcrack** [comment]
Is it possible to setup this so that when you drag a file into a CotEditor window it simply opens the file instead in a new tab?
