### ISSUE TITLE
Number of lines is 1 off

### ISSUE THREAD

**Issue by maziac** [coteditor/CotEditor#976]
V 3.7.8 (360)

Please see here:
![Bildschirmfoto 2019-07-15 um 19 20 18](https://user-images.githubusercontent.com/3081973/61235368-a384b780-a735-11e9-84b3-ac4dfa401d91.jpg)

The number of lines (Zeilen) shows "723" but the cursor is in line (Zeile) "724".

The right number of lines is indeed "724".

**Comment by alvint** [comment]
I think this is correct behavior. The cursor can be placed on 724 because the previous line has a newline at the end of it, but 724 doesn't count as a line until you something is added that line.

Look at it this way: suppose you open an empty file. Since the file is empty, it clearly has no lines, but the cursor must be placed on what would become a line if you typed.

In other words, the cursor only shows where text will be inserted; its presence anywhere doesn't mean it's an actual line yet.

**Comment by maziac** [comment]
Yes, you are right.
Sorry for taking your time.
