### ISSUE TITLE
Feature request: Refactoring support

### ISSUE THREAD

**Issue by shivendra90** [coteditor/CotEditor#982]
Cot is awesome. I have moved from using VSC and PyCharm to Cot all because of the simplicity yet the power it provides. But I think it's still lacking a couple of features. I code mostly in R and Python and would very much appreciate if refactoring was supported. Proper refactoring would pounce VSC that actually does a very bad job when you have to rename definitions/variables.

**Comment by 1024jp** [comment]
In order to implement an intelligent refactoring feature, an intelligent syntax parsing (and proper syntax definition for each language) is required to know the scope of the word to refactor in a document.
Unfortunately, the current CotEditor's syntax definition format is simple and easy just for syntax highlighting and it cannot determine the structure, for example, a range of a code block code, or type of each word.
I understand I need to improve it in the future but with the current implementation, it's hard.

For a simple substitution, you can select the same instances with ⌘D and edit them simultaneously.

**Comment by shivendra90** [comment]
Thanks. Will be looking forward.
