### ISSUE TITLE
Styling with Objective C syntax

### ISSUE THREAD

**Issue by thom-ek** [coteditor/CotEditor#990]
Objective C coloring syntax is missing. Please add :)

**Comment by 1024jp** [comment]
Actually, CotEditor had a syntax style for Objective-C before.
However, after the appearance of Swift, The use of Objective-C is reducing year by year; moreover, most of the users may write ObjC in Xcode.
Currently, in CotEditor, the extension ".m" for Objective-C is used for MATLAB, because I guess there are more users handling MATLAB than Objective-C in CotEditor.
You can substitute the normal C syntax style for minimum highlight.
I understand it's not enough, but sorry, I don't have any plan to re-bundle a syntax style for Objective-C.

**Comment by thom-ek** [comment]
Too bad. Objective C is still used and will for very long time (personally I prefer ObjC rather than Swift). I use CotEditor not for editing these files but for previewing them - I don't always want to open Xcode.

**Comment by willbprog127** [comment]
> sorry, I don't have any plan to re-bundle a syntax style for Objective-C
That's too bad.  I was about to submit an issue about this after coming back to try Cot editor again.

You have some other 'infrequently used' file formats in the supported list, why treat Objective-C users poorly?  The web page for Cot editor says something like "Made just for Mac"...well Objective-C (which isn't included) should have some priority over Erlang, Lisp and Scheme (which *are* included) because it's the original programming language of OS X / macOS before Swift.

Back to Geany, I guess...

**Comment by thom-ek** [comment]
> Back to Geany, I guess...

Try [SubEthaEdit](https://subethaedit.net).

**Comment by c0008** [comment]
Even if Matlab is much more important for an editor on macOS there could be still support for Objective-C syntax without assigning the ".m" extension to it. One could select Objective-C manually when needed.

**Comment by LeoNatan** [comment]
Hello,

For anyone interested, I’ve recreated the C, C++ & Objective-C syntax, you can find it here:
https://github.com/LeoNatan/CotEditor-ObjCSyntax

Thanks
